### ISSUE TITLE
Xcode can't find CDVViewController.h when archiving in Xcode 7.1 beta

### ISSUE THREAD

**Issue by akshaylive** [meteor/meteor#5496]
I recently upgraded to meteor 1.2 and XCode 7. Whenever I build the app to XCode 7, it fails. The project is unable to find Cordova/CDVViewController.h
Selecting "Enable bitcode" to "No" didn't help either.

Here is the screenshot -
<img width="862" alt="mainviewcontroller h xcode today at 5 27 31 pm" src="https://cloud.githubusercontent.com/assets/2084197/10653920/13d74944-7819-11e5-940c-41de1827899b.png">

Please help.

**Comment by martijnwalraven** [comment]
I haven't been able to reproduce this. Using Meteor 1.2 with Xcode 7 seems to work fine, so I assume there is something else going on. From your screenshot, it seems your project may be missing some files. Could you try cleaning the Cordova build directory (`rm -rf .meteor/local/cordova-build`) and running again?

**Comment by teknologist** [comment]
A little googling leads to this:

http://forum.ionicframework.com/t/cordova-cdvviewcontroller-h-file-not-found-in-xcode-7-1-beta/32232

To summarize, this is due to the Xcode 7.1 upgrade.

Quoting the ionic thread:
"Add this line to your Build Settings -> Header Search Paths:

"$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include"
Don't replace the existing line that looks similar, that is still needed to be backwards compatible with Xcode 7 and Xcode 6.4."

This solved it for me.

**Comment by martijnwalraven** [comment]
I tried this with the just released Xcode 7.1, and don't seem to need any workarounds (running Meteor 1.2.0.2). Is this still an issue for anyone else?

**Comment by pfafman** [comment]
I had this issue with Xcode 7.1 but only when doing an archive build for iTunes connect.  Normal build for a device or the simulator was fine.  Adding the above line fixed the issue for the archive build.

**Comment by akshaylive** [comment]
I don't know what the problem was but deleting cordova build directory helped. Thanks, @martijnwalraven

**Comment by mrlowe** [comment]
@akshaylive I think there may still be a problem here. I ran into the same issue after updating to Xcode 7.1. Removing old build folders didn't fix the problem but adding the new platform-specific build path (with $PLATFORM_NAME) did. The only problem is that every time I do a clean build, I'm going to have to add that path again. I assume meteor's cordova module needs to start adding this item to the build path when it generates the xcodeproj ... but of course it's possible that I did something weird, and that there's no real problem with Xcode 7.1 compatibility.

Do you want to reopen this issue, or would you like me to create a new one?

**Comment by martijnwalraven** [comment]
@mrlowe You're right, this does seem like a real issue, but only when archiving, so that may be why I wasn't able to reproduce it. [It has apparently been fixed in Cordova iOS](https://issues.apache.org/jira/browse/CB-9656), so when we upgrade the platforms for Meteor 1.3. In the meantime, I'm afraid you'll have to continue applying the configuration change manually.

**Comment by mrlowe** [comment]
@martijnwalraven aha, you found it faster than I did! As long as we know what the long-term fix should be, I'm happy. Thanks!

**Comment by MastaBaba** [comment]
I had 2 missing files on my first build with Xcode 7.1. After removing the Cordova build in .meteor, I had one missing file (CDVViewController.h).
Adding the extra line in build settings > Search Paths > Header Search Paths > Release then resulted in a successful archive build.

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.

**Comment by vishalrajole** [comment]
Facing same issue on Xcode Version 7.1 (7B91b). Tried 
1) adding header search path as mentioned.  
2) Changing import statements from <> to "" .
3) Changing Preferences --> Location --> Advance to unique.


I am using
Cordova Platform: 6.3.1
Cordova android 5.2.2
Cordova ios 4.2.1

not sure what I am missing.

**Comment by mrlowe** [comment]
@vishalrajole this works fine for me with versions of meteor > 1.3.

**Comment by vishalrajole** [comment]
@mrlowe  thanks for response. This issue is not related to meteor right? It is related to cordova or xCode 7.1 version. 
Pasting exact error for reference:

`In file included from /Users/myProject/phonegap/platforms/ios/Phonegap/Classes/MainViewController.m:28:
/Users/myProject/phonegap/platforms/ios/Phonegap/Classes/MainViewController.h:28:9: fatal error: ‘Cordova/CDVViewController.h’ file not found
#import “Cordova/CDVViewController.h”
^
In file included from /Users/myProject/phonegap/platforms/ios/Phonegap/Classes/AppDelegate.m:28:
/Users/myProject/phonegap/platforms/ios/Phonegap/Classes/AppDelegate.h:28:9: fatal error: ‘Cordova/CDVViewController.h’ file not found
#import “Cordova/CDVViewController.h”
^
1 error generated.

/Users/myProject/phonegap/platforms/ios/Phonegap/Plugins/cordova-plugin-device/CDVDevice.m:24:9: fatal error: ‘Cordova/CDV.h’ file not found
#import “Cordova/CDV.h”`

**Comment by mrlowe** [comment]
@vishalrajole no, sorry. This issue was reported specifically on the meteor repository in github (see above).

The link to the Cordova issue was provided by Martin: https://issues.apache.org/jira/browse/CB-9656

**Comment by mindspot** [comment]
@vishalrajole 
i also facing the same issue on Xcode 8.0

Version Information:
Cordova 6.3.1
Xcode 8.0
Node 6.2.2
Ionic 2.1.0
cordova-ios@4.2.1

![snip20161011_2](https://cloud.githubusercontent.com/assets/11856214/19248290/b9686752-8f61-11e6-8c88-f40db2ad4a53.png)

problem is still exists!

**Comment by Kalizo** [comment]
I get the same issue on XCode 8.0 ! Have you found any solutions @mindspot ?

**Comment by Kalizo** [comment]
Ok, seems to be great with new version _Cordova-iOS 4.3.0_ ! Just update with

`sudo npm install -g cordova`
and
`sudo cordova platform update ios`

After that, make sure you have same Code Signing Identity on YOUR_PROJECT.xcodeproj et CordovaLib.xcodeproj and same Header Search Paths like :

`$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include`

Finally, you can _Clear_, _Build_, _Archive_.
