### ISSUE TITLE
Error on using meteor add cordova:someplugin before having run meteor run ios

### ISSUE THREAD

**Issue by JanMP** [meteor/meteor#9257]
In Meteor 1.6 trying to `meteor add cordova:some-plugin` leads to the following error if you havent `meteor run ios` to trigger installation of cordova before.
```
/Users/pille/.meteor/packages/meteor-tool/.1.6.0-rc.16.2gxi9y++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
Error: Cannot find module 'cordova-registry-mapper'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Module.newPluginId (/tools/cordova/index.js:1:36)
    at Command.func (/tools/cli/commands-packages.js:2027:29)
    at /tools/cli/main.js:1522:15
```
`meteor add cordova:some-plugin`  probably ought to trigger the installation of cordova, too.

**Comment by tripflex** [comment]
Hey guys, i'm getting this error now after upgrading to 1.6.0.1 from 1.6.0 when attempting to add a cordova plugin from github:

```shell
~/c/d/m/f/src ❯❯❯ meteor add cordova:com.scott.serviceDiscovery@https://github.com/scottdermott/cordova-plugin-discovery.git#5431328fbb477d56d14f751fb39b679e7c631220                                                                                                                    ⏎ dev ✱
/Users/myles/.meteor/packages/meteor-tool/.1.6.0_1.1u0toj2.l6xqf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Cannot find module 'cordova-registry-mapper'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Module.newPluginId (/tools/cordova/index.js:1:36)
    at Command.func (/tools/cli/commands-packages.js:2027:29)
    at /tools/cli/main.js:1522:15
```
