### ISSUE TITLE
Project can't start because of error on 'aws-sdk' npm package after upgrading to the version 1.4.2.*

### ISSUE THREAD

**Issue by boldkhuu** [meteor/meteor#8243]
My meteor project can't start after updating to 1.4.2.3. All 1.4.2.* versions are same. Previous versions work well without any error.

'babel-runtime' npm package is installed according to the warning.

Meteor version: 1.4.2.*
Package: 'aws-sdk' npm package
Error:
```Shell
W20170112-15:25:55.205(8)? (STDERR) /Users/boldkhuu/.meteor/packages/meteor-tool/.1.4.2.3nnoaa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170112-15:25:55.274(8)? (STDERR)             				throw(ex);
W20170112-15:25:55.274(8)? (STDERR)             				^
W20170112-15:25:55.274(8)? (STDERR)           
W20170112-15:25:55.275(8)? (STDERR) Error: Cannot find module './node_loader'
W20170112-15:25:55.275(8)? (STDERR)     at require (packages/modules-runtime.js:109:19)
W20170112-15:25:55.275(8)? (STDERR)     at meteorInstall.node_modules.aws-sdk.lib.aws.js (packages/modules.js:374:1)
W20170112-15:25:55.276(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170112-15:25:55.276(8)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20170112-15:25:55.276(8)? (STDERR)     at Module.Mp.import (/Users/boldkhuu/.meteor/packages/modules/.0.7.7.1rfy90q++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170112-15:25:55.276(8)? (STDERR)     at meteorInstall.imports.api.server.utils.js (imports/api/server/utils.js:1:1)
W20170112-15:25:55.277(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170112-15:25:55.277(8)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20170112-15:25:55.277(8)? (STDERR)     at Module.Mp.import (/Users/boldkhuu/.meteor/packages/modules/.0.7.7.1rfy90q++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170112-15:25:55.278(8)? (STDERR)     at meteorInstall.imports.api.users.server.methods.js (imports/api/users/server/methods.js:1:1)
=> Exited with code: 1
```

**Comment by hwillson** [comment]
Hi @boldkhuu - sorry to hear you're having trouble. Any chance you could create and link to a small, runnable reproduction that shows this issue? Being able to repeat the issue will help with troubleshooting. Thanks!

**Comment by boldkhuu** [comment]
@hwillson Thank you for your help. My repo is https://github.com/erxes/erxes. It's version is now on 1.4.1.3. After `meteor update` command, it will display above error message. Can you use this repo to reproduce this issue?

**Comment by boldkhuu** [comment]
@hwillson Sorry. It was my fault. I didn't realize that aws-sdk package accidently was in devDependencies. After moving it to the dependencies, it works fine.

**Comment by hwillson** [comment]
No problem at all - glad to hear you found the problem!
