### ISSUE TITLE
Update to 1.6 fails with TypeError: _extends is not a function

### ISSUE THREAD

**Issue by rcurrier666** [meteor/meteor#9278]
When updating from 1.5.2 to 1.6 (on Windows 10), I get:

C:\Users\Ron\WraithNotes\Meteor\WraithNotes>meteor update
C:\Users\Ron\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_32\tools\isobuild\meteor-npm.js:265
   versions: _extends({}, process.versions)
             ^
TypeError: _extends is not a function
     at Object.<anonymous> (C:\tools\isobuild\meteor-npm.js:223:3)
     at Module._compile (module.js:612:30)
     at Object.Module._extensions..js (module.js:623:10)
     at Module.load (module.js:531:32)
     at Module.Mp.load (C:\tools\tool-env\install-runtime.js:16:29)
     at tryModuleLoad (module.js:494:12)
     at Function.Module._load (module.js:486:3)
     at Module.require (module.js:556:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (C:\tools\isobuild\package-source.js:8:17)

This is originally a really old install of Meteor (1.2 I think) that has been upgraded over time. It's been suggested that uninstalling and then reinstalling 1.6 onto a clean system will work, but I'm going to leave this install alone for a bit in case the team has questions or needs to test a fix.

**Comment by rcurrier666** [comment]
after the require statement at the top of meteor-npm.js, "_extends" is defined as:

`{ __esModule: true, default: [Function: assign] }`

The usage of "_extends" is:

`const currentVersions = {
  platform: process.platform,
  arch: process.arch,
  versions: _extends({}, process.versions)
};`

Something doesn't look right to me, but I'm not sure what is wrong.

**Comment by Pro75357** [comment]
I got the same error, so uninstalled and re-installed using choco.

Now, meteor won't run at all- getting this same error for all of my apps

`TypeError: _extends is not a function
    at Object.<anonymous> (C:\tools\isobuild\meteor-npm.js:223:3)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at Module.Mp.load (C:\tools\tool-env\install-runtime.js:16:29)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)`

**Comment by benjamn** [comment]
Getting `{ __esModule: true, default: [Function: assign] }` for `require("babel-runtime/helpers/extends")` is unexpected, since that module should be a plain CommonJS module.

If you are still experiencing this problem, can you please share

1. the `version` from this file (mine says 7.0.0-beta.3):
```
AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_*\dev_bundle\lib\node_modules\babel-runtime\package.json
```

2. and the contents of this file:
```
AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_*\dev_bundle\lib\node_modules\babel-runtime\helpers\extends.js
```

Here's what that file looks like for me:
```js
var _Object$assign = require("../core-js/object/assign");

function _extends() {
  module.exports = _extends = _Object$assign || function (target) {
    for (var i = 1; i < arguments.length; i++) {
      var source = arguments[i];

      for (var key in source) {
        if (Object.prototype.hasOwnProperty.call(source, key)) {
          target[key] = source[key];
        }
      }
    }

    return target;
  };

  return _extends.apply(this, arguments);
}

module.exports = _extends;
```

If either the `babel-runtime` version or the contents of `babel-runtime/helpers/extends.js` differ from what I showed above, can you recall doing anything that might have resulted in a new global installation of `babel-runtime`, such as `meteor npm install --global some-package` where `some-package` possibly depended on `babel-runtime`?

**Comment by rcurrier666** [comment]
Thanks for the reply.

In the 1.6.0 directory created by the failed install the version and file contents are identical to yours. I also have 5 other copies of extend.js that are different from yours:

```./mt-os.windows.x86_32/dev_bundle/lib/node_modules/babel-runtime/helpers/builtin/es6/extends.js
./mt-os.windows.x86_32/dev_bundle/lib/node_modules/babel-runtime/helpers/builtin/extends.js
./mt-os.windows.x86_32/dev_bundle/lib/node_modules/babel-runtime/helpers/es6/extends.js
./mt-os.windows.x86_32/dev_bundle/lib/node_modules/regenerator-transform/node_modules/babel-runtime/helpers/extends.js
./mt-os.windows.x86_32/isopackets/combined/npm/node_modules/meteor/babel-compiler/node_modules/babel-runtime/helpers/extends.js```

I can share contents of those files if you want (just trying to keep this post short and readable!)

I also still have a 64-bit 1.6.0 directory created by chocolatey. It contains the same version and contents that you asked about. That install worked fine, but Meteor fails to run, giving the error "access denied". Other people on the Meteor forums have also seen this error.

MUP seems to have installed a global copy in

```AppData/Roaming/npm/node_modules/mup/node_modules/babel-runtime/helpers/extends.js```

Renaming it and rerunning the update produces the same failure so that doesn't seem to be the problem (I actually also tried renaming the AppData/Roaming/npm directory and that also made no difference).

Let me know if there is something else I can provide. At least removing the 1.6.0 folder lets me continue to use 1.5.2.2.

**Comment by Pro75357** [comment]
> ...such as meteor npm install --global some-package where some-package possibly depended on babel-runtime

I had also installed MUP globally at some point. I also had a separate node.js install (but uninstalling that didn't help)- Sorry I can't be more specific- I'm currently out of town with no access to that PC for a few days.

**Comment by rcurrier666** [comment]
Since the JavaScript source code is available for edit I added a log message to the top of meteor-npm.js to print the search path using ```require.resolve("babel-runtime/helpers/extends")``` and discovered there were two instances of extends.js that were being included before the one in the 1.6.0 directory:

```
Users/Ron/node_modules/babel-runtime/helpers
Users/Ron/WraithNotes/Meteor/WraithNotes/node_modules/babel-runtime/helpers
``

I renamed them and now the correct version of ```extends.js``` is being picked up. And now ```_extends``` is a function. All good, except now I'm getting:

```
C:\Users\Ron\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

TypeError: _objectWithoutProperties is not a function
    at Function.readDirsFromJSON (C:\tools\isobuild\bundler.js:356:6)
    at C:\tools\isobuild\bundler.js:2305:34
    at Function._.each._.forEach (C:\Users\Ron\node_modules\underscore\underscore.js:153:9)
    at Function.readFromDisk (C:\tools\isobuild\bundler.js:2297:7)
    at Object.readJsImage (C:\tools\isobuild\bundler.js:3234:18)
    at loadIsopacketFromDisk (C:\tools\tool-env\isopackets.js:296:23)
    at C:\tools\tool-env\isopackets.js:112:9
    at Object.exports.noYieldsAllowed (C:\tools\utils\fiber-helpers.js:37:14)
    at loadIsopackage (C:\tools\tool-env\isopackets.js:103:34)
    at new ServiceConnection (C:\tools\meteor-services\service-connection.js:28:21)
    at Object.exports.openServiceConnection (C:\tools\meteor-services\auth-client.js:12:10)
    at openPackageServerConnection (C:\tools\packaging\package-client.js:23:21)
    at _updateServerPackageData (C:\tools\packaging\package-client.js:151:14)
    at C:\tools\packaging\package-client.js:129:12
    at C:\tools\utils\buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.exports.updateServerPackageData (C:\tools\packaging\package-client.js:128:23)
    at C:\tools\packaging\catalog\catalog-remote.js:783:36
    at C:\tools\utils\buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at RemoteCatalog.refresh (C:\tools\packaging\catalog\catalog-remote.js:782:18)
    at Object.catalog.refreshOrWarn (C:\tools\packaging\catalog\catalog.js:48:22)
    at catalog.Refresh.OnceAtStart.beforeCommand (C:\tools\packaging\catalog\catalog.js:21:16)
    at C:\tools\cli\main.js:1517:32
    at C:\tools\utils\buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\cli\main.js:1516:20
```
I don't know if this is because ```promise_server.js``` actually wants one of the ```extends.js``` files I renamed or if it is some other problem. I'll try to track this error down tomorrow.

It seems like, at least for ```meteor.update```, require should search the ```meteor-tool/1.6.0``` directory first. But I don't know enough about the update process to know how to do that.

**Comment by rcurrier666** [comment]
```
Users/Ron/node_modules/babel-runtime/helpers
Users/Ron/myProject/node_modules/babel-runtime/helpers
```
also contained old copies of ```objectWithoutProperties.js```. Removing/Renaming them allowed the update to succeed. But, of course, my project won't compile because it can't find  ```extends.js``` and ```objectWithoutProperties``` because I renamed the copies that are under ```myProject```. Sigh...

Can someone who understands the search paths for ```require``` explain why the build isn't finding those files under the 1.6.0 directory when I do ```meteor run``` or the update didn't update the files in ```myProject```?

**Comment by abernix** [comment]
@rcurrier666 I believe you should be able to examine the search path for the module resolution in your code by examining `module.paths` (via `console.log`, for example) before the `require`.

**Comment by JeremyKells** [comment]
I was also having this issue on windows 10, though with a new install of 1.6, and believe there is an issue with the paths, or possibly a symlink (or windows equivalent) missing?

Looking at the module search path (added `console.log(module.paths` to top of meteor-npm.js) shows that it starts in current directory, then steps back up through each parent directory, looking for `node_modules` directories that it would then search for `babel-runtime/helpers/extends`.

```
'C:\\Users\\Jeremy\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\tools\\isobuild\\node_modules',
'C:\\Users\\Jeremy\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\tools\\node_modules',
'C:\\Users\\Jeremy\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\node_modules',
'C:\\Users\\Jeremy\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\node_modules',
'C:\\Users\\Jeremy\\AppData\\Local\\.meteor\\packages\\meteor-tool\\node_modules',
'C:\\Users\\Jeremy\\AppData\\Local\\.meteor\\packages\\node_modules',
'C:\\Users\\Jeremy\\AppData\\Local\\.meteor\\node_modules',
'C:\\Users\\Jeremy\\AppData\\Local\\node_modules',
'C:\\Users\\Jeremy\\AppData\\node_modules',
'C:\\Users\\Jeremy\\node_modules',
'C:\\Users\\node_modules',
'C:\\node_modules'
```

This will not find `AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\babel-runtime\helpers\extends.js`

I copied the entire `AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules` directory to `AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\node_modules`, (skipping files where path was too long), and it's now works (at least I can `meteor create app` and run it with `meteor` again!)

But this is not ideal of course, any suggestions on how to fix the paths properly?

**Comment by Jorge131** [comment]
It's also happening to me, exactly the same error... It all started when I reinstalled the last Meteor update, and now any function that starts with Meteor works, everytime the same error you've posted.

**Comment by chanhngo** [comment]
![image](https://user-images.githubusercontent.com/26425056/32608586-630c10ec-c58f-11e7-823f-a27e51334d11.png)
I do it folow what you told me but it's not working. Here is error: 
![image](https://user-images.githubusercontent.com/26425056/32608669-b1ed29ee-c58f-11e7-8fea-3c444ad6fd5e.png)

**Comment by chanhngo** [comment]
please help me to solved it. I have an exercise for this open source :'(

**Comment by JeremyKells** [comment]
@chanhngo copying the node_modules directory is not a (good) solution to this, but hopefully showing that this 'fixes' the errors will hopefully help lead to a good solution.  I'm not sure how the devs intended the module resolution to find the correct `babel-runtime/helpers/extends`, I think we will need them to take a look at this.

**Comment by Pro75357** [comment]
> copying the node_modules directory 
@JeremyKells thanks for the fix- worked for me. At least I can get back to what I was doing. Hopefully devs fix this one soon- completely breaks meteor. I even tried to nuke everything Meteor related and start from a fresh install, still no dice.

**Comment by inatoff** [comment]
https://forums.meteor.com/t/meteor-error-typeerror-extends-is-not-a-function/40323
I followed this way (removed all babel packages from global node_modules folder) and its worked for me.

**Comment by scottstensland** [comment]
Does anyone have a repeatable solution to this ?  its one thing to futz about until it compiles its entirely another level of beast to automate such that transitioning to the next meteor release is seamless especially when one is not in the thick of coding up the nodejs side of the shop

Please advise

**Comment by hwillson** [comment]
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity (see the [bug issue lifespan](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/ISSUE_TRIAGE.md#bug-issue-lifespan) section of Meteor's traige doc for more information). If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!
