### ISSUE TITLE
[1.3.1] unable to import "sharp" npm module

### ISSUE THREAD

**Issue by DrDanRyan** [meteor/meteor#6726]
I am using a npm library called `sharp` that does image processing with the libvips image processing library (which is written in C). The module worked fine with 1.2.1 and meteorhacks:npm but cannot be imported in 1.3. Note that when you `npm install --save sharp` it uses `node-gyp` to compile bindings to the C library, so it is a bit of a weird npm package in that respect.  Here is the error I get when I try to import on the server:

```
=> Started proxy.

Unable to resolve some modules:

  "./build/Release/sharp" in /Users/dan/Code/sharp-test/node_modules/sharp/index.js (os.osx.x86_64)
  "./lib/versions.json" in /Users/dan/Code/sharp-test/node_modules/sharp/index.js (os.osx.x86_64)

W20160406-16:28:15.887(-4)? (STDERR) dyld: lazy symbol binding failed: Symbol not found: _node_module_register
W20160406-16:28:15.889(-4)? (STDERR)   Referenced from: /Users/dan/Code/sharp-test/node_modules/sharp/build/Release/sharp.node
W20160406-16:28:15.889(-4)? (STDERR)   Expected in: flat namespace
W20160406-16:28:15.889(-4)? (STDERR)
W20160406-16:28:15.889(-4)? (STDERR) dyld: Symbol not found: _node_module_register
W20160406-16:28:15.889(-4)? (STDERR)   Referenced from: /Users/dan/Code/sharp-test/node_modules/sharp/build/Release/sharp.node
W20160406-16:28:15.889(-4)? (STDERR)   Expected in: flat namespace
W20160406-16:28:15.890(-4)? (STDERR)
=> Exited from signal: SIGTRAP
```

Using the module in a standard node script with `require` continues to work fine on my machine as well, just using in Meteor 1.3 with `import` is an issue.

Any suggestions would be greatly appreciated.

**Comment by DrDanRyan** [comment]
The issue with `Symbol not found` was because I did `npm install --save sharp` using my globally installed system npm (from Node 5.x), but am loading the module in Meteor with Node 0.10.x. Since `sharp` is built with `node-gyp` I guess this is an issue.

Removing the `node_modules` directory and running `meteor npm install` fixed the issue. I still get the `Unable to resolve some modules` warnings, but the module functions fine and the server doesn't crash now.

FYI, the warnings come from two issues:
1. "./build/Release/sharp" is a Node add-on so the file is named `sharp.node` and not `sharp.js`; I think this confuses the Meteor module loader.
2. "./lib/versions.json" is `required` in the `index.js` within a `try / catch` block, but the Meteor module loader throws a warning even though the exception is handled in the `catch` block.
