### ISSUE TITLE
[1.8.2-beta.17] TypeError: module.watch is not a function, with dynamic import

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#10660]
The last version of Meteor where the problem did _not_ occur, if applicable. **1.6.0** (that's what I was on previously)

This is happening on some code that uses dynamic import, here: https://github.com/trusktr/trusktr.io/blob/master/meteor-app/client/imports/routes/index.js#L237

The full error stack is:

```
Uncaught (in promise) TypeError: module.watch is not a function
    at eval (/client/imports/apps/polydance.vue:11)
    at eval (polydance.vue:353)
    at dynamic-import.js?hash=c2308c4d377d48aa7a6d21ce779ea5a813112fa3:138
    at fileEvaluate (modules-runtime.js?hash=303a2be7d8ba0d407f0ea530952ce5711e9e7029:346)
    at Module.require (modules-runtime.js?hash=303a2be7d8ba0d407f0ea530952ce5711e9e7029:248)
    at Module.moduleLink [as link] (modules.js?hash=d33389da3570313bc3bde3199d2055011f8afcb9:320)
    at getNamespace (dynamic-import.js?hash=c2308c4d377d48aa7a6d21ce779ea5a813112fa3:187)
    at dynamic-import.js?hash=c2308c4d377d48aa7a6d21ce779ea5a813112fa3:40
    at meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1234
    at async importApp (index.js:229)
```

which leads to [here](https://github.com/trusktr/trusktr.io/blob/master/meteor-app/client/imports/apps/polydance.vue#L162) (but the transpiled version has `module.watch(require('...'))`.

**Comment by trusktr** [comment]
To reproduce, you should be able to clone https://github.com/trusktr/trusktr.io, then checkout the `meteor-issue-10660` branch, and

```
cd meteor-app
npm i
meteor
```

then open your browser to http://localhost:3000/polydance-vue

**Comment by trusktr** [comment]
Update the reproduction, forgot to specify cloning the submodule.

**Comment by sferoze** [comment]
@trusktr were you able to solve this? After upgrading to 1.8.2 I am also getting TypeError: module.watch is not a function

**Comment by sferoze** [comment]
@trusktr are you using coffeescript by any chance? I wonder if it is related to coffeescript

**Comment by anoop-chauhan** [comment]
Hi, @trusktr  and @sferoze , are you able to solve this? After upgrading to 1.8.2 from 1.8.1, I'm also getting TypeError: module.watch is not a function
