### ISSUE TITLE
Cannot import an NPM package in the Meteor shell unless it's imported somewhere in the app

### ISSUE THREAD

**Issue by mdorn** [meteor/meteor#9488]
It's often useful when you first install an NPM package via `meteor npm install` to work with it in the shell before actually putting it in one of your application files.  This worked in 1.4 but appears to have stopped working in 1.5 and is still broken in 1.6.

- The version of Meteor showing the problem. **1.6 (and 1.5, but not sure which subversions if not all of them)**
- The last version of Meteor where the problem did _not_ occur: **1.4 (I tested it on 1.4.4.3)**
- The operating system you're running Meteor on: **MacOS**

**Expected behavior**:

```
meteor npm install --save moment
meteor shell
> import moment from 'moment';
> moment.now()
1513722727773
```

**Actual behavior**

```
meteor npm install --save moment
meteor shell
> import moment from 'moment';
Error: Cannot find module 'moment'
    at makeMissingError (packages/modules-runtime.js:231:12)
    at require (packages/modules-runtime.js:241:19)
    at repl:2:14
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at evalCommandPromise.then (packages/shell-server/shell-server.js:246:21)
    at /Users/mdorn/.meteor/packages/promise/.0.10.0.ak8m4i++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Reproduction**

On Meteor 1.6.0.1:

```
meteor create myapp
cd myapp
meteor 
```

In a second terminal:

```
meteor npm install --save moment
meteor shell
> import moment from 'moment';
```

Note an error is thrown.

**Comment by hwillson** [comment]
Hi @mdorn - this is by design. The meteor shell works against your current application bundle. Meteor goes to great lengths to make sure that only the packages that you're truly using in your application are included in your app bundle. Since you haven't referenced `moment` anywhere in your application, Meteor hasn't bundled it into the app bundle. If you were to say update `/server/main.js` to include a `import moment from 'moment'` call, then `moment` would be included in your app bundle, and be reachable via `meteor shell`. 

If you think this should work differently, please consider opening a feature request over in http://github.com/meteor/meteor-feature-requests. Thanks!
