### ISSUE TITLE
Popper is not working with METEOR@2.0-beta.4

### ISSUE THREAD

**Issue by gunnartorfis** [meteor/meteor#11256]
Testing out Meteor 2.0-beta.4 and am receiving a **runtime** error when Popper is installed.

Link to a repo that replicates this: https://github.com/gunnartorfis/meteor-popper-test
Codesandbox showcases that Popper is working as expected using pure React: https://codesandbox.io/s/wizardly-kilby-soc9w?file=/src/App.js

The error I'm receiving is the following:
`modules-runtime-hot.js?hash=d62f7d8ae3407df88cd3e13a9d7d41f65e219d44:234 Uncaught Error: Cannot find module './popper-lite.js'`
I've dug into the code inside node_modules to find anything suspicious without luck, everything looks good to me. The only thing I could guess is that this is related to Typescript.

**Comment by gunnartorfis** [comment]
Is there anything I can do to help solve this issue?

**Comment by renanccastro** [comment]
Hello  @gunnartorfis ! I'm looking into this issue, and it does seem related to the other one we have related to .graphql files. I will keep this issue updated too.
Thanks for reporting and getting a repro.

**Comment by gunnartorfis** [comment]
Awesome. Looking forward to trying it out! We're suffering from such slow rebuild times that drastically impact our everyday development. Tree Shaking + Hot Module Replacement will hopefully help out a ton. Those two features are only available in Meteor 2.0, right?

**Comment by gunnartorfis** [comment]
@renanccastro I can confirm this is no longer an issue in beta 6!
