### ISSUE TITLE
[1.4.2] faker: Cannot find module './lib'

### ISSUE THREAD

**Issue by tnedich** [meteor/meteor#7990]
After updateing project to Meteor 1.4.2 I get this error:

```
W20161029-09:47:38.595(2)? (STDERR) C:\Users\****\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20161029-09:47:38.906(2)? (STDERR)                                             throw(ex);
W20161029-09:47:38.908(2)? (STDERR)                                             ^
W20161029-09:47:38.909(2)? (STDERR)
W20161029-09:47:38.910(2)? (STDERR) Error: Cannot find module './lib'
W20161029-09:47:38.912(2)? (STDERR)     at require (packages\modules-runtime.js:109:19)
W20161029-09:47:38.913(2)? (STDERR)     at meteorInstall.node_modules.faker.index.js (packages\modules.js:372:13)
W20161029-09:47:38.915(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:181:9)
W20161029-09:47:38.917(2)? (STDERR)     at Module.require (packages\modules-runtime.js:106:16)
W20161029-09:47:38.918(2)? (STDERR)     at Module.Mp.import (C:\Users\Admin\AppData\Local\.meteor\packages\modules\0.7.7\npm\node_modules\reify\lib\runtime.js:70:16)
W20161029-09:47:38.920(2)? (STDERR)     at meteorInstall.imports.api.documents.documents.js (imports/api/documents/documents.js:1:1)
W20161029-09:47:38.922(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:181:9)
W20161029-09:47:38.924(2)? (STDERR)     at Module.require (packages\modules-runtime.js:106:16)
W20161029-09:47:38.926(2)? (STDERR)     at Module.Mp.import (C:\Users\Admin\AppData\Local\.meteor\packages\modules\0.7.7\npm\node_modules\reify\lib\runtime.js:70:16)
W20161029-09:47:38.927(2)? (STDERR)     at meteorInstall.imports.api.documents.methods.js (imports/api/documents/methods.js:1:1)
```

OS: Windows 7 64-bit

**Comment by johnsonchandra** [comment]
me too...
OS: macOS Sierra version 10.12

**Comment by abernix** [comment]
@johnsonchandra Please provide your exact error and stack trace.

**Comment by johnsonchandra** [comment]
W20161029-19:36:39.393(7)? (STDERR) Error: Cannot find module './lib'
W20161029-19:36:39.394(7)? (STDERR)     at require (packages/modules-runtime.js:109:19)
W20161029-19:36:39.395(7)? (STDERR)     at meteorInstall.node_modules.faker.index.js (packages/modules.js:370:13)
W20161029-19:36:39.395(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161029-19:36:39.396(7)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20161029-19:36:39.396(7)? (STDERR)     at Module.Mp.import (/Users/johnsonchandra/.meteor/packages/modules/.0.7.7.7z86v0++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161029-19:36:39.397(7)? (STDERR)     at meteorInstall.imports.api.documents.documents.js (imports/api/documents/documents.js:1:1)
W20161029-19:36:39.398(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161029-19:36:39.398(7)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20161029-19:36:39.399(7)? (STDERR)     at Module.Mp.import (/Users/johnsonchandra/.meteor/packages/modules/.0.7.7.7z86v0++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161029-19:36:39.400(7)? (STDERR)     at meteorInstall.imports.api.documents.methods.js (imports/api/documents/methods.js:1:1)

**Comment by johnsonchandra** [comment]
update: after removing npm faker package, it runs ok.

maybe something in faker or meteor not following convention?

**Comment by distalx** [comment]
I had the similar issue - resolved by moving `faker` to `dependencies` from `devDependencies`.

```
/Users/dv/.meteor/packages/meteor-tool/.1.4.2.15d82lf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Cannot find module './lib'
    at require (packages/modules-runtime.js:109:19)
    at meteorInstall.node_modules.faker.index.js (packages/modules.js:409:13)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/Users/dv/.meteor/packages/modules/.0.7.7.7ddnrf++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.server.seeder.user_collection_seeder.js (server/seeder/user_collection_seeder.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/Users/dv/.meteor/packages/modules/.0.7.7.7ddnrf++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.server.seeder.database_seeder.js (server/seeder/database_seeder.js:1:1)
```

**Comment by tnedich** [comment]
@distalx solution also works for me.

**Comment by UmbraLimi** [comment]
Same error in Win 7/64 for me

`[34mW20161029-14:26:22.564(-4)? (STDERR) [39m[35mC:\Users\****\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280[39m
[34mW20161029-14:26:22.636(-4)? (STDERR) [39m[35m						throw(ex);[39m
[34mW20161029-14:26:22.636(-4)? (STDERR) [39m[35m						^[39m
[34mW20161029-14:26:22.636(-4)? (STDERR) [39m[35m[39m
[34mW20161029-14:26:22.636(-4)? (STDERR) [39m[35mError: Cannot find module './lib'[39m
[34mW20161029-14:26:22.636(-4)? (STDERR) [39m[35m    at require (packages\modules-runtime.js:109:19)[39m
[34mW20161029-14:26:22.637(-4)? (STDERR) [39m[35m    at meteorInstall.node_modules.faker.index.js (packages\modules.js:374:13)[39m
[34mW20161029-14:26:22.637(-4)? (STDERR) [39m[35m    at fileEvaluate (packages\modules-runtime.js:181:9)[39m
[34mW20161029-14:26:22.637(-4)? (STDERR) [39m[35m    at Module.require (packages\modules-runtime.js:106:16)[39m
[34mW20161029-14:26:22.638(-4)? (STDERR) [39m[35m    at Module.Mp.import (C:\Users\****\AppData\Local\.meteor\packages\modules\0.7.7\npm\node_modules\reify\lib\runtime.js:70:16)[39m
[34mW20161029-14:26:22.638(-4)? (STDERR) [39m[35m    at meteorInstall.imports.api.documents.documents.js (imports/api/documents/documents.js:1:1)[39m
[34mW20161029-14:26:22.638(-4)? (STDERR) [39m[35m    at fileEvaluate (packages\modules-runtime.js:181:9)[39m
[34mW20161029-14:26:22.638(-4)? (STDERR) [39m[35m    at Module.require (packages\modules-runtime.js:106:16)[39m
[34mW20161029-14:26:22.638(-4)? (STDERR) [39m[35m    at Module.Mp.import (C:\Users\****\AppData\Local\.meteor\packages\modules\0.7.7\npm\node_modules\reify\lib\runtime.js:70:16)[39m
[34mW20161029-14:26:22.639(-4)? (STDERR) [39m[35m    at meteorInstall.imports.api.documents.methods.js (imports/api/documents/methods.js:1:1)[39m
=> Exited with code: 1
`

**Comment by UmbraLimi** [comment]
Same for me of Win7-64

`[34mW20161029-14:26:22.564(-4)? (STDERR) C:\Users\Fraser\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
[34mW20161029-14:26:22.636(-4)? (STDERR) 						throw(ex);
[34mW20161029-14:26:22.636(-4)? (STDERR) 						^
[34mW20161029-14:26:22.636(-4)? (STDERR) 
[34mW20161029-14:26:22.636(-4)? (STDERR) Error: Cannot find module './lib'
[34mW20161029-14:26:22.636(-4)? (STDERR)     at require (packages\modules-runtime.js:109:19)
[34mW20161029-14:26:22.637(-4)? (STDERR)     at meteorInstall.node_modules.faker.index.js (packages\modules.js:374:13)
[34mW20161029-14:26:22.637(-4)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:181:9)
[34mW20161029-14:26:22.637(-4)? (STDERR)     at Module.require (packages\modules-runtime.js:106:16)
[34mW20161029-14:26:22.638(-4)? (STDERR)     at Module.Mp.import (C:\Users\Fraser\AppData\Local\.meteor\packages\modules\0.7.7\npm\node_modules\reify\lib\runtime.js:70:16)
[34mW20161029-14:26:22.638(-4)? (STDERR)     at meteorInstall.imports.api.documents.documents.js (imports/api/documents/documents.js:1:1)
[34mW20161029-14:26:22.638(-4)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:181:9)
[34mW20161029-14:26:22.638(-4)? (STDERR)     at Module.require (packages\modules-runtime.js:106:16)
[34mW20161029-14:26:22.638(-4)? (STDERR)     at Module.Mp.import (C:\Users\Fraser\AppData\Local\.meteor\packages\modules\0.7.7\npm\node_modules\reify\lib\runtime.js:70:16)
[34mW20161029-14:26:22.639(-4)? (STDERR)     at meteorInstall.imports.api.documents.methods.js (imports/api/documents/methods.js:1:1)
=> Exited with code: 1`

**Comment by UmbraLimi** [comment]
Same here for Win 7/64

`[34mW20161029-14:26:22.564(-4)? (STDERR) C:\Users\Fraser\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
[34mW20161029-14:26:22.636(-4)? (STDERR) 						throw(ex);
[34mW20161029-14:26:22.636(-4)? (STDERR) 						^
[34mW20161029-14:26:22.636(-4)? (STDERR) 
[34mW20161029-14:26:22.636(-4)? (STDERR) Error: Cannot find module './lib'
[34mW20161029-14:26:22.636(-4)? (STDERR)     at require (packages\modules-runtime.js:109:19)
[34mW20161029-14:26:22.637(-4)? (STDERR)     at meteorInstall.node_modules.faker.index.js (packages\modules.js:374:13)
[34mW20161029-14:26:22.637(-4)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:181:9)
[34mW20161029-14:26:22.637(-4)? (STDERR)     at Module.require (packages\modules-runtime.js:106:16)
[34mW20161029-14:26:22.638(-4)? (STDERR)     at Module.Mp.import (C:\Users\Fraser\AppData\Local\.meteor\packages\modules\0.7.7\npm\node_modules\reify\lib\runtime.js:70:16)
[34mW20161029-14:26:22.638(-4)? (STDERR)     at meteorInstall.imports.api.documents.documents.js (imports/api/documents/documents.js:1:1)
[34mW20161029-14:26:22.638(-4)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:181:9)
[34mW20161029-14:26:22.638(-4)? (STDERR)     at Module.require (packages\modules-runtime.js:106:16)
[34mW20161029-14:26:22.638(-4)? (STDERR)     at Module.Mp.import (C:\Users\Fraser\AppData\Local\.meteor\packages\modules\0.7.7\npm\node_modules\reify\lib\runtime.js:70:16)
[34mW20161029-14:26:22.639(-4)? (STDERR)     at meteorInstall.imports.api.documents.methods.js (imports/api/documents/methods.js:1:1)
=> Exited with code: 1`

**Comment by ni-ko-o-kin** [comment]
same here. I get ´Error: Cannot find module´ for faker and for [ftpd](https://github.com/sstur/nodeftpd) too if faker is not listed in the devDeps.

**Comment by Gywem** [comment]
The solution you provided of moving the faker to `dependency` is not working for me. I get the same error message you posted, but instead of reference the `faker` index from the `node_module` folder, it does the NPM modules from a meteor package bundled.

Anyone also get this?

**Comment by zvictor** [comment]
I have the same problem, but `faker` is already in my `devDependencies`.

> meteor version: `1.4.2.1-beta.0`
> OS: `mac sierra 10.12 (16A323)`


I tried reseting all my installed packages, as shown below, but it didn't help.

```bash
$ rm -Rf ~/.meteor && rm -Rf node_modules
$ curl https://install.meteor.com/ | sh
$ meteor npm install
$ meteor run
```

as noted by @Gywem, but it is thrown by a Meteor package. In our case, a private package inside the `/packages` folder.

```haskell
W20161101-11:15:42.474(1)? (STDERR)     at meteorInstall.node_modules.meteor.quadric:fixtures.data.Brands.js (/Users/zvictor/development/network/src/.meteor/local/build/programs/server/packages/quadric_fixtures.js:327:684)
```

**Comment by zvictor** [comment]
just found a workaround.
Faker was not in the `NPM.depends` of that package. Adding it there solved the issue.

```js
Npm.depends({
  faker: '3.1.0',
});
```

**Comment by lampe** [comment]
We have the same problem.
```javascript
W20161101-15:49:55.710(1)? (STDERR) /home/michael_lazarski/.meteor/packages/meteor-tool/.1.4.2.bfpvb6++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161101-15:49:55.796(1)? (STDERR)                                             throw(ex);
W20161101-15:49:55.797(1)? (STDERR)                                             ^
W20161101-15:49:55.797(1)? (STDERR) 
W20161101-15:49:55.797(1)? (STDERR) Error: Cannot find module './lib/cheerio'
W20161101-15:49:55.797(1)? (STDERR)     at require (packages/modules-runtime.js:109:19)
W20161101-15:49:55.798(1)? (STDERR)     at meteorInstall.node_modules.meteor.local-test:qlp:qlp-relationable.node_modules.cheerio.index.js (/tmp/meteor-test-run1g6n850/.meteor/local/build/programs/server/packages/local-test_qlp_qlp-relationable.js:1400:28)
W20161101-15:49:55.798(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161101-15:49:55.798(1)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20161101-15:49:55.800(1)? (STDERR)     at Module.Mp.import (/home/michael_lazarski/.meteor/packages/modules/.0.7.7.1wd47ms++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161101-15:49:55.800(1)? (STDERR)     at meteorInstall.node_modules.meteor.local-test:qlp:qlp-relationable.server.tests.Relationable.spec.js (packages/local-test:qlp:qlp-relationable/server/tests/Relationable.spec.js:1:1)
W20161101-15:49:55.800(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161101-15:49:55.801(1)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161101-15:49:55.801(1)? (STDERR)     at /tmp/meteor-test-run1g6n850/.meteor/local/build/programs/server/packages/local-test_qlp_qlp-relationable.js:1411:1
W20161101-15:49:55.802(1)? (STDERR)     at /tmp/meteor-test-run1g6n850/.meteor/local/build/programs/server/packages/local-test_qlp_qlp-relationable.js:1421:3
```

we have this in one of our /packages.

```
    Npm.depends({
        'cheerio': '0.22.0'
    });
```

with `meteor run` this solution works but with  `meteor test-packages --driver-package=practicalmeteor:mocha``

**Comment by namirsab** [comment]
It seems like a bug introduced in the latest versions, because it was working perfectly in 1.4.1.1 with exactly the same configurations for us.

**Comment by abernix** [comment]
Many of the solutions to this issue so far have been incorrectly defined (or missing) packages in `devDependencies`, `dependencies` or `Npm.depends` and I'm not sure if the actual solution to this issue is anything aside from that.

If I'm understanding this issue and the changes in Meteor 1.4.2, it could have been that it was working in previous versions because Meteor 1.4.2 (now) tries to strip unneeded modules from the bundle (see https://github.com/meteor/meteor/commit/1850105f9065cd12fab6739d2e08f853c8835a13) to avoid them being in (and bloating) your production build.

Therefore, if you have a package that is installed in development, but not in your `package.json` (an invisible dependency), it may have been getting copied over directly from the `node_modules` directory in previous versions but is no longer being copied over now if it's not properly identified in `package.json`.

This logic did have a bug during beta and it was revised before the 1.4.2 release to ensure that it doesn't strip `devDependencies` when running in test mode (https://github.com/meteor/meteor/pull/7668/commits/cadf113e6c279116e23d18d224e3c6db64516791, #7832 & #7953).

So it is actually very likely that the same configurations that worked on Meteor 1.4.1.1 might have worked before but do not work in 1.4.2, however, the reason is very likely a missing dependency definition.

**Comment by namirsab** [comment]
In my case, the problem happen when running tests
I have a package with a npm dependency defined with `Npm.depends`
When I run the tests, it complains and throw this error.

```
W20161101-15:49:55.710(1)? (STDERR) /home/michael_lazarski/.meteor/packages/meteor-tool/.1.4.2.bfpvb6++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161101-15:49:55.796(1)? (STDERR)                                             throw(ex);
W20161101-15:49:55.797(1)? (STDERR)                                             ^
W20161101-15:49:55.797(1)? (STDERR) 
W20161101-15:49:55.797(1)? (STDERR) Error: Cannot find module './lib/cheerio'
W20161101-15:49:55.797(1)? (STDERR)     at require (packages/modules-runtime.js:109:19)
W20161101-15:49:55.798(1)? (STDERR)     at meteorInstall.node_modules.meteor.local-test:qlp:qlp-relationable.node_modules.cheerio.index.js (/tmp/meteor-test-run1g6n850/.meteor/local/build/programs/server/packages/local-test_qlp_qlp-relationable.js:1400:28)
W20161101-15:49:55.798(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161101-15:49:55.798(1)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20161101-15:49:55.800(1)? (STDERR)     at Module.Mp.import (/home/michael_lazarski/.meteor/packages/modules/.0.7.7.1wd47ms++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161101-15:49:55.800(1)? (STDERR)     at meteorInstall.node_modules.meteor.local-test:qlp:qlp-relationable.server.tests.Relationable.spec.js (packages/local-test:qlp:qlp-relationable/server/tests/Relationable.spec.js:1:1)
W20161101-15:49:55.800(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161101-15:49:55.801(1)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161101-15:49:55.801(1)? (STDERR)     at /tmp/meteor-test-run1g6n850/.meteor/local/build/programs/server/packages/local-test_qlp_qlp-relationable.js:1411:1
W20161101-15:49:55.802(1)? (STDERR)     at /tmp/meteor-test-run1g6n850/.meteor/local/build/programs/server/packages/local-test_qlp_qlp-relationable.js:1421:3
```

That was not happening in 1.4.1.1

**Comment by abernix** [comment]
@namirsab It's entirely possible.  Since your issue sounds like a different issue than reported here, please make a reproduction repo on GitHub with a bare-minimum reproduction, create a new issue following the instructions for reporting a bug and someone will be happy to look at it!  Would definitely like to get it fixed if it is indeed a problem.

**Comment by namirsab** [comment]
@abernix #7999 here you are!

**Comment by alvestjo** [comment]
I get the same error (Can not find module ./lib) but with the npm module gridfs-stream.
//Jonas

**Comment by nuk** [comment]
Moving faker from `devDependencies` to `dependencies` on npm `package.json` worked for me

**Comment by Gywem** [comment]
I've got to reproduce this issue in a separate repository in github. You can check it out [here](https://github.com/Gywem/meteor-issue-faker-1.4.2.1).

Basically, what I did for raising this issue up was:

* Prepare a Meteor application running on version `1.4.1.1`.
* Prepare a Meteor package using the `1.4.1.1` version and including, importing and using the `faker` dependency.
* Install npm dependencies on both meteor app and package.
* Upgrade Meteor app to `1.4.2.1` version.
* Run the application

You get the issue
```
W20161114-15:18:09.503(1)? (STDERR) Error: Cannot find module './lib'
W20161114-15:18:09.504(1)? (STDERR)     at require (packages/modules-runtime.js:109:19)
W20161114-15:18:09.504(1)? (STDERR)     at meteorInstall.node_modules.meteor.example.node_modules.faker.index.js (/Users/nacho/meteor-issue-faker-1.4.2.1/.meteor/local/build/programs/server/packages/example.js:53:13)
W20161114-15:18:09.504(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161114-15:18:09.504(1)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20161114-15:18:09.504(1)? (STDERR)     at Module.Mp.import (/Users/nacho/.meteor/packages/modules/.0.7.7.171jhj5++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161114-15:18:09.505(1)? (STDERR)     at meteorInstall.node_modules.meteor.example.example.js (packages/example/example.js:1:19)
W20161114-15:18:09.505(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161114-15:18:09.505(1)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161114-15:18:09.505(1)? (STDERR)     at /Users/nacho/meteor-issue-faker-1.4.2.1/.meteor/local/build/programs/server/packages/example.js:59:15
W20161114-15:18:09.505(1)? (STDERR)     at /Users/nacho/meteor-issue-faker-1.4.2.1/.meteor/local/build/programs/server/packages/example.js:65:3
```

I also tried to reproduce this on a new meteor app running on the `1.4.2.1` but I did not get it. So the problem is related with the upgrading process between `1.4.1.1` to `1.4.2.1`.

Hope, this helps to solve it.

**Comment by abernix** [comment]
Thanks for putting this reproduction which clearly identifies what you're speaking about, @Gywem!  Much appreciated.  

Unfortunately, I don't see a problem with what's happening here.  Based on the fact that you don't have `faker` defined in the `example` package's `package.js`, I'm assuming that you're trying to use a [peer NPM dependency approach](https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies) to your `example` package.  A peer NPM dependency pattern with Atmosphere packages requires that the NPM that you are relying on rely at the application level – the root of the repository.  However, in your reproduction, I see you have a (Node) `package.json` in the root of your (Meteor) **package**, which is not the intended way of doing this.

You'd need to either:

* Change your `package.js` to `Npm.depends` on the `faker` package, in the same way that you currently use `Npm.depends` for `unicode@0.6.1`.  This would no longer be a "peer NPM" approach as it would specifically build that version of the `faker` NPM into your `example` package; or
* You would need to run `meteor npm install faker --save` in the root of your project which will add it to your 

I've done the latter and it fixes your reproduction.  Please understand that `package.json` files within Meteor *packages* are not interpreted, only those within Meteor *applications*.

If you were doing this before, it's possible that you had a transitive dependence (a package which was installed in your `node_modules` directory but not referenced in your application's `package.json`) on the `faker` package in your project. 

Meteor 1.4.2 introduced a [number of performance enhancements and optimizations](https://github.com/meteor/meteor/blob/devel/History.md#v142) which may have made this necessary when it wouldn't have been before, but these changes are important.  One of the changes is to only bundle NPM dependencies which are listed in your `package.json` instead of copying the entirety of your `node_modules` to the bundle.

**Comment by Davidyuk** [comment]
@abernix, please try this:
```
meteor create test-app                      
cd test-app                                 
meteor npm install --save babel-runtime
meteor npm install --save-dev faker
echo "import faker from 'faker';" >> server/main.js
echo "console.log(faker && faker.lorem.sentence());" >> server/main.js
meteor
```
In my computer this outputs: [gist](https://gist.github.com/Davidyuk/e25064d5dc4f4407f93349a471f440a5).
If after that I run
```
meteor npm install --save faker
meteor
```
all works properly.

**Comment by abernix** [comment]
Thanks for that, @Davidyuk.  I can reproduce that and I think that should work as (I believe) modules installed in `node_modules` (either with `devDependencies` or just transitive) are supposed to work fine in development based on [this comment](https://github.com/meteor/meteor/blob/devel/tools/isobuild/bundler.js#L1995-L1997).

I'll mark for this as confirmed.

**Comment by abernix** [comment]
@Davidyuk Also, just in case it's not clear (I'm basing this comment on the commit you made here: https://github.com/Davidyuk/meteor/commit/c609c3e187fe10f415aec7e13d5686b5e27432be) the reproduction you provided me should NOT work in production as the `devDependencies` would be stripped.  Why are you using the `--production` flag?

**Comment by Davidyuk** [comment]
Oops. I should use `const faker = Meteor.isDevelopment && require('faker');` instead `import faker from faker;` if I want run this in development and production?
With `Meteor.isDevelopment && require('faker')` reproduction works fine using my commit in dev and prod.

**Comment by abernix** [comment]
@Davidyuk Using the reproduction just above with `Meteor.isDevelopment && require('faker')` instead of `import faker from faker` still fails for me, but yes, if you want to deploy same exact code on development and production but only **use** `faker` in development you would need to confirm the environment with `Meteor.isDevelopment`.  Otherwise, `require('faker')` will certainly fail in production if you only have it in your `devDependencies` since they are removed from production bundles.  This is to avoid including (what can be hundreds of megabytes, if not more) dependencies which are not needed.

That being said, I still think there is a bug here based on your reproduction above.  I'm not sure how changing it to ensure the `isDevelopment` flag would have helped a situation that was already happening in development.  Can you check again or explain further?

**Comment by Davidyuk** [comment]
@abernix I mean, my reproduction over [this commit](https://github.com/Davidyuk/meteor/commit/c609c3e187fe10f415aec7e13d5686b5e27432be) with condition and require instead import don't throws error in development and production environments.

**Comment by abernix** [comment]
@Davidyuk Got it.  That makes more sense.  Thanks for the clarification! :smile:

**Comment by dmarkrollins** [comment]
Since I only need faker for tests I found adding faker as a dev dependency then referencing it via the following works: 

`const faker = Meteor.isTest && require('faker');`

**Comment by hwillson** [comment]
As of Meteor 1.4.2, `devDependencies` are stripped in everything except for test mode. This means that if you want to access `faker` in development, you will need to add it to your `package.json`'s `dependencies` section. If access to `devDependencies` based packages was allowed in development mode, the development version of your application could behave differently than your production application (since those `devDependencies` would be stripped in production). This could lead to bugs in production that don't appear in development, when the code that references a development dependency can't execute properly. For example, `import`'s and `require`'s associated with `devDependencies` would have to be handled differently between development and production (e.g. by catching lookup exceptions - yuck). 

Since the current approach of stripping `devDependencies` in development and production is by design, I'll close this issue off. If anyone is interested in seeing this behavior changed, please consider opening a new feature request over in http://github.com/meteor/meteor-feature-requests. Thanks!
