### ISSUE TITLE
[1.6] fails on Mac. Error: [Cannot find module 'internal/util/types']

### ISSUE THREAD

**Issue by naho2081** [meteor/meteor#9310]
After upgrade to 1.6 Meteor project fails to start on Mac with following error

Supporting info:

`node -v` - v.8.9.0
`npm -v` - 5.5.1

```
W20171106-18:43:21.705(2)? (STDERR) (node:47262) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
W20171106-18:43:21.707(2)? (STDERR) /Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171106-18:43:21.707(2)? (STDERR) 						throw(ex);
W20171106-18:43:21.708(2)? (STDERR) 						^
W20171106-18:43:21.708(2)? (STDERR) 
W20171106-18:43:21.708(2)? (STDERR) Error: Cannot find module 'internal/util/types'
W20171106-18:43:21.708(2)? (STDERR)     at Function.Module._resolveFilename (module.js:513:15)
W20171106-18:43:21.709(2)? (STDERR)     at Function.Module._load (module.js:463:25)
W20171106-18:43:21.709(2)? (STDERR)     at Module.require (module.js:556:17)
W20171106-18:43:21.709(2)? (STDERR)     at require (internal/module.js:11:18)
W20171106-18:43:21.709(2)? (STDERR)     at evalmachine.<anonymous>:31:26
W20171106-18:43:21.709(2)? (STDERR)     at Object.<anonymous> (/Users/user/.meteor/packages/velocity_core/.0.10.10.1k6cc05.rbtc++os+web.browser+web.cordova/npm/node_modules/fs-extra/node_modules/graceful-fs/fs.js:11:1)
W20171106-18:43:21.710(2)? (STDERR)     at Module._compile (module.js:612:30)
W20171106-18:43:21.710(2)? (STDERR)     at Object.Module._extensions..js (module.js:623:10)
W20171106-18:43:21.710(2)? (STDERR)     at Module.load (module.js:531:32)
W20171106-18:43:21.710(2)? (STDERR)     at tryModuleLoad (module.js:494:12)
```

What can be the cause of issue and how can it be fixed?

**SOLUTION:**

Remove all packages that depend on `velocity:core`.
In my case it was `sanjo:jasmine` package.

Thanks @abernix for help.

**Comment by benjamn** [comment]
I tried reproducing this by running `meteor add velocity:core` in a new Meteor 1.6 app, but I didn't encounter any problems. Can you provide a [reproduction](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)?

**Comment by nethoncho** [comment]
I have reproduced the issue on a different meteor package
meteor-useraccounts/flow-routing#56

**Comment by hwillson** [comment]
I've been able to reproduce this issue following the steps listed in https://github.com/meteor/meteor/issues/9313#issue-271716825, so marking as confirmed.

**Comment by hwillson** [comment]
Here's a complete dump of stdout showing the error:

```
[local] ~/Documents/meteor/2017-11/meteor-issue-9313 > meteor add useraccounts:flow-routing
 => Errors while adding packages:                                                  
                                              
While loading kadira:flow-router@2.11.0...:
error: Command failed:
/Users/hwillson/.meteor/packages/meteor-tool/.1.6.0.svkjt3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm rebuild
--update-binary
module.js:515
throw err;
^

Error: Cannot find module 'internal/util/types'
at Function.Module._resolveFilename (module.js:513:15)
at Function.Module._load (module.js:463:25)
at Module.require (module.js:556:17)
at require (internal/module.js:11:18)
at evalmachine.<anonymous>:31:26
at Object.<anonymous>
(/private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/fs-extra/node_modules/graceful-fs/fs.js:11:1)
at Module._compile (module.js:612:30)
at Object.Module._extensions..js (module.js:623:10)
at Module.load (module.js:531:32)
at tryModuleLoad (module.js:494:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hwillson/.npm/_logs/2017-11-07T13_53_04_083Z-debug.log
module.js:515
throw err;
^

Error: Cannot find module 'internal/util/types'
at Function.Module._resolveFilename (module.js:513:15)
at Function.Module._load (module.js:463:25)
at Module.require (module.js:556:17)
at require (internal/module.js:11:18)
at evalmachine.<anonymous>:31:26
at Object.<anonymous>
(/private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/fs-extra/node_modules/graceful-fs/fs.js:11:1)
at Module._compile (module.js:612:30)
at Object.Module._extensions..js (module.js:623:10)
at Module.load (module.js:531:32)
at tryModuleLoad (module.js:494:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hwillson/.npm/_logs/2017-11-07T13_53_04_083Z-debug.log
```

And the npm error log:

```
0 info it worked if it ends with ok                                              
1 verbose cli [ '/Users/hwillson/.meteor/packages/meteor-tool/.1.6.0.svkjt3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
1 verbose cli   '/Users/hwillson/.meteor/packages/meteor-tool/.1.6.0.svkjt3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm',
1 verbose cli   'rebuild',                                                           
1 verbose cli   '--update-binary' ]                                                  
2 info using npm@5.4.2                                                               
3 info using node@v8.8.1                                                             
4 info readInstalled object                                                          
5 verbose rebuild path, id [ '/private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/.temp-15oj0yp.x2o8/node_modules/phantomjs',
5 verbose rebuild   'phantomjs@1.9.16' ]                                             
6 silly rebuild set [ '/private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/.temp-15oj0yp.x2o8/node_modules/phantomjs' ]
7 info build /private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/.temp-15oj0yp.x2o8/node_modules/phantomjs8 info lifecycle phantomjs@1.9.16~preinstall: phantomjs@1.9.16                   
9 info linkStuff phantomjs@1.9.16                                                    
10 silly linkStuff phantomjs@1.9.16 has /private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/.temp-15oj0yp.x2o8/node_modules as its parent node_modules 
11 verbose linkBins phantomjs@1.9.16                                             
12 verbose linkBins [ { phantomjs: './bin/phantomjs' },                              
12 verbose linkBins   '/private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/.temp-15oj0yp.x2o8/node_modules/.bin', 
12 verbose linkBins   false ]                                                    
13 verbose linkMans phantomjs@1.9.16                                                 
14 verbose rebuildBundles phantomjs@1.9.16                                           
15 info lifecycle phantomjs@1.9.16~install: phantomjs@1.9.16                         
16 verbose lifecycle phantomjs@1.9.16~install: unsafe-perm in lifecycle true         
17 verbose lifecycle phantomjs@1.9.16~install: PATH: /Users/hwillson/.meteor/packages/meteor-tool/.1.6.0.svkjt3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/bin/node-gyp-bin:/private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/.temp-15oj0yp.x2o8/node_modules/phantomjs/node_modules/.bin:/private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/.temp-15oj0yp.x2o8/node_modules/.bin:/private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/.bin:/Users/hwillson/.meteor/packages/meteor-tool/.1.6.0.svkjt3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin:/Users/hwillson/.meteor/packages/meteor-tool/.1.6.0.svkjt3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/MAMP/Library/bin:/Users/hwillson/bin
18 verbose lifecycle phantomjs@1.9.16~install: CWD: /private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/.temp-15oj0yp.x2o8/node_modules/phantomjs
19 silly lifecycle phantomjs@1.9.16~install: Args: [ '-c', 'node install.js' ]   
20 silly lifecycle phantomjs@1.9.16~install: Returned: code: 1  signal: null      
21 info lifecycle phantomjs@1.9.16~install: Failed to exec install script            
22 verbose stack Error: phantomjs@1.9.16 install: `node install.js`                  
22 verbose stack Exit status 1                                                       
22 verbose stack     at EventEmitter.<anonymous> (/Users/hwillson/.meteor/packages/meteor-tool/.1.6.0.svkjt3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
22 verbose stack     at emitTwo (events.js:125:13)                               
22 verbose stack     at EventEmitter.emit (events.js:213:7)                          
22 verbose stack     at ChildProcess.<anonymous> (/Users/hwillson/.meteor/packages/meteor-tool/.1.6.0.svkjt3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
22 verbose stack     at emitTwo (events.js:125:13)                               
22 verbose stack     at ChildProcess.emit (events.js:213:7)                          
22 verbose stack     at maybeClose (internal/child_process.js:927:16)                
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
23 verbose pkgid phantomjs@1.9.16                                                
24 verbose cwd /private/var/folders/fk/nt93dphj0s3g6xlk_ll74lxm0000gn/T/mt-5a5wiv.33x17/npm/node_modules/.temp-15oj0yp.x2o8
25 verbose Darwin 17.2.0                                                         
26 verbose argv "/Users/hwillson/.meteor/packages/meteor-tool/.1.6.0.svkjt3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/hwillson/.meteor/packages/meteor-tool/.1.6.0.svkjt3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild" "--update-binary"
27 verbose node v8.8.1                                                           
28 verbose npm  v5.4.2                                                               
29 error code ELIFECYCLE                                                             
30 error errno 1                                                                     
31 error phantomjs@1.9.16 install: `node install.js`                                 
31 error Exit status 1                                                               
32 error Failed at the phantomjs@1.9.16 install script. 
32 error This is probably not a problem with npm. There is likely additional logging output above.
33 verbose exit [ 1, true ] 
```

**Comment by hwillson** [comment]
And just to add, this has been reported to npm (both still open):

- https://github.com/npm/npm/issues/19063
- https://github.com/npm/npm/issues/19032

**Comment by abernix** [comment]
Based on the [last comment](https://github.com/npm/npm/issues/19032#issuecomment-344209128) in the second npm issue linked above, it sounds like this is fixed with a more recent version of `graceful-fs`, which is a dependency of `fs-extra`, which is a dependency of `velocity:core`.  The `velocity:core` package is quite old at this point and [depends on](https://github.com/meteor-velocity/velocity/blob/0169f31c25bbefe92a6883c5263ef5e8c931ccf2/package.js#L13) a very old version of `fs-extra` (it specifies 0.18.0 and 4.x is out now).

**Comment by geoidesic** [comment]
How does one install the more recent version of graceful-fs please? I tried updating my package.json to include "graceful-fs": "^4.0.0" but that didn't work.

**Comment by danielsouzapinna** [comment]
Thanks cormip!!!
