### ISSUE TITLE
[1.3.4.1] jQuery, Package.blaze, Package.templating etc all undefined

### ISSUE THREAD

**Issue by apratimankur** [meteor/meteor#7319]
Getting the following client-side errors, after updating app's meteor to 1.3.4.1 -->  

> Uncaught Error: jQuery not found  (in blaze.js)
> Uncaught TypeError: Cannot read property 'Blaze' of undefined   (in spacebars.js)
> Uncaught TypeError: Cannot read property 'Blaze' of undefined   (in templating.js)
> Uncaught TypeError: Cannot read property 'Blaze' of undefined   (in ui.js)
> Uncaught TypeError: Cannot read property 'Template' of undefined   (in aldeed_autoform.js)
> Uncaught TypeError: Cannot read property 'Template' of undefined   (in meteortoys_toykit.js)
> Uncaught TypeError: Cannot read property 'Template' of undefined   (in msavin_mongol.js)
> Uncaught TypeError: Cannot read property 'Template' of undefined   (in iron_layout.js)
> Uncaught TypeError: $ is not a function   (in iron_location.js)
> ...
> ...
> (And similar errors in other packages.) 
> 
> Uncaught ReferenceError: meteorInstall is not defined   (in .meteor/local/build/programs/web.browser/app/app.js )

<img width="1674" alt="screen shot 2016-06-28 at 06 00 39" src="https://cloud.githubusercontent.com/assets/3172946/16414837/adf44f78-3d57-11e6-9646-bd292a0c3ce6.png">

The server is running fine (additionally verified by logging, see below) -->
<img width="495" alt="screen shot 2016-06-28 at 06 04 28" src="https://cloud.githubusercontent.com/assets/3172946/16414864/dc013c96-3d57-11e6-9655-6a43f8fb299e.png">

The packages are downloaded properly in the browser -->
<img width="1008" alt="screen shot 2016-06-28 at 06 14 03" src="https://cloud.githubusercontent.com/assets/3172946/16414901/10280f90-3d58-11e6-920e-acdc5b7fd69a.png">
<img width="1015" alt="screen shot 2016-06-28 at 06 23 15" src="https://cloud.githubusercontent.com/assets/3172946/16414910/2029c1b8-3d58-11e6-9739-ead086efa6d0.png">

NOTE : The project structure is -->

- both/
    - collections/
    - lib/
    - routes.js

- client/
    - lib/
    - startup/
    - styles/
    - templates/

- packages/
    - (local_packages)

- public/
    - (static_files)

- resources/
     - icons/
     - splash/

- server/ 
    - api/
    - methods/
    - seeds/
    - publications/
    - permissions.js
    - ..

- mobile-config.js
- mup.json
- settings.json
..

What could be causing these errors ?

**Comment by abernix** [comment]
There's really not much to work off here.  Is it possible to reproduce this problem in a new Meteor project?  Or can you create a simplified version of your current project that you can share on GitHub and someone could easily open and reproduce?

Without this, there isn't much anyone can do.  Please read more about [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

**Comment by apratimankur** [comment]
I deleted the global meteor installation and reinstalled it - 
and its working now.
Apparently meteor update, didn't update the packages downloaded in the global repository (~/.meteor/packages)

**Comment by willemx** [comment]
I have the exact same problem (updated from 1.3.2.4 to 1.3.4.1) and I would like to try your advice to "delete the global meteor installation and reinstall", but I don't know how to do this.
Can you explain how to do this?

**Comment by abernix** [comment]
@willemx Are you on Windows, Mac or Linux?

**Comment by willemx** [comment]
I am on Mac.
BTW, I also have a number of older meteor projects that are still on 1.2 and I don't want to update those projects. (too risky... ;)

**Comment by abernix** [comment]
On Mac, you can just re-run the install script and it will wipe everything clean.

    curl https://install.meteor.com/ | sh

When you run your 1.2 projects again it will need to download and extract the 1.2 bootstrap tarball but the projects should be fine after that.  If you want to be **uber**-safe, you can backup your `$HOME/.meteor` first:

    mv ~/.meteor ~/.meteor-backup

You can then put it back afterward if there are problems and you'll be working with the same exact Meteor as you were before.

Please do report back if this fixes it for you!

**Comment by willemx** [comment]
Yes! the errors are gone now. (also the old projects still work).
Many thanks, you saved my weekend...

**Comment by tmignot** [comment]
I had the same errors, but reinstalling did not help, believe me if you can but closing re-launching chrome fixed it (Yes I'm confused, No I don't understand)

**Comment by sourav2029** [comment]
@abernix  I had this exact same issue and I wanted to reinstall meteor as per the comment from @apratimankur.
I tried using this command : curl "https://install.meteor.com/?release=1.6.1" | sh
But it failed with error: 
Removing your existing Meteor installation.
rm: /Users/sourav.prem/.meteor/packages: Directory not empty
rm: /Users/sourav.prem/.meteor: Directory not empty
Installation failed.

Any help ?

**Comment by sourav2029** [comment]
Reinstallation is also not working for me :( . Can someone provide a solution ? I am in a grave situation

**Comment by abernix** [comment]
I'm assuming that there's something in your `/Users/sourav.prem/.meteor` directory that the installation script can't remove when it's trying to re-install (for some reason).  Can you try completely removing `/Users/sourav.prem/.meteor` (i.e. `rm -rf /Users/sourav.prem/.meteor/`) before installing again?

**Comment by abernix** [comment]
@sourav2029 I'm assuming that there's something in your `/Users/sourav.prem/.meteor` directory that the installation script can't remove when it's trying to re-install (for some reason).  Can you try completely removing `/Users/sourav.prem/.meteor` (i.e. `rm -rf /Users/sourav.prem/.meteor/`) before installing again?
