### ISSUE TITLE
[1.7.0.1] Meteor autorun is not a function with gwendall_auth-client & Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by Jogibaer1963** [meteor/meteor#9938]
I get this error message after upgrade to 1.7.0.1 with every project.
First part shows up with the login -> gwendall_auth-client, 
the second part shows up for each call to the mongodb... 
Sorry for maybe bad english  :/
 Something I missed ?

u2622_persistent-session.js?hash=57db38c11edeebc31dce68f5b5be8581c20a2286:265 Uncaught TypeError: Cannot read property 'apply' of undefined
    at ReactiveDict.PersistentSession.old_set (u2622_persistent-session.js?hash=57db38c11edeebc31dce68f5b5be8581c20a2286:265)
    at ReactiveDict._psSet [as set] (u2622_persistent-session.js?hash=57db38c11edeebc31dce68f5b5be8581c20a2286:285)
    at overView.js (app.js?hash=1f9520ede93764e7e70ab3d24dd9624067c095fa:4542)
    at fileEvaluate (modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349)
    at require (modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248)
    at app.js?hash=1f9520ede93764e7e70ab3d24dd9624067c095fa:7127
PersistentSession.old_set @ u2622_persistent-session.js?hash=57db38c11edeebc31dce68f5b5be8581c20a2286:265
_psSet @ u2622_persistent-session.js?hash=57db38c11edeebc31dce68f5b5be8581c20a2286:285
overView.js @ app.js?hash=1f9520ede93764e7e70ab3d24dd9624067c095fa:4542
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
(anonymous) @ app.js?hash=1f9520ede93764e7e70ab3d24dd9624067c095fa:7127

  Exception in template helper: TypeError: Cannot read property 'apply' of undefined
    at ReactiveDict.PersistentSession.old_get (http://localhost:3000/packages/u2622_persistent-session.js?hash=57db38c11edeebc31dce68f5b5be8581c20a2286:241:25)
    at ReactiveDict._psGet [as get] (http://localhost:3000/packages/u2622_persistent-session.js?hash=57db38c11edeebc31dce68f5b5be8581c20a2286:244:18)
    at Object.get (http://localhost:3000/packages/accounts-ui-unstyled.js?hash=215c2e819839e04fe71a66b39df2d61c6a6bc8d3:919:20)
    at Object.inResetPasswordFlow (http://localhost:3000/packages/accounts-ui-unstyled.js?hash=215c2e819839e04fe71a66b39df2d61c6a6bc8d3:1879:32)
    at http://localhost:3000/packages/blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3051:16
    at http://localhost:3000/packages/blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:1715:16
    at http://localhost:3000/packages/blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3103:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3102:27
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?hash=547cf8e466d1d52603d19bd5f48fb5df184fd237:172:18)

**Comment by evolross** [comment]
This is related to #9918. u2622:persistent-session is broken in Meteor 1.7. I also use this package extensively so will be interested in any updates.

**Comment by Jogibaer1963** [comment]
meteor remove u2622:persistent-session
and problem was solved.
Thank you
