### ISSUE TITLE
cordova cannot find module

### ISSUE THREAD

**Issue by sakulstra** [meteor/meteor#10026]
When building our app for cordova it seems like related npm dependencies aren't resolved properly any more on meteor 1.7. When i try to build for android on 1.6.1.3 everything works fine - after the upgrade to 1.7.1-beta.3 I get the following error:
 ```
=> Errors executing Cordova commands:                                              

   While preparing Cordova project for platform Android:                           
   cordova-custom-config: Error loading dependencies for applyCustomConfig.js - ensure the plugin has been installed via cordova-fetch or run 'npm install cordova-custom-config': Cannot find module 'plist'
```

`cordova-custom-config` is already installed and the same version as on 1.6.1.3

--------
I'll try to create a reproduction in the evening.

**Comment by sakulstra** [comment]
hmmm i cannot manage to create a reproduction, so i guess it's not related to meteor, but sth else

**Comment by sakulstra** [comment]
i managed to reproduce it in some different form:
https://github.com/sakulstra/meteor-bugs/commits/cordova-plist-issue
1. checkout c1b8e9a9665342af123defd76910026e4aef9849
2. `rm node_modules -rf && meteor npm i`
3. you should see that plist is not listed in node_modules any more (which is the problem we are facing)
4. when you run `meteor npm i` once again it will be added again

in our codebase 4. isn't behaving like that, but i'm not sure what the big difference is here.
