### ISSUE TITLE
Meteor 1.5: Importing module error

### ISSUE THREAD

**Issue by FranciscoHanna** [meteor/meteor#8862]
Hi!
I'm using `useraccounts:core` in a project, and I was setting the template and the route for the `signIn` form with the following code:

```javascript
// in useraccounts-configurations.js
AccountsTemplates.configureRoute('signIn', {
	name: '/long',
	path: '/login',
	template: 'Login_page',
	layoutTemplate: 'Login_page',
	redirect: '/'
});
```
I was not importing the module `ui/pages/login-page.js` and it was working on Meteor 1.4. 
Since update, I get the following error:
`BlazeLayout warning: unknown template "Login_page"`

If I add the following line in `useraccounts-configuration.js`
```javascript
import '../../ui/pages/login-page.js'
```
I get the following error:
```
Error: Cannot find module './login-page.html'
    at makeMissingError (packages/modules-runtime.js:221:12)
    at require (packages/modules-runtime.js:231:19)
    at meteorInstall.imports.ui.pages.login-page.js (imports/ui/pages/login-page.js:1:14)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at meteorInstall.imports.startup.both.useraccounts-configuration.js (imports/startup/both/useraccounts-configuration.js:1:230)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at meteorInstall.imports.startup.both.index.js (imports/startup/both/index.js:1:14)
    at fileEvaluate (packages/modules-runtime.js:333:9)
```

Wich is nonsense since I have the `login-page.html` in the same folder as `login-page.js`, and in the last one I have the following line:
```javascript
import './login-page.html'
```
```html
<!-- login-page.html -->
<template name="Login_page">
	{{> atForm }}
</template>
```

I've already tried removing and adding the blaze-layout package and deleting the blaze package cache.
I've also updated all the packages that are in the project.

What should I do?

**Comment by hwillson** [comment]
@FranciscoHanna - please provide a small, runnable reproduction demonstrating this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). This shouldn't be a Meteor 1.5 bug (if it was we would have heard about it by now), but if you can provide a reproduction, I'll take a look.

**Comment by FranciscoHanna** [comment]
@hwillson  - Hi! Thank you for your reply!

Here's the link to the repository for error reproduction. [https://github.com/FranciscoHanna/meteor-import-module-bug](url)
Clone it. Run `npm install`. Run `meteor run` and go to `localhost:3000`. The message error will be visible.

I created the reproduction with `meteor create --bare` as the starting project.

The list of packages installed is:
```
accounts-password          1.3.7  
accounts-ui                1.1.9  
blaze-html-templates       1.1.2  
ecmascript                 0.8.1  
es5-shim                   4.6.15 
kadira:blaze-layout        2.3.0  
kadira:flow-router         2.12.1 
meteor-base                1.1.0  
mobile-experience          1.0.4  
mongo                      1.1.18 
reactive-var               1.0.11 
standard-minifier-css      1.3.4  
standard-minifier-js       2.1.0  
tracker                    1.1.3  
useraccounts:core          1.14.2  
useraccounts:flow-routing  1.14.2  
```

Please let me know if you need additional information.

**Comment by hwillson** [comment]
There are 2 issues with your app:

1. In your `server/main.js`, you're importing `/imports/startup/both`, which means you're trying to import your `useraccounts-configuration.js` file on the server. This won't work - `AccountsTemplates` is intended to be loaded client side only. To fix this, just remove the `import '/imports/startup/both';` line from your `server/main.js` file. This will let your reproduction start up properly.

2. After it starts, you'll get a missing `atForm` reference. This is because your reproduction doesn't include a `useraccounts` login template package. For example, if you `meteor add useraccounts:unstyled`, the `atForm` error will go away, and your login page will show properly.

Since there aren't any issues with Meteor here, I'll close this off. Thanks!

**Comment by FranciscoHanna** [comment]
Thanks, now it's working.
My confussion came from the Guide for `useraccounts`, refering to the `AccountsTemplates.configureRoute(route_code, options);` and `AccountsTemplates.configure(options);` methods. It says:

_"The only other requirement is to make exactly the same calls on both the server and the client. The best thing is to put everything inside a file shared between both. I suggest you use something like lib/config/at_config.js"_ 
 
See it here:
[https://github.com/meteor-useraccounts/core/blob/master/Guide.md#configuration-api](url)

Must be a `useraccounts` bug tough, but it was working with the file shared between client and server in  Meteor 1.4.3.

**Comment by hwillson** [comment]
Oh, right - sorry @FranciscoHanna, I haven't used `useraccounts` in a while. Well, then you can ignore what I said and instead just move your login route template reference out of your `imports/startup/both/useraccounts-configuration.js` file, and into a client side routing file. So continue to call `import '/imports/startup/both';` in your `server/main.js`, but make the following additional changes:

`imports/startup/both/useraccounts-configuration.js`:

```js
import { FlowRouter } from 'meteor/kadira:flow-router';
import { AccountsTemplates } from 'meteor/useraccounts:core';

AccountsTemplates.configure({
  forbidClientAccountCreation: false,
  onLogoutHook() {
    FlowRouter.go('/login')
  },
});

// Here I've removed the need to reference the Template in this file.
AccountsTemplates.configureRoute('signIn', {
  name: '/login',
  path: '/login',
});
```

`imports/startup/client/routes/home.js`:

```js
import { FlowRouter } from 'meteor/kadira:flow-router';
import { BlazeLayout } from 'meteor/kadira:blaze-layout';

/* Importamos estos archivos .js para usar los templates necesarios */
import '../../../ui/layouts/app-body.js';
import '../../../ui/pages/login-page.js'

/* Definimos las rutas de la app y las acciones que se llevan a cabo cuando se golpean las URL */
FlowRouter.route('/', {
  name : 'App.home',
  action() {
    BlazeLayout.render('App_body', {body_main: ''})
  }
});

// Just an example - you might want this route in another file.
FlowRouter.route('/login', {
  name: 'Login',
  action() {
    BlazeLayout.render('App_body', { body_main: 'Login_page' });
  },
});
```

With the above approach you're keeping the need to reference your templates on the client side only, instead of trying to reference them on the server side, when you import `imports/startup/both/useraccounts-configuration.js`.

**Comment by FranciscoHanna** [comment]
Thanks @hwillson , that worked perfectly. 
Do you think I should I open an issue in the [useraccounts:core github page](https://github.com/meteor-useraccounts/core/) regarding this issue?
