### ISSUE TITLE
1.3.2.4 hot pushes not working with React code

### ISSUE THREAD

**Issue by ywongweb** [meteor/meteor#6991]
Hello all,

I am having problems with getting hotpush to work on Meteor 1.3.2.4 when using React / react-template-helper. The problem only seem to happen when _hot pushing from remote server to device_.

I have added react and react-template-helper to the project using
```
npm install --save react react-dom
meteor add react-template-helper
```

When I build the project it runs on device and I can see the react components. However when the _same working code_ is hot pushed from the server, the app reloads and get stuck on white screen. In the inspector I can see these errors:
```
Error: Cannot find module 'react/package.json'(…)
7c52702df8cab1d59be81025272d43c498547079.js?meteor_js_resource=true:295 Error: Cannot find module 'react-dom/package.json'(…)
7c52702df8cab1d59be81025272d43c498547079.js?meteor_js_resource=true:295 WARNING: npm peer requirements (for react-template-helper) not installed:
 - react@15.x not installed.
 - react-dom@15.x not installed.

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

7c52702df8cab1d59be81025272d43c498547079.js?meteor_js_resource=true:11 Uncaught Error: Cannot find module 'react'
```

Once I remove the react code, hot push works again.

Anyone encounter this problem before?

**Comment by ywongweb** [comment]
The issue seem to be a problem with our Docker build script, we added `npm install` and things seem to be working again.
