### ISSUE TITLE
[1.3-rc.2] Cannot find module 'fibers' when running demo project simple-todos on Ubuntu

### ISSUE THREAD

**Issue by danlg** [meteor/meteor#6525]
I had issue to upgrade my complex project to 1.3-rc.2. 
Before opening an issue to meteor, I have managed to reproduce it deploying a simple-todos meteor project (git clone https://github.com/meteor/simple-todos/tree/master/.meteor)

I checked I could deploy with meteor 1.2.1 then I run 
```meteor update --release 1.3-rc.2``` (as I have done on my project)
It doesn't work on 1.3-rc.2 on Ubuntu 14.04 LTS 3.13.0-57-generic #95-Ubuntu SMP. 

* [x] Node 0.10.41 is setup , which I understand is the minimum version for 1.3 (BTW this needs to be documented).

I am using mup to deploy and got this error :
```
[my ubuntu ip] x Invoking deployment process: FAILED
	-----------------------------------STDERR-----------------------------------
	, run them from an Administrator prompt.)
	npm WARN deprecated 
	npm WARN deprecated If you're running the version of npm bundled with
	npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
	npm WARN deprecated will be bundled with a version of npm@2, which has some small
	npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
	npm WARN deprecated semver behavior.
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	stop: Unknown instance: 
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8003: Connection refused
	Latest deployment failed! Reverted back to the previous version.
	-----------------------------------STDOUT-----------------------------------
	fibers.node`
	ansi-regex@0.2.1 node_modules/ansi-regex
	ansi-styles@1.1.0 node_modules/ansi-styles
	chalk@0.5.1 node_modules/chalk
	escape-string-regexp@1.0.5 node_modules/escape-string-regexp
	has-ansi@0.1.0 node_modules/has-ansi
	supports-color@0.2.0 node_modules/supports-color
	strip-ansi@0.3.0 node_modules/strip-ansi
	eachline@2.3.3 node_modules/eachline
	type-of@2.0.1 node_modules/type-of
	amdefine@1.0.0 node_modules/amdefine
	asap@2.0.3 node_modules/asap
	underscore@1.5.2 node_modules/underscore
	meteor-promise@0.5.1 node_modules/meteor-promise
	promise@7.0.4 node_modules/promise
	source-map-support@0.3.2 node_modules/source-map-support
	semver@4.1.0 node_modules/semver
	source-map@0.1.32 node_modules/source-map
	fibers@1.0.8 node_modules/fibers
	Waiting for MongoDB to initialize. (5 minutes)
	connected
	stodos-1-3 start/running, process 12244
	Waiting for 15 seconds while app is booting up
	Checking is app booted or not?
	stodos-1-3 stop/waiting
```

To force the actual deployment of the app (and override the rollback by mup), I have manually expanded the archive and started manually the app on the server. Here is the error I get in the log file of the app:
```
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/stodos-1-3/app/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
error: Script restart attempt #750 
module.js:340
    throw err;
```

@tmeasday I understand you work on this upgrade so this is something to take into account so that the upgrade is smooth. 1.3-rc.2 is not yet production ready. Thanks for your advice or fix.

**Comment by teknologist** [comment]
Will the new RC which will hopefully fix this is out, you may use this 

[Creating a Custom Production Docker Image for Meteor 1.3](http://markshust.com/2016/02/01/creating-custom-production-docker-image-meteor-13)

It made meteor app deployable again. Basically it rebuilds all node_modules and copies them all over.

**Comment by benjamn** [comment]
My guess: Recent 1.3 beta releases use a new version of `npm`, 2.14.22, which uses a newer version of the v8 API by default, which won't work with Meteor's version of `node`, 0.10.43. When `npm install` is used to install `fibers`, it's important that the version of `node` in the `$PATH` is the same as Meteor's, or at least a version of `node` that uses a compatible version of `v8` (3.14).

What's the `mup` command you're using to deploy?

**Comment by danlg** [comment]
@benjamn simply ```mup deploy ```. But I don't think this is a mup issue as I can manually reproduce the issue by launching the app on the Ubuntu server. I'll try to upgrade to node 0.10.43 (my build Mac machine client is node 0.10.42 with nvm). 

I don't get your point on meteor as IMHO meteor is not required on the server: the app is just a simple node app. Or is your point on meteor version on the client box building the archive (not the server)? Where do we need node 0.10.43 & npm 2.14.22 on the build client machine with git sources, on the deployed server or both ? Tx for your clarification.

**Comment by danlg** [comment]
same issue (module fibers not found) with node 0.10.43 and npm 3.8.2 upgraded on Ubuntu server
```
root@dolgdev2:/var/log/upstart# which npm 
/root/.nvm/v0.10.43/bin/npm
root@dolgdev2:/var/log/upstart# npm -v
3.8.2
root@dolgdev2:/var/log/upstart# which node
/root/.nvm/v0.10.43/bin/node
root@dolgdev2:/var/log/upstart# node -v
v0.10.43
```

**Comment by Deilv** [comment]
Did you run npm install inside the project before trying to run it?

**Comment by danlg** [comment]
@Deilv no, but ```npm install``` doesn't change anything. Just tried now without any success:
```
root@dolgdev2:/opt/stodos-1-3/app# ls -l
total 24
-r--r--r-- 1 root root  543 Mar 19 00:22 README
-r--r--r-- 1 root root  485 Mar 19 00:22 main.js
drwxr-xr-x 2 root root 4096 Mar 19 01:36 node_modules
drwxr-xr-x 4 root root 4096 Mar 19 00:22 programs
drwxr-xr-x 2 root root 4096 Mar 19 00:22 server
-r--r--r-- 1 root root  361 Mar 19 00:22 star.json
root@dolgdev2:/opt/stodos-1-3/app# npm install
npm WARN enoent ENOENT, open '/opt/stodos-1-3/app/package.json'
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.
root@dolgdev2:/opt/stodos-1-3/app# uname -a
Linux dolgdev2 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by Deilv** [comment]
Sorry, try **npm install** inside ./app/programs/server/

**Comment by tmeasday** [comment]
@danlg have you followed this exact process (manually installing on a ubuntu server **without** using mup) with 1.2? You'll get that `fibers` issue if you don't `npm install` properly on the server with any version of Meteor. I don't believe the way that works has changed (and I think @Deilv is onto something here---you may just be doing it in the wrong spot, the `ENOENT` is a hint here).

I suspect the original issue is a problem with mup + 1.3 after all--it sounds from the log like the app started properly but mup didn't detect it? Although I have no real idea how mup works.

**Comment by tmeasday** [comment]
PS the bundle has a README in it that explains how to run it, have you looked at that (it may need to be updated to include the correct node version @benjamn)

**Comment by danlg** [comment]
@tmeasday I had not run ```npm install``` in the ./app/programs/server/ (but why are we supposed to do this??? a tar ball is supposed to be used as it you 're not supposed to compile on the server...). anyway, I have run:

1. ```meteor build``` on my mac (instead of mup to remove this dependency) 
2.  ```scp``` the tarball to the Ubuntu server 
3. ```tar zxf ```extracted it
4.  run ```npm install``` in the server directory , which install fibers and the npm_modules inside
5. start it ```service stodos-1-3 start```

It is now a different error. but I am positive this just a hack not going in the right direction. The compilation of fibers and npm install on the ** server** looks very weird. How are we supposed to deploy a tar ball with Meteor 1.3 without mup on Digital Ocean? I would expect just to deploy my tarball, extract it and that's it.

```  
Error: /opt/stodos-1-3/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node:
 invalid ELF header at Module.load (module.js:356:32)
```
  I'm very puzzled by the deployment of Meteor on server. Thanks

**Comment by tmeasday** [comment]
Hi @danlg you need to `npm install` on the server to build the correct version of fibers for your architecture. It's always been the way the Meteor node bundle has been deployed (http://guide.meteor.com/deployment.html#custom-deployment).

The bcrypt thing is interesting though, I'll investigate that further..

**Comment by Deilv** [comment]
Running **npm install** is a clever way to make sure your app is using modules suited to your server platform. If **meteor build** did this for you before deployment then the resulting bundle would only be compatible with your working platform (Mac) and probably not your hosting platform (Linux). Therefore it's not a hack, it's how npm modules are meant to be installed.

As for the new error, try running **npm install bcrypt** inside **./app/programs/server/** and the run **npm install** as before. Please let us know what happens.

**Comment by jorisroling** [comment]
I see the same as @danlg 

I removed the node_modules dir (in **/opt/<APP>/app/programs/server**) entirely with ```rm -rf node_modules``` then ```npm install```
All looks good, except the meteor app won't start: saying

```Error: /opt/pilot/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Module.load (module.js:356:32)```

**Comment by Deilv** [comment]
@jorisroling are you also using mup to deploy? This error has been reported before and I don't believe it's related to meteor, but rather a problem with the bcrypt binary bundled by MuP into app/programs/server/npm/npm-bcrypt/ when deploying from osx to linux.

A tested solution which was published over a year ago is to:
cd app/programs/server/
rm -rf node_modules
npm install bcrypt
cp -r node_modules/bcrypt npm/node_modules/bcrypt
npm install

Please let us know if this solves the issue for you, as I cannot replicate your issue.

**Comment by tmeasday** [comment]
Are you providing an `--architecture` when building?

Try

```
meteor build --architecture os.linux.x86_64 /path/to/build
```

**Comment by tmeasday** [comment]
I'm closing this as by the sounds of it a combination of `(cd programs/server; npm install)` and `build --architecture` will solve all issues listed here.

I'll reopen if this is not the case.

**Comment by benlavalley** [comment]
@danlg mup does the npm rebuilds on your remote server for you in a script. My guess is something changed with bcrypt in 1.3 and mup is failing to detect that it needs to be re-built, or isn't rebuilding it and placing the results in the proper folder. 

This is the script that does it... https://github.com/arunoda/meteor-up/blob/master/templates/linux/deploy.sh

I'd start troubleshooting this now myself but I spent a good chunk of the day just sorting it out and I want to code on my app. I found/fixed a similar bcrypt issue for mup back in 2014. Going to simply use mupx + 1.3 RC2 for now -- rc3 has a node 0.10.43 version check and the mupx docker image isn't on 0.10.43 yet. Not totally sold on the Docker thing yet myself.

**Comment by tmeasday** [comment]
@benlavalley, heads up that rc4 no longer has the bumped node dependency. 

Also I'm guessing the issue is that mup isn't building properly in the first place (ie not using that `--architecture` flag) rather than needing to do all that extra work on the server after unbundling

**Comment by danlg** [comment]
@tmeasday indeed I had not specified the architecture. Tried that with meteor 1.3-rc.4 and got into the issue ```Error when building for os.linux.x86_64``` #6537. I want to avoid at all cost doing a partial build on 1 machine and npm install on another one. This is really not clean (although this is not new in 1.3 but 
I realize it only now). IMHO the case is still open but could be renamed as 

> [meteor 1.3-rc.4] Cannot deploy on os.linux.x86_64 

@benlavalley thanks for that

**Comment by tmeasday** [comment]
@danlg, OK, this makes sense. I think (as you have done) we should move discussion of your issue to that ticket, as the problem you are now running into matches that.

**Comment by benlavalley** [comment]
I wasn't able to code on my app since this was bugging me and I knew I could fix it with a little more elbow grease.

@danlg - here you go.... within this file:

https://github.com/arunoda/meteor-up/blob/master/lib/build.js

Modify line 22 from this :
`    "--server", "http://localhost:3000"`

to this:

`    "--server", "http://localhost:3000","--architecture", "os.linux.x86_64"`

Obviously mup will now be statically compiling for Linux, so if for some reason you want to use it to push to OS X, you'll want to remove this. 

mup is now deploying fine for me with only this change.

I'm not crazy about the extra resource usage of Docker for just running a node app (Meteor) especially since I'm deploying it to my own dedicated Amazon EC2 VPC environment (front-end nginx load balancer+SSL/mid-tier nginx+meteor servers/beefy mongodb backend).  I've been using mup with it's usage of upstart+forever for a while now without any major issues.

**Comment by danlg** [comment]
@benlavalley thanks a lot for this tip. Will try it!

**Comment by afrantz** [comment]
"Sorry, try npm install inside ./app/programs/server/"
=> Thnak you !

It works but it's not in the Meteor's doc... Whyyyyyy ?

**Comment by benjamn** [comment]
It's a bit buried, because it's something that Galaxy handles for you, but here's where we recommend `npm install` in the deployed bundle: https://guide.meteor.com/deployment.html#custom-deployment
