### ISSUE TITLE
Stripe and aws-sdk NPM packages not working with Meteor 1.3 beta 11

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6285]
I'm running Meteor 1.3 beta 11, and some NPM packages are not working at all, even just upon simply importing them. Two in particular: `aws-sdk`, and `stripe`.

When doing this:

    import Stripe from 'stripe';

this yields the following error in the browser console:

![title_here](https://cloud.githubusercontent.com/assets/12532733/13207118/902f9c42-d8bf-11e5-8325-81c116ebf074.png)

And when doing this:

    import AWS from 'aws-sdk';

the following occurs:

```
Error: Cannot find module '/node_modules/aws-sdk/apis/metadata.json'
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:77:1)
    at buildServiceMap (node_modules/aws-sdk/lib/api_loader.js:13:1)
    at Object.getServices [as services] (node_modules/aws-sdk/lib/api_loader.js:42:1)
    at meteorInstall.node_modules.aws-sdk.lib.services.js (node_modules/aws-sdk/lib/services.js:7:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at meteorInstall.node_modules.aws-sdk.lib.aws.js (node_modules/aws-sdk/lib/aws.js:14:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at meteorInstall.lib.collections.some-collection.js (/private/tmp/npmtest/.meteor/local/build/programs/server/app/app.js:60:15)
Exited with code: 8
Your application is crashing. Waiting for file change.
```

These actually failed with beta 8 as well, but I upgraded to beta 11 to make sure this wasn't a bug that had been fixed since then.

**Comment by zol** [comment]
@benjamn I'm afraid these will be popular packages.

**Comment by benjamn** [comment]
Do either of these packages need to work on the client?

After manually adding some stub packages (like `http` and `url`), I was intrigued to see that the `aws-sdk` bug only happens on the first test run.

**Comment by ffxsam** [comment]
Stripe might, since it creates a hidden iframe.

**Comment by marbemac** [comment]
The aws package, at least, seems to use the "browser" package.json property. I think I remember some other issues where the package.json browser property was mentioned, but I can't seem to find them.

https://github.com/aws/aws-sdk-js/blob/master/package.json#L36

**Comment by benjamn** [comment]
Both of these packages will work on the client in the next beta release (`beta.12`, slated to be released tomorrow)!

The `stripe` package will work just fine on the server, too, but `aws-sdk` will unfortunately need to be installed the old way, by a Meteor package via `Npm.depends`, and imported using `Npm.require`. In other words, you should probably continue using a Meteor wrapper package like [`peerlibrary:aws-sdk`](https://atmospherejs.com/peerlibrary/aws-sdk), if you need to use `aws-sdk` on the server.

Related issue: https://github.com/meteor/meteor/issues/6173#issuecomment-189481637

**Comment by marbemac** [comment]
Great news, thanks @benjamn! Looking forward to beta.12.

**Comment by ciwolsey** [comment]
This isn't even working on server for me in beta 12. Ever since switching to 1.3 it seems like more npms don't work for me than do.
