### ISSUE TITLE
[1.4][ubuntu 16.04] Error could not locate bindings file (bcrypt)

### ISSUE THREAD

**Issue by badmark** [meteor/meteor#7513]
Upgraded Meteor project to 1.4 (Ubuntu 16.04 x64), after updating all dependencies I receive the following error:

```
W20160727-23:03:44.541(-4)? (STDERR) /home/mark/.meteor/packages/meteor-tool/.1.4.0.hylsrj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160727-23:03:44.584(-4)? (STDERR)            				throw(ex);
W20160727-23:03:44.585(-4)? (STDERR)            				^
W20160727-23:03:44.585(-4)? (STDERR)          
W20160727-23:03:44.586(-4)? (STDERR) Error: Could not locate the bindings file. Tried:
W20160727-23:03:44.586(-4)? (STDERR)  → /home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/build/bcrypt_lib.node
W20160727-23:03:44.586(-4)? (STDERR)  → /home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/build/Debug/bcrypt_lib.node
W20160727-23:03:44.587(-4)? (STDERR)  → /home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/build/Release/bcrypt_lib.node
W20160727-23:03:44.587(-4)? (STDERR)  → /home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/out/Debug/bcrypt_lib.node
W20160727-23:03:44.587(-4)? (STDERR)  → /home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/Debug/bcrypt_lib.node
W20160727-23:03:44.588(-4)? (STDERR)  → /home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/out/Release/bcrypt_lib.node
W20160727-23:03:44.588(-4)? (STDERR)  → /home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/Release/bcrypt_lib.node
W20160727-23:03:44.588(-4)? (STDERR)  → /home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/build/default/bcrypt_lib.node
W20160727-23:03:44.588(-4)? (STDERR)  → /home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/compiled/4.4.7/linux/x64/bcrypt_lib.node
W20160727-23:03:44.589(-4)? (STDERR)     at bindings (/home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bindings/bindings.js:88:9)
W20160727-23:03:44.589(-4)? (STDERR)     at Object.<anonymous> (/home/mark/.meteor/packages/npm-bcrypt/.0.8.7.1jx18a8++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/bcrypt.js:3:35)
W20160727-23:03:44.589(-4)? (STDERR)     at Module._compile (module.js:409:26)
W20160727-23:03:44.589(-4)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20160727-23:03:44.589(-4)? (STDERR)     at Module.load (module.js:343:32)
W20160727-23:03:44.590(-4)? (STDERR)     at Module.Mp.load (/home/mark/.meteor/packages/babel-compiler/.6.9.0.jissfh++os+web.browser+web.cordova/npm/node_modules/reify/node/runtime.js:16:23)
W20160727-23:03:44.590(-4)? (STDERR)     at Function.Module._load (module.js:300:12)
W20160727-23:03:44.590(-4)? (STDERR)     at Module.require (module.js:353:17)
W20160727-23:03:44.590(-4)? (STDERR)     at require (internal/module.js:12:17)
W20160727-23:03:44.590(-4)? (STDERR)     at Object.Npm.require (/store/projects/Apollo/.meteor/local/build/programs/server/boot.js:190:18)
```

Also getting this error:

```
W20160728-11:01:09.015(-4)? (STDERR) /home/mark/.meteor/packages/meteor-tool/.1.4.0.hylsrj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160728-11:01:09.056(-4)? (STDERR) 						throw(ex);
W20160728-11:01:09.057(-4)? (STDERR) 						^
W20160728-11:01:09.057(-4)? (STDERR) 
W20160728-11:01:09.057(-4)? (STDERR) TypeError: Meteor.subscribe is not a function
W20160728-11:01:09.057(-4)? (STDERR)     at meteorInstall.addCars.js (addCars.js:160:8)
W20160728-11:01:09.057(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160728-11:01:09.058(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160728-11:01:09.058(-4)? (STDERR)     at addCars.js:2075:1
W20160728-11:01:09.058(-4)? (STDERR)     at /store/projects/Apollo/.meteor/local/build/programs/server/boot.js:297:10
W20160728-11:01:09.058(-4)? (STDERR)     at Array.forEach (native)
W20160728-11:01:09.059(-4)? (STDERR)     at Function._.each._.forEach (/home/mark/.meteor/packages/meteor-tool/.1.4.0.hylsrj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160728-11:01:09.059(-4)? (STDERR)     at /store/projects/Apollo/.meteor/local/build/programs/server/boot.js:133:5
```

When starting from scratch. How is Meteor.subscribe not a function?

I've tried completely reinstalling node/npm/meteor, I've reset, I'vestarted the project from scratch. When starting from scratch on 1.4 the error begins after adding **accounts-base** package. **meteor npm rebuild** does not correct the issue although it rebuilds without error.

**Comment by dnish** [comment]
Same? https://github.com/meteor/meteor/issues/7512

**Comment by badmark** [comment]
The issue is in development and I've tried those steps with no success.

**Comment by abernix** [comment]
@badmark First, `Meteor.subscribe` does not exist on the server – only the client ([per the docs](http://docs.meteor.com/api/pubsub.html#Meteor-subscribe).  Perhaps you meant, `Meteor.publish`?

As to the other error, I don't know if pre-compiled bindings exist for that OS, but you should make sure you have compiler tools so they can be rebuilt for you.  What happens if you:

    sudo apt-get install build-essential g++

Then, in the directory of your project run `meteor npm rebuild`.

**Comment by badmark** [comment]
The file I am getting this error in is a client file, the error I receive is when I run meteor. This exact code works fine in 1.3.

I already have all of the required build packages install, as well as the correct Python. I run meteor npm rebuild and everything rebuilds without error. I am at a complete loss.

**Comment by c9s** [comment]
here is my steps to rebuild the packages:

```
cd ${BUNDLE_DIR}/programs/server
rm -rf npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt
npm install -f bcrypt
cp -r node_modules/bcrypt npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt
rm -rf npm/node_modules/bignum
npm install -f bignum
cp -r node_modules/bignum npm/node_modules/bignum
```

**Comment by abernix** [comment]
@badmark:

> W20160728-11:01:09.057(-4)? (STDERR) TypeError: Meteor.subscribe is not a function

This message is being output in your server log.  There must be some `import` path that is allowing the server to import your client code.  Please examine your code paths carefully.

> (Ubuntu 16.04 x64)
> When starting from scratch on 1.4 the error begins after adding accounts-base package

I'm guessing you somehow still don't have the necessary build requirements for this otherwise it should work.  `node-gyp` takes care of building binary dependencies for NPM pacakges (and is a critical part of the Node NPM package buiding system).  The official instructions for build requirements are available on [`node-gyp`'s README](https://github.com/nodejs/node-gyp#installation).

One of those requirements is Python 2.7 however, [Ubuntu 16.04 no longer ships with Python 2.7](https://wiki.ubuntu.com/Python) – only Python 3.  `node-gyp` itself isn't ready for this to happen.  

These steps just worked for me on a brand new Ubuntu 16.04 64-bit server:

```sh
$ # Install compiler tools and python
$ sudo apt-get install -y build-essential g++ python2.7
...
$ # Set the PYTHON env so node-gyp knows where to find it
$ export PYTHON=$(which python2.7)
$ # Make the previous line permanent by adding to your ~/.bashrc (recommended)
$ echo 'export PYTHON="$(which python2.7)"' >> .bashrc
$ meteor create app
$ cd app
app $ meteor npm install
app $ meteor add accounts-password
app $ # It adds successfully
app $ meteor
```

If you _still_ experience problems after all that, please run the following **from your app root**.  This is a bit extreme, and I doubt you need to do this, but if something wasn't setup right before, it could help:

```sh
$ # From your App root
$ rm -rf ~/.node-gyp/ ~/.meteor/packages/npm-bcrypt/ .meteor/local/{build,bundler-cache,isopacks,plugin-cache} node_modules/
```

**Comment by badmark** [comment]
So recreating my entire development environment from scratch, I was able to correct the odd issues in development. On production I had to append the following lines to my script:

```
cd  <root app folder>/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt
node-gyp rebuild
```

Thank you everyone for your help. 

Application performance has been visibly increased after the upgrade. Cheers!

**Comment by cristianhoyos66** [comment]
My solution was upgrade meteor version. This thread is old, but if anyone is working with an old project the meteor version could be since 1.3.x
