### ISSUE TITLE
Caching compiler's addJavascript not working consistently

### ISSUE THREAD

**Issue by jmdsg** [meteor/meteor#10280]
- [x] A short, but descriptive title. The title doesn't need "Meteor" in it.

I am ussing a custom caching compiler to add `.png`, `.jpg` and `.svg` files, the plugin is actually a clone of `nathantreid:static-assets` with the `ecmascript` and `caching-compiler` dependencies updated, but it is pretty simple, the important part is in `./packages/meteor-static-assets/compiler.js`

- [x] The version of Meteor showing the problem.
    - 1.8
- [x] The last version of Meteor where the problem did _not_ occur, if applicable.
    - 1.7.0.5
- [x] The operating system you're running Meteor on.
    - Windows 10 64 bits, version 1803 (also tried in heroku which i think uses ubuntu)
- [x] The expected behavior.
    - The image is added as an asset and a javascript file is added.
- [x] The actual behavior.
    - The asset is added but not the javascript. When i import an image it says the following:
    
        > Uncaught Error: Cannot find module '../assets/img/sidebar-1.jpg'
    at makeMissingError (modules-runtime.js?hash=b819d45cbf32aff410d740fac0364cb4088cd3f2:232)
    at Module.require (modules-runtime.js?hash=b819d45cbf32aff410d740fac0364cb4088cd3f2:251)
    at Module.moduleLink [as link] (modules.js?hash=c2dce81526f9ee2b07e113ba2ac820abeb31eb74:299)
    at Signin.js (Signin.js:1)
    at fileEvaluate (modules-runtime.js?hash=b819d45cbf32aff410d740fac0364cb4088cd3f2:346)
    at Module.require (modules-runtime.js?hash=b819d45cbf32aff410d740fac0364cb4088cd3f2:248)
    at Module.moduleLink [as link] (modules.js?hash=c2dce81526f9ee2b07e113ba2ac820abeb31eb74:299)
    at App.js (App.js:1)
    at fileEvaluate (modules-runtime.js?hash=b819d45cbf32aff410d740fac0364cb4088cd3f2:346)
    at Module.require (modules-runtime.js?hash=b819d45cbf32aff410d740fac0364cb4088cd3f2:248)

- [x] A **simple** reproduction!
    - This can be showed in this MCVE:
        - https://github.com/jmdsg/meteor-caching-compiler-example/tree/meteor1.8
        - https://github.com/jmdsg/meteor-caching-compiler-example/tree/meteor1.7

    - In this example the meteor 1.8 version does not work while the 1.7 does. I have made it work in the 1.8 changing some files (i don't know if is related with the cache), yesterday i moved `marc.jpg` from `assets/img/faces/` to `assets/img/` and it started to work.

    - The 1.7 version adds code similar to this one for each of the 3 images:

        ```javascript
        // ...
        // imports/ui/assets/img/sidebar-1.jpg
        module.watch(require("./sidebar-1.jpg.js"), {
          "*": module.makeNsSetter(true)
        });
        // ...
        // imports/ui/assets/img/sidebar-1.jpg.js
        module.exports = require('meteor/meteor').Meteor
            .absoluteUrl('static/imports/ui/assets/img/sidebar-1.jpg');
        // ...
        ```

    - The 1.8 version adds code only for the first image:

        ```javascript
        // ...
        // imports/ui/assets/img/faces/marc.jpg
        module.link("./marc.jpg.js", { "*": "*+" });
        // ...
        // imports/ui/assets/img/faces/marc.jpg.js
        module.exports = require('meteor/meteor').Meteor
            .absoluteUrl('static/imports/ui/assets/img/faces/marc.jpg');
        // ...
        ```

**Comment by jmdsg** [comment]
Was anyone able to reproduce this or just me. I am still not sure if this is a bug or a misuse of the caching compiler, the only difference between this `meteor-static-assets` and the current `nathantreid:static-assets` is the updated packages mentioned above.
