### ISSUE TITLE
Issue on accounts-google package on METEOR@1.7.1-beta.21

### ISSUE THREAD

**Issue by juvyc** [meteor/meteor#10188]
Hello Guys,

Not sure if this is the right place to put this issue. But right now, we encountered server error when logging-in using accounts-google (release 1.3.2-beta171.21) package at meteor version 1.7.1-beta.21. 

```
W20180830-00:02:41.210(0) (oauth.js:424) Error in OAuth Server: hasOwn is not defined
I20180830-00:02:41.946(0)? Exception while invoking method 'login' { ReferenceError: hasOwn is not defined
I20180830-00:02:41.947(0)?     at getServiceDataFromTokens (packages/google-oauth/google_server.js:18:3)
I20180830-00:02:41.948(0)?     at Object.getServiceData [as handleOauthRequest] (packages/google-oauth/google_server.js:78:33)
I20180830-00:02:41.948(0)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
I20180830-00:02:41.948(0)?     at middleware (packages/oauth.js:194:5)
I20180830-00:02:41.948(0)?     at /home/ubuntu/.meteor/packages/promise/.0.11.1.unjajh.03et++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 message: 'hasOwn is not defined' }
```
But it works on lower version of meteor.

Thanks!

**Comment by jamesmillerburgess** [comment]
I believe this was fixed in https://github.com/meteor/meteor/pull/9942/commits/36d9bc12bb897a1e30423a68d4dca4e0c5b0cf32, which was part of `1.7.1-beta.31`. Can you check if you still have any issues after updating to the latest release candidate of 1.7.1?

**Comment by juvyc** [comment]
Thanks, it's working on 1.7.1-beta.31
