### PR TITLE
Fix fetch() type declaration

### LINKED ISSUE #12351: Incorrect type decl for `fetch()` in `meteor/fetch`
Observed in Meteor 2.8.1

Introduced in https://github.com/meteor/meteor/commit/eb7a50c61006282d1e93c8e78b741fb885b295d9

This presumably only affects folks attempting to use the `zodern:types` package for typescript integration.

The type declaration at https://github.com/meteor/meteor/blob/ab07174f87e720cb876f785f857f9b16699cd482/packages/fetch/fetch.d.ts#L1 is incorrect.  `fetch` has the type of `globalThis.fetch`.  It is not a function which takes no arguments and returns that type.

Compare against https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2a56bfed7dec17a128dc5aedbbc6649553d6d30f/types/meteor/fetch.d.ts#L5 which has a correct typing.

### PR DESCRIPTION
**Pull request by zarvox**
`fetch()` is the type of `globalThis.fetch`; it is not a function which returns a `globalThis.fetch`.

Fixes #12351.

### CODE REVIEW

**Review by radekmie — APPROVED** [review]

**Comment by zarvox** [comment]
Test failure at https://app.circleci.com/pipelines/github/meteor/meteor/4146/workflows/0b352fe4-ca03-4321-b811-a081b4ae2c44/jobs/93806 appears unrelated?

I see the same failure (Test Group 3 killed while `running (12/18) create.js test:create --chakra-ui ...`) at HEAD: https://app.circleci.com/pipelines/github/meteor/meteor/4074/workflows/da5501de-27d7-4f13-875a-45a165e69e26/jobs/93113

**Review by henriquealbert — APPROVED** [review]

**Comment by Grubba27** [comment]
Set to rerun the checks, and I will merge this in our next patch! Thanks a lot again for your help

**Comment by Grubba27** [comment]
Will send this to 2.9.1 and solve from there
