### ISSUE TITLE
Incorrect type decl for `fetch()` in `meteor/fetch`

### ISSUE THREAD

**Issue by zarvox** [meteor/meteor#12351]
Observed in Meteor 2.8.1

Introduced in https://github.com/meteor/meteor/commit/eb7a50c61006282d1e93c8e78b741fb885b295d9

This presumably only affects folks attempting to use the `zodern:types` package for typescript integration.

The type declaration at https://github.com/meteor/meteor/blob/ab07174f87e720cb876f785f857f9b16699cd482/packages/fetch/fetch.d.ts#L1 is incorrect.  `fetch` has the type of `globalThis.fetch`.  It is not a function which takes no arguments and returns that type.

Compare against https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2a56bfed7dec17a128dc5aedbbc6649553d6d30f/types/meteor/fetch.d.ts#L5 which has a correct typing.

**Comment by Grubba27** [comment]
Awesome catch! thx a lot for opening this issue
