### ISSUE TITLE
Missing some pseudo-globals in 1.3?

### ISSUE THREAD

**Issue by ryanfields** [meteor/meteor#6667]
I've found that the following do not work in 1.3:

```
import { ReactiveDict } from 'meteor/reactive-dict';
import { ReactiveVar } from 'meteor/reactive-var';
```

I just get `Cannot find module 'meteor/reactive-dict`, etc.

The new guide says to use `import` for all of Meteor's pseudo-globals.  Are these not considered pseudo-globals and am I supposed to still rely on the actual packages?  I'm wondering if there's a list somewhere detailing which are intended for import and which still have to be included globally via `meteor add`.

**Comment by ryanfields** [comment]
Ah.  Weird.  I was originally getting undefined imports, so I'd removed the meteor packages.  When I added the packages back, it seems to be working fine.  I'm not sure what was wrong the first time around, but I'm going to close this as it's now something I can't reproduce.
