### ISSUE TITLE
[1.7.0.1] es7 array flatter and other strange issues

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#9925]
This happens after upgrade to 1.7.0.1 from 1.5.4.something

```
Uncaught Error: Cannot find module 'core-js/modules/es7.array.flatten'
    at makeMissingError (modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:241)
    at require (modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:251)
    at modern.js (ecmascript-runtime-client.js?hash=3755b87a9db33c177a60cfa7cbf41e1d9033df6f:32)
    at fileEvaluate (modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349)
    at require (modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248)
    at ecmascript-runtime-client.js?hash=3755b87a9db33c177a60cfa7cbf41e1d9033df6f:48
    at ecmascript-runtime-client.js?hash=3755b87a9db33c177a60cfa7cbf41e1d9033df6f:53
lai_collection-extensions.js?hash=3c7218d278e8d69be644f831afd44f6dc756d5b9:58 `Meteor.addCollectionExtension` is deprecated, please use `CollectionExtensions.addExtension`
Meteor.addCollectionExtension @ lai_collection-extensions.js?hash=3c7218d278e8d69be644f831afd44f6dc756d5b9:58
meteor.js?hash=c8108d734cc548d91539b054e14b613d0c4512cc:1010 Exception in template helper: TypeError: Cannot read property 'apply' of undefined
    at ReactiveDict.PersistentSession.old_get (http://localhost:3000/packages/u2622_persistent-session.js?hash=57db38c11edeebc31dce68f5b5be8581c20a2286:241:25)
    at ReactiveDict._psGet [as get] (http://localhost:3000/packages/u2622_persistent-session.js?hash=57db38c11edeebc31dce68f5b5be8581c20a2286:244:18)
    at Object.get (http://localhost:3000/packages/accounts-ui-unstyled.js?hash=215c2e819839e04fe71a66b39df2d61c6a6bc8d3:919:20)
    at Object.inResetPasswordFlow (http://localhost:3000/packages/accounts-ui-unstyled.js?hash=215c2e819839e04fe71a66b39df2d61c6a6bc8d3:1879:32)
    at http://localhost:3000/packages/blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3051:16
    at http://localhost:3000/packages/blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:1715:16
    at http://localhost:3000/packages/blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3103:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3102:27
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?hash=547cf8e466d1d52603d19bd5f48fb5df184fd237:172:18)
```

**Comment by theodorDiaconu** [comment]
First error solved by installing `core-js`

**Comment by evolross** [comment]
The other error is related to this #9918 perhaps? [u2622:persistent-session](https://atmospherejs.com/u2622/persistent-session) is broken in Meteor 1.7. I also use this package extensively so will be interested in any updates.

Hey, weren't we supposed to be sipping cocktails mingling with Hollywood A-listers!?  Instead we're both working on Meteor stuff. :P

**Comment by theodorDiaconu** [comment]
@evolross indeed that would've been better, but regarding this issue, is very strange, why would I need core-js for modern browser, and why would it break old packages ? 1.7.0.1 doesn't seem stable at all

**Comment by tcastelli** [comment]
Also having the same two issues, resolved first installing core-js although not sure why it was able to work without it before. As for persistent session, I tried to create a local package to fix the problem, but it ended being too strange (after importing Session package to extend it, it was not finding get function on the session object), so I just removed all the code using persistent session and user localStorage instead (didn't need reactivity).
For lai:ddp-connections might end being more troublesome

**Comment by benjamn** [comment]
Typically `core-js` is installed as a side-effect of installing `@babel/runtime`, so that's probably why this was working before. To answer your question, @theodorDiaconu, `core-js` includes polyfills for ECMAScript proposals that modern browsers need, so it's a misconception that `core-js` is not needed in modern browsers.

**Comment by theodorDiaconu** [comment]
@benjamn that is fine but why would other packages break ?

**Comment by benjamn** [comment]
Babel-generated code anywhere in the application (including packages) could be using the `node_modules/core-js` package installed in the application. That's how it's worked since Meteor 1.4, which means packages published since July 2016 might be depending on `core-js`.

**Comment by theodorDiaconu** [comment]
I get it, the problem was actually related to _.clone() on a ReactiveDict xD

For the persistent session I ended up launching cultofcoders:persistent-session

**Comment by theodorDiaconu** [comment]
@evolross https://github.com/cult-of-coders/meteor-persistent-session

**Comment by maxfi** [comment]
> There's a good chance that the old babel-runtime package can be removed from your package.json dependencies, though there's no harm in leaving it there. 
-- https://github.com/meteor/meteor/blob/devel/History.md#v161-2018-01-19

Removing the old `babel-runtime` package fixed the issue for me.

**Comment by elie222** [comment]
I added `core-js`, but from here I see it's about 45% of the legacy bundle size. How can this problem be solved by not having to add `core-js`?
