### ISSUE TITLE
Can't run a newly created full 1.5.1 Meteor app

### ISSUE THREAD

**Issue by evolross** [meteor/meteor#9543]
I'm on OS X 10.10.5. I was trying to build a repo to demonstrate a bug I'm getting upgrading from 1.5.1 upward and I ran into a bug trying to build a repo at 1.5.1.

I did:

`meteor create --release 1.5.1 --full myProject`
`cd myProject`
`meteor`

And I get:

```
=> Started proxy.                             
=> A patch (Meteor 1.5.4.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While loading plugin `minifyStdJS` from package `standard-minifier-js`:
   vm.js:24:10: Block-scoped declarations (let, const, function, class) not yet supported
   outside strict mode
   at Object.exports.createScript (vm.js:24:10)
   at /tools/fs/files.js:1161:34
   at Function.time (/tools/tool-env/profile.js:305:10)
   at Object.files.runJavaScript (/tools/fs/files.js:1099:18)
   at /tools/isobuild/bundler.js:1936:15
   at Array.forEach (native)
   at Function._.each._.forEach
   (/Users/rossmnewton/.meteor/packages/meteor-tool/.1.5.1.yt2f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at JsImage.load (/tools/isobuild/bundler.js:1849:7)
   at /tools/isobuild/isopack.js:536:16
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/isopack.js:526:20
   at Function._.each._.forEach
   (/Users/rossmnewton/.meteor/packages/meteor-tool/.1.5.1.yt2f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
   at [object Object].ensurePluginsInitialized (/tools/isobuild/isopack.js:514:7)
   at /tools/isobuild/compiler.js:382:16
   at Array.forEach (native)
   at /tools/isobuild/compiler.js:381:26
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/compiler.js:377:16
   at /tools/isobuild/compiler.js:184:28
   at Object.withCache (/tools/fs/files.js:1652:12)
   at /tools/isobuild/compiler.js:183:11
   at Array.forEach (native)
   at Function._.each._.forEach
   (/Users/rossmnewton/.meteor/packages/meteor-tool/.1.5.1.yt2f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at Object.compile (/tools/isobuild/compiler.js:178:5)
   at /tools/isobuild/bundler.js:2917:24
   at /tools/utils/buildmessage.js:271:13
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:264:29
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:262:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:253:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.capture (/tools/utils/buildmessage.js:252:19)
   at bundle (/tools/isobuild/bundler.js:2860:31)
   at /tools/isobuild/bundler.js:2807:32
   at Object.withCache (/tools/fs/files.js:1652:12)
   at Object.exports.bundle (/tools/isobuild/bundler.js:2807:16)
   at /tools/runners/run-app.js:588:36
   at Function.run (/tools/tool-env/profile.js:490:12)
   at bundleApp (/tools/runners/run-app.js:587:34)
   at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
   at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
   at /tools/runners/run-app.js:417:12
   
   
   While loading plugin `compileLessBatch` from package `less`:
   vm.js:24:10: Unexpected token ...
   at Object.exports.createScript (vm.js:24:10)
   at /tools/fs/files.js:1161:34
   at Function.time (/tools/tool-env/profile.js:305:10)
   at Object.files.runJavaScript (/tools/fs/files.js:1099:18)
   at /tools/isobuild/bundler.js:1936:15
   at Array.forEach (native)
   at Function._.each._.forEach
   (/Users/rossmnewton/.meteor/packages/meteor-tool/.1.5.1.yt2f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at JsImage.load (/tools/isobuild/bundler.js:1849:7)
   at /tools/isobuild/isopack.js:536:16
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/isopack.js:526:20
   at Function._.each._.forEach
   (/Users/rossmnewton/.meteor/packages/meteor-tool/.1.5.1.yt2f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
   at [object Object].ensurePluginsInitialized (/tools/isobuild/isopack.js:514:7)
   at /tools/isobuild/compiler.js:382:16
   at Array.forEach (native)
   at /tools/isobuild/compiler.js:381:26
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/compiler.js:377:16
   at /tools/isobuild/compiler.js:184:28
   at Object.withCache (/tools/fs/files.js:1652:12)
   at /tools/isobuild/compiler.js:183:11
   at Array.forEach (native)
   at Function._.each._.forEach
   (/Users/rossmnewton/.meteor/packages/meteor-tool/.1.5.1.yt2f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at Object.compile (/tools/isobuild/compiler.js:178:5)
   at /tools/isobuild/bundler.js:2917:24
   at /tools/utils/buildmessage.js:271:13
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:264:29
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:262:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:253:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.capture (/tools/utils/buildmessage.js:252:19)
   at bundle (/tools/isobuild/bundler.js:2860:31)
   at /tools/isobuild/bundler.js:2807:32
   at Object.withCache (/tools/fs/files.js:1652:12)
   at Object.exports.bundle (/tools/isobuild/bundler.js:2807:16)
   at /tools/runners/run-app.js:588:36
   at Function.run (/tools/tool-env/profile.js:490:12)
   at bundleApp (/tools/runners/run-app.js:587:34)
   at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
   at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
   at /tools/runners/run-app.js:417:12
   
   
=> Your application has errors. Waiting for file change.
```
The packages file created is:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.1.0             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.19                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.4   # CSS minifier run for production mode
standard-minifier-js@2.1.1    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers
ecmascript@0.8.1              # Enable ECMAScript2015+ syntax in app code

kadira:flow-router      # FlowRouter is a very simple router for Meteor
kadira:blaze-layout     # Layout manager for blaze (works well with FlowRouter)
less@2.7.9                    # Leaner CSS language


practicalmeteor:mocha             # A package for writing and running your meteor app and package tests with mocha
johanbrook:publication-collector  # Test a Meteor publication by collecting its output
```

**Comment by benjamn** [comment]
You should edit the versions of `standard-minifier-js` and `less` in the `.meteor/versions` file to match the constraints in `.meteor/packages`—that is, `2.1.1` and `2.7.9`, respectively. Since Meteor 1.5.1 was first published, more recent versions of those packages have been released that are apparently not fully compatible with 1.5.1. If you created the app around the time Meteor 1.5.1 was released, you'd still be using the original versions of those packages, and things would still work. Creating a new app with an old version of Meteor exposes you to more recent versions of packages than you might want.

**Comment by evolross** [comment]
Understood. I know building fresh projects using old versions of Meteor isn't something that's used often. But it is helpful for building repos for testing bugs that pop up when trying to upgrade to the latest. I think I solved the bug I was making this 1.5.1 repo for, but FWIW, I made the updates to the versions of `standard-minifier-js` and `less` and now I'm getting this upon trying to start the app:
```
W20180116-17:51:22.789(-8)? (STDERR) /Users/rossmnewton/.meteor/packages/meteor-tool/.1.5.1.yt2f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180116-17:51:22.852(-8)? (STDERR) 						throw(ex);
W20180116-17:51:22.854(-8)? (STDERR) 						^
W20180116-17:51:22.855(-8)? (STDERR) 
W20180116-17:51:22.856(-8)? (STDERR) TypeError: fieldsKeys.includes is not a function
W20180116-17:51:22.857(-8)? (STDERR)     at projectionDetails (packages/minimongo/common.js:1309:20)
W20180116-17:51:22.857(-8)? (STDERR)     at Function.LocalCollection._compileProjection (packages/minimongo/local_collection.js:869:19)
W20180116-17:51:22.858(-8)? (STDERR)     at new Cursor (packages/minimongo/cursor.js:33:42)
W20180116-17:51:22.859(-8)? (STDERR)     at LocalCollection.find (packages/minimongo/local_collection.js:68:12)
W20180116-17:51:22.859(-8)? (STDERR)     at LocalCollection.findOne (packages/minimongo/local_collection.js:86:17)
W20180116-17:51:22.860(-8)? (STDERR)     at [object Object]._.extend.findOne (packages/mongo/collection.js:334:29)
W20180116-17:51:22.860(-8)? (STDERR)     at updateVersions (packages/autoupdate.js:121:24)
W20180116-17:51:22.861(-8)? (STDERR)     at packages/autoupdate.js:189:3
W20180116-17:51:22.862(-8)? (STDERR)     at Function.time (/Users/rossmnewton/Projects/test151FullNewApp/.meteor/local/build/programs/server/profile.js:309:28)
W20180116-17:51:22.863(-8)? (STDERR)     at /Users/rossmnewton/Projects/test151FullNewApp/.meteor/local/build/programs/server/boot.js:347:13
=> Exited with code: 1
```

**Comment by crapthings** [comment]
try paste these into .meteor/packages

# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var            # Reactive variable for tracker
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers
ecmascript              # Enable ECMAScript2015+ syntax in app code

kadira:flow-router      # FlowRouter is a very simple router for Meteor
kadira:blaze-layout     # Layout manager for blaze (works well with FlowRouter)
less                    # Leaner CSS language

practicalmeteor:mocha             # A package for writing and running your meteor app and package tests with mocha
johanbrook:publication-collector  # Test a Meteor publication by collecting its output

then rm .meteor/versions

**Comment by hwillson** [comment]
Thanks for pointing this out @evolross. 

> I know building fresh projects using old versions of Meteor isn't something that's used often. But it is helpful for building repos for testing bugs that pop up when trying to upgrade to the latest.

You're quite right. We try to make sure all package patches remain compatible with their associated Meteor release, but sometimes incompatible changes slip through the cracks. You're still seeing issues after updating `standard-minifier-js` and `less` as there were other package changes that need to be pulled in as well (involving `minimongo`). Glad to hear you addressed your original issue. We'll look into ways to help avoid this happening in the future, while at the same time making sure we aren't hindering forward progress. Thanks!

**Comment by sylido** [comment]
I'm experiencing eactly the same behavior after working on 1.5.1 and doing an update --packages-only - everything broke.
`less` doesn't work, replacing it with `grove:less` seems to fix it
`meteorhacks:fast-render` fails as well, replacing it with `staringatlights:fast-render` seems to work
`standard-minifier-js@2.1.1` fails too, replaced with `abernix:standard-minifier-js` that fixes it
`yogiben:autoform-file` also fails, but that might be, because the package is not maintained anymore
replaced it with `ostrio:autoform-files` and that fixed that, but there is a new error that appears, pasted below.

> /home/meteor/.meteor/packages/meteor-tool/.1.5.1.puot9a++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280 
  throw(ex);
  TypeError: fieldsKeys.includes is not a function
    at projectionDetails (packages/minimongo/common.js:1309:20)
    at Function.LocalCollection._compileProjection (packages/minimongo/local_collection.js:869:19)
    at new OplogObserveDriver (packages/mongo/oplog_observe_driver.js:90:40)
    at [object Object].MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1253:21)
    at [object Object].Cursor.observeChanges (packages/mongo/mongo_driver.js:935:22)
    at _getMultiplexer (packages/meteorhacks_meteorx.js:138:24)
    at _getObserverDriver (packages/meteorhacks_meteorx.js:131:21)
    at exposeOplogDriver (packages/meteorhacks_meteorx.js:107:16)
    at exposeMongoLivedata (packages/meteorhacks_meteorx.js:101:3)
    at packages/meteorhacks_meteorx.js:181:5

Seems like one of the other `meteorhacks` packages that we use is doing that -> `kadira`, `aggregate` or/and `async`

**Comment by evolross** [comment]
@sylido Sounds like you're having package problems upgrading. I would Google around for the errors you're getting (and it sounds like you're already doing that). The original problem of this bug report is not having a blank project with the `--full` setting run correctly after being created, which is unrelated to upgrading.

**Comment by sylido** [comment]
hey @evolross - it's true, my problems started with the `meteor update --packages-only` while I was on 1.5.1, but then I tried re-cloning my repo and installing meteor 1.5.1 anew. The package file and versions file is pinned to the correct package versions, but it still seems to go ahead and download newer versions, so I have the same issue in a way, not getting the right package versions.

**Comment by hwillson** [comment]
Quick follow up to https://github.com/meteor/meteor/issues/9543#issuecomment-358315818 - we've discussed this issue internally, and will try to be more careful with regards to creating situations like this in the future. If you had created a 1.5.1 project back when 1.5.1 was released, and had kept working with it from that point forward (and `meteor update`'ing as needed), your app would have continued to work properly. It's the new project creation at a specific release that caused this issue, which while really nice to have working properly, is much less of an issue for the developer base as a whole. Still, we'll do our best to make sure `meteor create --release XXX` continues to work as it should, but given a tradeoff between forward progress and impacting new project creation using an old release, we'll likely give forward progress more weight.

Thanks again for reporting this @evolross!
