### ISSUE TITLE
Exported function named "load" not exported from npm module

### ISSUE THREAD

**Issue by CaptainN** [meteor/meteor#10790]
An npm module I'm using (`svelte-loadable`) exports a method named "load". This method is not exported, leading to a "load" is not a function error. If I rename the method it to exports normally.

I think this worked at one point in the Meteor 1.8.2 beta or rc cycle, but it does not work in 1.8.2.

It's easy enough to see this in action - just try to import `svelte-loadable` into a project, and then inspect the `modules.js` file, search for `svelte-loadable` and you'll see that the "load" method is not exported. Then change the exported "load" method inside `node_modules/svelte-loadable` and restart. You'll then see the renamed function is in the export list.

**Comment by benjamn** [comment]
What compiler plugin are you using to compile `.svelte` files? I ask because the entry point for `svelte-loadable` is a file called `Loadable.svelte`.

**Comment by CaptainN** [comment]
I'm using `svelte:compiler`
