### ISSUE TITLE
collection.observe() throws exception when handle._added is undefined

### ISSUE THREAD

**Issue by stiang** [meteor/meteor#589]
I have the following code in server/publish.js:

```
Meteor.publish("counts-by-view", function (userId, randomery) {
  var self = this;

  Dummy.insert({name: "blabla"});

  updateViewCounts(self);

  var handle = Dummy.find().observe({
    changed: function (doc, idx) {
      updateViewCounts(self);
      self.flush();
    }
  });

  self.onStop(function () {
    handle.stop();
    self.flush();
  });

  self.flush();
});  
```

After upgrading from 0.5.0 to 0.5.2 I keep getting the following exception:

```
Internal exception while starting subscription 9456cbe6-93af-4cdd-8faa-edfbad9e9b34 TypeError: Property '_added' of object [object Object] is not a function
    at Object.Future.wait (/usr/local/meteor/lib/node_modules/fibers/future.js:322:15)
    at _.extend.runTask (app/packages/meteor/fiber_helpers.js:73:9)
    at _.extend._addObserveHandleAndSendInitialAdds (app/packages/mongo-livedata/mongo_driver.js:720:21)
    at _Mongo._observe (app/packages/mongo-livedata/mongo_driver.js:513:20)
    at Cursor.observe (app/packages/mongo-livedata/mongo_driver.js:338:22)
    at null.<anonymous> (app/server/publish.js:107:29)
    at sub._runHandler (app/packages/livedata/livedata_server.js:355:27)
    at _.extend._startSubscription (app/packages/livedata/livedata_server.js:381:9)
    at _.extend.protocol_handlers.sub (app/packages/livedata/livedata_server.js:224:12)
    at processNext (app/packages/livedata/livedata_server.js:188:43)
    - - - - -
    at _.extend._addObserveHandleAndSendInitialAdds (app/packages/mongo-livedata/mongo_driver.js:731:16)
    at Array.forEach (native)
    at Function._.each._.forEach (app/packages/underscore/underscore.js:79:11)
    at Object._.extend._addObserveHandleAndSendInitialAdds [as task] (app/packages/mongo-livedata/mongo_driver.js:730:9)
    at _.extend._run (app/packages/meteor/fiber_helpers.js:118:18)
    at _.extend._scheduleRun (app/packages/meteor/fiber_helpers.js:96:14)
```

This seems to be caused by _added being undefined in line 730 of meteor/packages/mongo-livedata/mongo_driver.js:

```
    handle._added(LocalCollection._deepcopy(doc),
                  self._ordered ? i : undefined);
```

Here is a dump of the "handle" variable in that method:

```
{ _liveResultsSet: 
   { _cursorDescription: { collectionName: 'dummy', selector: {}, options: {} },
     _mongoHandle: 
      { collection_queue: [],
        _liveResultsSets: [Object],
        db: [Object] },
     _ordered: true,
     _stopCallbacks: [ [Function], [Function], [Function] ],
     _synchronousCursor: 
      { _dbCursor: [Object],
        _synchronousNextObject: [Function],
        _synchronousCount: [Function],
        _visitedIds: [Object] },
     _results: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     _pollsScheduledButNotStarted: 0,
     _addHandleTasksScheduledButNotPerformed: 0,
     _pendingWrites: [],
     _ensurePollIsScheduled: [Function],
     _taskQueue: 
      { _taskHandles: [],
        _runningOrRunScheduled: false,
        _currentTaskFiber: undefined },
     _observeHandles: { '15': [Object] },
     _callbackMultiplexer: 
      { added: [Function],
        changed: [Function],
        removed: [Function],
        moved: [Function] } },
  _added: undefined,
  _changed: [Function],
  _removed: undefined,
  _moved: undefined,
  _observeHandleId: 34 }
```

Am I doing something wrong here or is this a bug? Should _addObserveHandleAndSendInitialAdds check that _added is actually a function before trying to call it?
