### ISSUE TITLE
Meteor 1.3.4.4 can't deploy

### ISSUE THREAD

**Issue by jacobjuul** [meteor/meteor#7429]
after updating meteor from 1.3.3 to 1.3.4.4 I get the following error on galaxy when deploying.
```shell
2016-07-18 12:00:01+02:00
bqfm
2016-07-18 12:00:01+02:00/app/bundle/programs/server/boot.js:338
bqfm
2016-07-18 12:00:01+02:00}).run();
bqfm
2016-07-18 12:00:01+02:00 ^
bqfm
2016-07-18 12:00:01+02:00Error: Cannot find module 'core-js/library/fn/symbol'
bqfm
2016-07-18 12:00:01+02:00 at Function.Module._resolveFilename (module.js:338:15)
bqfm
2016-07-18 12:00:01+02:00 at Function.Module._load (module.js:280:25)
bqfm
2016-07-18 12:00:01+02:00 at Module.require (module.js:364:17)
bqfm
2016-07-18 12:00:01+02:00 at require (module.js:380:17)
bqfm
2016-07-18 12:00:01+02:00 at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/babel-runtime/core-js/symbol.js:1:31)
bqfm
2016-07-18 12:00:01+02:00 at Module._compile (module.js:456:26)
bqfm
2016-07-18 12:00:01+02:00 at Object.Module._extensions..js (module.js:474:10)
bqfm
2016-07-18 12:00:01+02:00 at Module.load (module.js:356:32)
bqfm
2016-07-18 12:00:01+02:00 at Module.Mp.load (/app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
bqfm
2016-07-18 12:00:01+02:00 at Function.Module._load (module.js:312:12)
```

I'm using the `webpack:webpack` athmosphere package (and `webpack:scss`, `webpack:react`)

### packages
```yaml
accounts-ui
accounts-password
service-configuration
email
aldeed:simple-schema
aldeed:collection2
themeteorchef:bert
standard-minifier-css
standard-minifier-js
accounts-facebook
accounts-base
mrgalaxy:stripe
reactive-var
http
react-meteor-data
edgee:slingshot
fortawesome:fontawesome
deanius:promise
meteorhacks:ssr
vsivsi:job-collection
nooitaf:colors
webpack:sass
fourseven:scss
webpack:webpack
webpack:react
```

### package.json
```json
 {
  "dependencies": {
    "chalk": "^1.1.3",
    "classnames": "^2.2.5",
    "domain": "0.0.1",
    "email-validator": "^1.0.4",
    "globalize": "^1.1.1",
    "google-libphonenumber": "^1.0.23",
    "halogen": "^0.2.0",
    "history": "^3.0.0",
    "lodash": "^4.13.1",
    "material-ui": "^0.15.0",
    "meteor-node-stubs": "^0.2.3",
    "moment": "^2.13.0",
    "npm": "^3.9.5",
    "radium": "^0.17.1",
    "react": "^15.2.1",
    "react-addons-create-fragment": "^15.2.1",
    "react-addons-css-transition-group": "^15.2.1",
    "react-addons-linked-state-mixin": "^15.2.1",
    "react-addons-perf": "^15.2.1",
    "react-addons-pure-render-mixin": "^15.2.1",
    "react-addons-test-utils": "^15.2.1",
    "react-addons-transition-group": "^15.2.1",
    "react-addons-update": "^15.2.1",
    "react-bootstrap": "^0.29.5",
    "react-creditcard-input": "0.0.1",
    "react-cropper": "^0.8.0",
    "react-data-grid": "^1.0.8",
    "react-dom": "^15.2.1",
    "react-geosuggest": "^1.23.0",
    "react-google-maps": "^4.11.0",
    "react-html5video": "^1.2.9",
    "react-images": "^0.4.6",
    "react-router": "^2.4.1",
    "react-select": "^1.0.0-beta13",
    "react-tap-event-plugin": "^1.0.0",
    "react-textarea-autosize": "^4.0.3",
    "react-ux-password-field": "^0.9.12",
    "react-widgets": "^3.3.2",
    "uuid": "^2.0.2"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.9.1",
    "babel-eslint": "^6.0.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-plugin-transform-class-properties": "^6.10.2",
    "babel-plugin-transform-decorators": "^6.8.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-stage-0": "^6.5.0",
    "eslint": "^2.12.0",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-import-resolver-meteor": "^0.2.4",
    "eslint-plugin-babel": "^3.2.0",
    "eslint-plugin-import": "^1.9.2",
    "eslint-plugin-jsx-a11y": "^1.4.2",
    "eslint-plugin-meteor": "^3.6.0",
    "eslint-plugin-react": "^5.1.1",
    "webpack": "^1.13.0",
    "webpack-hot-middleware": "^2.10.0",
    "style-loader": "^0.13.0",
    "css-loader": "^0.23.0",
    "extract-text-webpack-plugin": "^0.9.1",
    "sass-loader": "^3.1.2",
    "node-sass": "^3.4.2",
    "url-loader": "^0.5.7",
    "file-loader": "^0.8.5",
    "json-loader": "^0.5.4",
    "babel-preset-react": "^6.3.13",
    "expose-loader": "^0.7.1",
    "react-transform-hmr": "^1.0.1",
    "react-transform-catch-errors": "^1.0.0",
    "redbox-react": "^1.2.0"
  }
}
```

**Comment by abernix** [comment]
And you have no problem running this project locally?  Perhaps also try removing the `node_modules` directory and running `meteor npm install` in your project root before you deploy?

**Comment by jacobjuul** [comment]
@abernix no problems running it locally. I tried deleting `node_modules` and doing `meteor reset`

could it be my .babelrc?
```json
{
  "presets": [
    "stage-0",
    "es2015"
  ],

  "plugins": [
    "transform-decorators-legacy",
    "transform-decorators",
    "transform-class-properties",
    "transform-async-to-generator"
  ]
}
```

**Comment by abernix** [comment]
I don't expect that to be the problem, however the best way to try would be to put that into a new project and try loading it into Galaxy as a separate application.

There are a lot of other users using Meteor 1.3.4.4 on Galaxy who are not experiencing this problem so there are no go-to answers I can give you.  My recommendation would be to to try to reproduce it in a much more simple project.  Since you already have a project exhibiting this problem, copy your current project and begin yanking out more and more pieces until you see this problem and can't remove anything else.  The main entry points are a great place to start commenting things out!  If you can provide a reproduction, then someone can easily analyze the problem and figure out if it's a problem with your configuration or a problem with Meteor itself.

Also, try running it outside of Galaxy but as a deployed app (in the same way that Galaxy would run it) and see how it works for you.  Try the [Custom deployment options in Meteor Guide](https://guide.meteor.com/deployment.html#custom-deployment) for help with that.

**Comment by laosb** [comment]
Close due to inactivity. If someone found this again, please open a new issue or comment below.
