### ISSUE TITLE
deploy on meteor 1.6.1 centos 6.8

### ISSUE THREAD

**Issue by moslemir** [meteor/meteor#9618]
deploy on meteor 1.6.1 centos 6.8

After upgrade my procject form 1.5.2.2 to 1.6.1, extract my build project file in 'bundle/program/server',
and 'meteor npm i --production', faced to this error:
```

> fibers@2.0.0 install /home/username/domains/domain.com/public_html/tmp/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Problem with the binary; manual build incoming
make: Entering directory `/home/username/domains/domain.com/public_html/tmp/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:21,
                 from /home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
In file included from /home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: At global scope:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:333: error: expected unqualified-id before ‘using’
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:350: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:357: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:365: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal()’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:394: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:396: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In member function ‘bool v8::Eternal<T>::IsEmpty() const’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:401: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:775: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:800: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:812: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: At global scope:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:838: error: expected unqualified-id before ‘using’
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:1187: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:1193: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:1733: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: At global scope:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:3198: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:3839: error: ‘nullptr’ was not declared in this scope
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h: At global scope:
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:4108: error: function definition does not declare parameters
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:4164: error: expected unqualified-id before ‘&’ token
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:4164: error: expected ‘)’ before ‘&’ token
/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:4164: error: expected ‘;’ before ‘&’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ostream_insert.h:36,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:46,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from ../src/fibers.cc:8:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘;’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected unqualified-id before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected declaration before end of line
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/home/username/domains/domain.com/public_html/tmp/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-642.11.1.el6.x86_64
gyp ERR! command "/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/hay/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/username/domains/domain.com/public_html/tmp/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hay/.npm/_logs/2018-02-01T13_46_20_380Z-debug.log

```
My production server: centos 6.8, node 8.9.4 whith gcc 4.4.7 & glibc 2.12

**Comment by abernix** [comment]
Meteor 1.5 used Node.js v4 however Meteor 1.6.x uses Node.js 8.  There's some amazing improvements in Node.js 8, so I hope you'll get to upgrade.  With that said, I realize that CentOS is under long-term-support (LTS) until 2020, however the version of `gcc` which shipped with CentOS 6.8 is aging at this point and is going to cause you problems.

We can certainly relate to those problems.  We upgraded part of our build infrastructure (which runs CentOS 6.4 for maximum compatibility) in preparation for Meteor 1.6 to use `gcc`/`g++` 4.9.x because the Node Foundation has upped the version they use to build Node.js itself.  You'll see in [this official Node `BUILDING.md` documentation](https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms) that they build the official Node binaries (for distribution) with v4.9.4.

As the version of Node gets newer and the version of `gcc`/`g++`/`glibc` gets older, this will become more and more of a problem for you.  Unfortunately, my only suggestion here is for you to upgrade your compiler toolchain to newer versions, or upgrade your CentOS distribution.  There's some great information on how to do so [here](https://gist.github.com/stephenturner/e3bc5cfacc2dc67eca8b#gistcomment-1796976).  Hope this helps, but unfortunately, I'm afraid the alternative is to use a less modern version of Node.js and Meteor (that is, staying on Meteor 1.5), which I would highly advise against as Node.js 4 will only remain in LTS until the end of April 2018!
