### ISSUE TITLE
meteor 1.3-beta-5 npm "react-color-picker" client error: missing 'events'

### ISSUE THREAD

**Issue by ArdentKid** [meteor/meteor#6110]
Using react-color-picker in my project as npm module, but it isn't being loaded properly.

```
import {SaturationSpectrum, HueSpectrum} from 'react-color-picker';
```

Gives the following error in browser console:

```
Uncaught Error: Cannot find module 'events' ... installs.js:77
```

Anyone know a workaround or if this is fixable in meteor 1.3-beta-5?

**Comment by ArdentKid** [comment]
bump..?

**Comment by benjamn** [comment]
Can you try `npm install events` in your app? It seems like https://www.npmjs.com/package/events may be a mature, high-fidelity implementation of the Node built-in module.

**Comment by schabluk** [comment]
I have the same problem with 'enzyme' module. I'm trying to create a simple test for my Meteor/React application. When doing import { shallow } from 'enzyme', I'm getting this error to the browser console:

    Error: Cannot find module 'events'

Source code: https://github.com/schabluk/test-meteor
Test file: https://github.com/schabluk/test-meteor/blob/master/client/__tests__/main-test.js

**Comment by abernix** [comment]
This appears to work fine in Meteor 1.4.2.3.  Closing, but happy to reopen if this problem still is affecting you on new versions of Meteor.  Thanks for reporting this originally!
