### PR TITLE
Release 1.4.2.1

### PR DESCRIPTION
**Pull request by benjamn**
This release will be a bug-fixing follow-up to Meteor 1.4.2.

### CODE REVIEW

**Comment by veered** [comment]
Will this release address the huge performance improvement introduced by `METEOR_DISABLE_FS_FIBERS=1`? I think this should either be the default or we should find a different way of addressing the underlying issue.

**Comment by mitar** [comment]
My list of what should go into this release: #7573, #7972, #6002, and resolving the issue with FS fibers.

> I think that all the file caching improvements decreases the advantage of running fs stuff in fibers. Maybe the caching layer should be before the fiber is spawned? As in, it checks if the file is in the cache before spawning a fiber to read the file?

Interesting idea!

**Comment by abernix** [comment]
Suggested bug-fix candidate for this: PR #7982.

...because more command-line arguments and environment variables.

**Comment by tcastelli** [comment]
I'm having problems after updating to latest beta for 1.4.2.1 and can't start running because of missing meteor-deque. Could this be related to something else?


```
W20161101-13:37:04.687(1)? (STDERR) D:\Programming\webstorm_workspace\xxx\.meteor\local\build\programs\server\boot.js:348
W20161101-13:37:05.150(1)? (STDERR) }).run();
W20161101-13:37:05.154(1)? (STDERR)    ^
W20161101-13:37:05.159(1)? (STDERR)
W20161101-13:37:05.162(1)? (STDERR) Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
W20161101-13:37:05.168(1)? (STDERR)     at Object.require (D:\Programming\webstorm_workspace\xxx\.meteor\local\build\programs\server\boot.js:200:17)
W20161101-13:37:05.173(1)? (STDERR)     at packages\meteor.js:677:32
W20161101-13:37:05.176(1)? (STDERR)     at packages\meteor.js:846:4
W20161101-13:37:05.181(1)? (STDERR)     at packages\meteor.js:1380:3
W20161101-13:37:05.184(1)? (STDERR)     at D:\Programming\webstorm_workspace\xxx\.meteor\local\build\programs\server\boot.js:295:34
W20161101-13:37:05.190(1)? (STDERR)     at Array.forEach (native)
W20161101-13:37:05.194(1)? (STDERR)     at Function._.each._.forEach (C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.4.2-1-beta.0\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20161101-13:37:05.198(1)? (STDERR)     at D:\Programming\webstorm_workspace\xxx\.meteor\local\build\programs\server\boot.js:128:5
W20161101-13:37:05.205(1)? (STDERR)     at D:\Programming\webstorm_workspace\xxx\.meteor\local\build\programs\server\boot.js:344:5
W20161101-13:37:05.212(1)? (STDERR)     at Function.run (D:\Programming\webstorm_workspace\xxx\.meteor\local\build\programs\server\profile.js:480:12)
```

**Comment by veered** [comment]
I love seeing that green checkmark :)

**Comment by tcastelli** [comment]
Not sure if on purpose or still wip but I seems like last beta is not released for Windows 🐶 

> This project uses Meteor 1.4.2-beta.1, which isn't available on Windows. To work with this app on all supported
platforms, use meteor update --release METEOR@1.4.2 to pin this app to the newest Windows-compatible release.

**Comment by benjamn** [comment]
@tcastelli 1.4.2**.1**-beta.1?

**Comment by tcastelli** [comment]
Ugh I'm half asleep! Sorry about that, already downloading

P.S The worst part is that I typed it wrong 3 times 😆

**Comment by tcastelli** [comment]
Was getting same error about meteor-deque, did a meteor reset, meteor npm install babel-runtime --save and now the error is something about fibers. Gonna try to revert to old 1.4.1 to see if I messed around with something else 😕 
```
W20161103-04:10:43.381(1)? (STDERR) module.js:327
W20161103-04:10:43.383(1)? (STDERR)     throw err;
W20161103-04:10:43.384(1)? (STDERR)     ^
W20161103-04:10:43.385(1)? (STDERR)
W20161103-04:10:43.386(1)? (STDERR) Error: Cannot find module 'fibers'
W20161103-04:10:43.387(1)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20161103-04:10:43.388(1)? (STDERR)     at Function.Module._load (module.js:276:25)
W20161103-04:10:43.388(1)? (STDERR)     at Module.require (module.js:353:17)
W20161103-04:10:43.389(1)? (STDERR)     at require (internal/module.js:12:17)
W20161103-04:10:43.390(1)? (STDERR)     at Object.<anonymous> (D:\Programming\webstorm_workspace\spandlo\.meteor\local\build\programs\server\boot.js:1:75)
W20161103-04:10:43.394(1)? (STDERR)     at Module._compile (module.js:409:26)
W20161103-04:10:43.395(1)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20161103-04:10:43.396(1)? (STDERR)     at Module.load (module.js:343:32)
W20161103-04:10:43.397(1)? (STDERR)     at Function.Module._load (module.js:300:12)
W20161103-04:10:43.398(1)? (STDERR)     at Module.require (module.js:353:17)
=> Exited with code: 1

```

**Comment by benjamn** [comment]
Please help test the first release candidate!
```sh
cd path/to/some/test/app
meteor update --release 1.4.2.1-rc.0
meteor update --all-packages
meteor npm install --save babel-runtime
# etc. etc.
```

**Comment by mjmasn** [comment]
@benjamn can confirm deploy issue caused by #7974 is fixed so it's a thumbs up from me!

**Comment by pozylon** [comment]
@benjamn I see very fast refresh now, it seems like 1.4.2.1-rc.0 improved rebuild times even more. Is that possible? I don't see any issues at the moment trying server/client/api changes.

**Comment by tcastelli** [comment]
@pozylon there's a new "feature" that is now ON by defaults for disabling fibers from command-line operations. You must be getting the benefits of this new setup:

> File system operations performed by the command-line tool no longer use fibers unless the METEOR_DISABLE_FS_FIBERS environment variable is explicitly set to a falsy value. For larger apps, this change results in significant build performance improvements due to the creation of fewer fibers and the avoidance of unnecessary asyncronous delays. https://github.com/meteor/meteor/pull/7975/commits/ca4baed90ae0675e55c93976411d4ed91f12dd63

 (taken from https://github.com/meteor/meteor/blob/devel/History.md )

**Comment by brucejo75** [comment]
Any chance #7991 could be addressed?  Console debugging of Server side (Node) is toast with 1.4.2.
While at it take a look at #7977?

**Comment by djgagner** [comment]
reloading my massive app in 1/2 seconds with rc-1... now I can get rid of my plans to switch off of meteor in the long term :) (and hopefully ditch my expensive cloud servers we've been using to build)

**Comment by abernix** [comment]
I've been getting `rc.1` out into some test environments and I received this error in two different environments (same project):

* During a `meteor build` which was run on an environment where `node_modules` was copied over from a different platform (Mac => Ubuntu)
* When running a `meteor test --once --driver-package dispatch:mocha-phantomjs` in an environment which I _believe_ was purely Ubuntu (meaning, no Mac artifacts lying around)

I don't have a simple reproduction yet, so I guess just consider this food-for-thought at the moment:

```
Error: ENOENT: no such file or directory, lstat '/tmp/mt-jguafk/npm/node_modules/.bin/.meteor-portable'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at Object.wrapper (/tools/fs/files.js:1533:35)
    at files.(anonymous function) (/tools/fs/files.js:1634:27)
    at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:22:15)
    at Entry._reallyRecompute (/home/runner/.meteor/packages/meteor-tool/.1.4.2-1-rc.1.1v1va32++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/home/runner/.meteor/packages/meteor-tool/.1.4.2-1-rc.1.1v1va32++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/home/runner/.meteor/packages/meteor-tool/.1.4.2-1-rc.1.1v1va32++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/home/runner/.meteor/packages/meteor-tool/.1.4.2-1-rc.1.1v1va32++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at /tools/isobuild/builder.js:500:26
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:463:34)
    at /tools/isobuild/builder.js:545:13
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:463:34)
    at Builder.copyDirectory (/tools/isobuild/builder.js:584:5)
    at /tools/isobuild/isopack.js:1446:17
    at Function._.each._.forEach (/home/runner/.meteor/packages/meteor-tool/.1.4.2-1-rc.1.1v1va32++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /tools/isobuild/isopack.js:1445:9
    at Isopack.saveToPath (/tools/isobuild/isopack.js:1191:9)
    at [object Object]._saveIsopack (/tools/packaging/tropohouse.js:353:15)
    at /tools/packaging/tropohouse.js:526:16
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/packaging/tropohouse.js:515:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.download (/tools/packaging/tropohouse.js:427:20)
    at /tools/packaging/tropohouse.js:613:18
    at /tools/utils/buildmessage.js:572:21
    at /home/runner/.meteor/packages/meteor-tool/.1.4.2-1-rc.1.1v1va32++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:32:39
 => awaited here:
    at Promise.await (/home/runner/.meteor/packages/meteor-tool/.1.4.2-1-rc.1.1v1va32++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:39:12)
    at Object.forkJoin (/tools/utils/buildmessage.js:604:6)
    at [object Object].downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:609:18)
    at /tools/project-context.js:776:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:775:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:774:13)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/runners/run-app.js:549:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:548:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:617:35)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

**Comment by benjamn** [comment]
@abernix I believe I can make that code a bit more defensive. There shouldn't ever be a `.meteor-portable` file in a `node_modules/.bin` directory, so it should be fine to avoid copying the non-existent file.

**Comment by benjamn** [comment]
I'm currently publishing `METEOR@1.4.2.1-rc.2` just to make sure tests pass one last time, then will do some manual QA before publishing `METEOR@1.4.2.1`.

In other words, now's the time to flag any issues you believe can't wait for 1.4.3 :)

**Comment by abernix** [comment]
The only other issue which appears to me to have been a regression in 1.4.2 (so nice-to-fix-in-1.4.2.1 and a candidate for bringing to the table) would be #7999. Unless it screams out as a problem to you, @benjamn, given the suggested work-around (which I believe would work) it may be fine to wait.

Anything else that has been suggested I believe is feature-related and not ideal for a patch release.  This is a pretty nice release overall, as is.

**Comment by abernix** [comment]
I can confirm that https://github.com/meteor/meteor/pull/7975/commits/a7ac32e00a87384956fdf65dfdf2198c98d73d6f fixes the issue with `.meteor-portable` not existing in `node_modules/.bin` directories during tests.

**Comment by klaussner** [comment]
An issue that was introduced in 1.4.2 is that (in some cases) new modules cannot be imported. Someone posted about this on the forums: https://forums.meteor.com/t/meteor-not-detecting-new-files/31151. I could reproduce the error by just following the `simple-todos` tutorial until step 2.4 where `/imports/ui/body.js` is imported.

Another manifestation of the problem: new `.less` files (maybe `.scss` files, too) that are created while `meteor` is running are sometimes not included in the final bundle if they are imported from a JavaScript file. See https://github.com/klaussner/meteor-css-issue for a reproduction.

**Comment by Akryum** [comment]
This happens with `.vue` files too since 1.4.2, that throw a file not found error when they are created while meteor is running.

**Comment by mitar** [comment]
Possibly related: https://github.com/meteor/blaze/issues/150

**Comment by benjamn** [comment]
I remember trying and failing to reproduce #8008, though I believe this problem is real.

Am I correct in understanding that everything works if Meteor is fully restarted? And that there are no problems with modifications to existing `.less` etc. files?

**Comment by klaussner** [comment]
@benjamn Yes, restarting Meteor helped in both cases. Editing existing files seems to work as well.

**Comment by Akryum** [comment]
@benjamn Yes, the `.vue` files are successfully compiled and imported in other files when meteor is fully restarted.
