### ISSUE TITLE
[rspack] Cannot find module 'cac' or its corresponding type declarations

### ISSUE THREAD

**Issue by italojs** [meteor/meteor#14057]
While uncommenting the typescript test back (+ a few changes), I started to get a rspack issue:

``` 
running (9/10) typescript.js test:typescript template works ...
Extra junk is : node_modules/@rspack/cli/dist/cli.d.ts(2,26): error TS2307: Cannot find module 'cac' or its corresponding type declarations.
node_modules/@rspack/cli/dist/utils/options.d.ts(1,30): error TS2307: Cannot find module 'cac' or its corresponding type declarations.
```

To reproduce the issue:

1. Uncomment and address the changes in this test

``` js
// .../meteor/tools/tests/typescript.js
selftest.define("typescript template works", async function () {
  const s = new Sandbox; 
  await s.init();

  let run = s.run("create", "--typescript", "typescript");

  run.waitSecs(60);
  await run.match("Created a new Meteor app in 'typescript'.");
  await run.match("To run your new app");

  s.cd("typescript");

  run = s.run("npm", "install");
  await run.expectExit(0);

  run = s.run("lint");
  run.waitSecs(60);
  await run.match("[zodern:types] Exiting \"meteor lint\" early");
  await run.expectExit(0);

  run = s.run("npx", "tsc");
  run.waitSecs(60);
  await run.expectEnd();
  await run.expectExit(0);
});
```

2. so run `meteor self-test` 

2.1 or if you want to be closer from CI
```
TEST_GROUP=$(
  { cat ./tmp/test-groups/10.txt 2>/dev/null \
    || cat ./tmp/test-groups/0.txt 2>/dev/null \
    || printf '^[t-z]'; } | tr -d '\r\n'
) \
&& echo "$TEST_GROUP" \
&& { [[ -n ${PRE_TEST_COMMANDS:-} ]] && eval "${PRE_TEST_COMMANDS}"; :; } \
&& ./meteor self-test "$TEST_GROUP" \
  --retries "${METEOR_SELF_TEST_RETRIES:-0}" \
  --exclude "${SELF_TEST_EXCLUDE:-}" \
  --headless \
  --junit ./tmp/results/junit/10.xml \
  --without-tag "custom-warehouse"
``` 

This Test was introduced in the PR https://github.com/meteor/meteor/pull/12934

**Comment by thenileshmishra** [comment]
Root cause identified:
@rspack/cli ships .d.ts files importing `cac`, which is listed as a devDependency and therefore not installed.
TypeScript checks node_modules .d.ts by default, causing TS2307.

Fix proposed in PR #14094 
- Enable `skipLibCheck` in the TypeScript template tsconfig
- Matches TypeScript team recommendations and modern scaffolding tools

Please review.
