### ISSUE TITLE
Fibers is missing binaries; can do away with fork

### ISSUE THREAD

**Issue by GeoffreyBooth** [meteor/meteor#11791]
@renanccastro I just wanted to draw your attention to https://github.com/laverdet/node-fibers/pull/454#issuecomment-981142332: you can take over the original Fibers project. I think this would be preferable to maintaining a separate fork.

In addition, the version of the Fibers fork for Meteor 2.5.1 was missing some binaries that the original version usually included when it was published to npm. In particular, the only ones in the fork are `darwin-x64-93` and `linux-x64-72-glibc`. The original library publishes all of these: `darwin-x64-72`, `darwin-x64-83`, `darwin-x64-93`, `linux-x64-72-glibc`, `linux-x64-72-musl`, `linux-x64-83-glibc`, `linux-x64-83-musl`, `win32-x64-72`, `win32-x64-83`. (You can see this by running `npm install fibers` in a new project and looking in `node_modules/fibers/bin`.) [My project is broken without the musl binary that is needed to run in Alpine.](https://github.com/disney/meteor-base/pull/95#issuecomment-974765661)

So if you don’t mind, I suggest you accept the offer in https://github.com/laverdet/node-fibers/pull/454 to take over the original Fibers repo and merge in the PRs that necessitated the fork, and publish a new version to NPM that includes the full set of binaries. Instructions on how to generate them are [here](https://github.com/laverdet/node-fibers/pull/454#issuecomment-981142332). Thanks!

**Comment by renanccastro** [comment]
Hi @GeoffreyBooth , I'm following up with laverdet for having npm push permissions there. As soon as we have it, we will publish a new version with all the binaries.

Sorry for this, adding the other architectures went through me, as fibers can always be compiled this wouldn't be a fatal exception in our flow (except on alpine). I will correct this in the new fibers version.

**Comment by simplecommerce** [comment]
@renanccastro Does the [2.5.2 beta 10](https://github.com/meteor/meteor/pull/11788#issuecomment-998303564) release include this new fibers version with all binairies? I am asking because in my current project, I cannot update to latest version of Meteor on Azure (windows web app) as I can't install any fibers version above 4.0.2 because of missing binairies. I don't mind waiting, I was just curious, since I am not sure how to check.

Thanks!

**Comment by renanccastro** [comment]
@simplecommerce no, not yet, unfortunately. There is still some CI work to be done for this to be possible

**Comment by nspangler** [comment]
@renanccastro we are also unable to push to our production endpoint because of this issue. We upgraded our application's meteor version to take advantage of this fix https://github.com/mui-org/material-ui/issues/29131

**Comment by diavrank** [comment]
Hi, is there any ETA for this fix? We stuck on **v2.4** due to this issue. There are many users who use the docker image from [Disney](https://github.com/disney/meteor-base) to deploy their meteor apps, so, I think this is urgent.

**Comment by renanccastro** [comment]
I will be starting the work to release a new fibers version with common pre-built binaries this week. I will let you guys know the status here.

For now, the major uplift will be to migrate node-fibers to use node-pre-gyp so we can have a distribution pipeline instead of doing it manually.

**Comment by simplecommerce** [comment]
@renanccastro Does this mean that in order for it to work we need to be able to build/compile using node-pre-gyp? I ask because in my current environment I can't since its a VM with restricted access and no admin rights.

**Comment by renanccastro** [comment]
> @renanccastro Does this mean that in order for it to work we need to be able to build/compile using node-pre-gyp? I ask because in my current environment I can't since its a VM with restricted access and no admin rights.

No, we will use node-pre-gyp to organize the library release process. If your architecture is targeted by our shipped binaries you won't need to build it.

**Comment by renanccastro** [comment]
Hello everyone.
I've just released meteor 2.5.6 with fibers 5.0.1, which do include the binaries.

You can check more details here: https://github.com/meteor/meteor/pull/11872

Can you please give it a try and let me know how it goes? Thanks.

@simplecommerce @GeoffreyBooth @diavrank @nspangler

**Comment by diavrank** [comment]
Thank you @renanccastro , can we have a beta for this release? (in order to do the tests with CI tools)

**Comment by simplecommerce** [comment]
@renanccastro I did a quick test on a project and it seemed to work. Then I did a test on an existing live project and for some reason it keeps failing. And in my logs I see 

`Error: Cannot find module '@meteorjs/reify/lib/runtime'`

So I tried to `npm install` in the `programs/server` folder and get the same compile error for the fibers.
Any ideas?

For the moment I am reverting to 1.9.2 until I can be sure it works for my live site.

**Comment by renanccastro** [comment]
@simplecommerce 1.9.2 is very behind compared with 2.5 on fibers version. Have you tried to do an incremental update to identify exactly which version breaks in your system?
I've shipped the same binaries on 2.5 as the previous version, so no regressions are expected here.

**Comment by simplecommerce** [comment]
@renanccastro if you mean for fibers, anything above 3.0.2 I believe breaks for me, I am on a windows architecture with no admin rights so my instance can't use node-pre-gyp to compile the binaries if they are missing. I kept 1.9.2 of meteor with the 3.0.2 on my current sites because it was the only working version for me at the moment. I am going to try more testing of Meteor 2.5.6 on a test server to see if I can figure out why its breaking on the live and not on my test.

**Comment by simplecommerce** [comment]
@renanccastro ok, it was my mistake, I didn't notice my test site was redirecting to my live site that is why I was thinking it was working, but it is not on my end, here is what I get when I try `npm install` in the `programs/server` after updating to 2.5.6

```
\programs\server> npm install
[37;40mnpm [30;43mWARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> fibers@5.0.1 install D:\home\site\wwwroot\programs\server\node_modules\fibers
> node build.js || nodejs build.js


D:\home\site\wwwroot\programs\server\node_modules\fibers>if not defined npm_config_node_gyp (node "D:\Program Files (x86)\npm\6.14.15\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "D:\Program Files (x86)\npm\6.14.15\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(365,5): warning MSB8003: Could not find VCInstallDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [D:\home\site\wwwroot\programs\server\node_modules\fibers\build\fibers.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\home\site\wwwroot\programs\server\node_modules\fibers\build\fibers.vcxproj]
  
  
gyp ERR! build error 
gyp ERR! stack Error: `D:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files (x86)\npm\6.14.15\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files (x86)\\nodejs\\14.18.1\\node.exe" "D:\\Program Files (x86)\\npm\\6.14.15\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\home\site\wwwroot\programs\server\node_modules\fibers
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
[37;40mnpm [31;40mERR! code ELIFECYCLE
[37;40mnpm [31;40mERR! errno 1
[37;40mnpm [31;40mERR! fibers@5.0.1 install: `node build.js || nodejs build.js`
[37;40mnpm [31;40mERR! Exit status 1
[37;40mnpm [31;40mERR! 
[37;40mnpm [31;40mERR! Failed at the fibers@5.0.1 install script.
[37;40mnpm [31;40mERR! This is probably not a problem with npm. There is likely additional logging output above.

[37;40mnpm [31;40mERR! A complete log of this run can be found in:
[37;40mnpm [31;40mERR!     D:\local\Temp\monacositeextension\temp\_logs\2022-01-26T14_13_17_026Z-debug.log
\programs\server> 
```

**Comment by renanccastro** [comment]
What is your windows version @simplecommerce ? It seems you don't have the development tools to build it, and we don't have a pre-built binary for your version.

You can follow the instructions here: https://github.com/nodejs/node-gyp to set up the required toolchain to build it.

**Comment by simplecommerce** [comment]
@renanccastro its an Azure Web App running windows environment `OS version: Microsoft Windows NT 10.0.14393.0` 
 and it doesn't support or allow me to install the build tools in order to compile the missing binaries. That's why I was hoping it would be made available in the latest 5.0.1 release with Meteor 2.5.6. Otherwise my only solution is to manually build it on my local PC and upload it every time there is a new release of fibers in your Meteor package.
