### ISSUE TITLE
1.3.3 / 1.3.3.1 update broke Angular service, module.export is not a function

### ISSUE THREAD

**Issue by walliski** [meteor/meteor#7260]
Just started working with Meteor a week back, and so far I am very pleased with it. However with the new update I am getting the following error for my app when I update it to 1.3.3 or 1.3.3.1.

```
TypeError: module.export is not a function
```

The service, error thrown on last line:

From dev console:
```javascript
var KanbanGridService = function () {                                                                                  //
    function KanbanGridService($q) {                                                                                   // 5
        _classCallCheck(this, KanbanGridService);                                                                      // 5
                                                                                                                       //
        this.q = $q;                                                                                                   // 6
    }                                                                                                                  // 7
                                                                                                                       //
    KanbanGridService.prototype.getNotebooks = function () {                                                           //
        function getNotebooks() {                                                                                      //
            var deferred = this.q.defer();                                                                             // 10
            Meteor.call('getNotebooks', function (err, result) {                                                       // 11
                if (err) {                                                                                             // 12
                    deferred.reject(err);                                                                              // 13
                    return;                                                                                            // 14
                }                                                                                                      // 15
                                                                                                                       //
                deferred.resolve(result);                                                                              // 17
            });                                                                                                        // 18
            return deferred.promise;                                                                                   // 19
        }                                                                                                              // 20
                                                                                                                       //
        return getNotebooks;                                                                                           //
    }();                                                                                                               //
                                                                                                                       //
    return KanbanGridService;                                                                                          //
}();                                                                                                                   //
                                                                                                                       //
var module = angular.module('kanbanServices', []);                                                                     // 23
module.export("default",exports.default=(module.service('kanbangridService', ['$q', KanbanGridService])));             // 24
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
```

Sourcecode:
```javascript
import angular from 'angular';
import 'angular-meteor';

class KanbanGridService {
    constructor($q){
        this.q = $q;
    }

    getNotebooks() {
        var deferred = this.q.defer();
        Meteor.call('getNotebooks', (err, result)=> {
            if (err) {
                deferred.reject(err);
                return;
            }

            deferred.resolve(result);
        });
        return deferred.promise;
    }
}

var module = angular.module('kanbanServices', []);
export default module.service('kanbangridService',  ['$q', KanbanGridService]);
```

Package list:
```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

angular-templates
wiseguyeh:accounts-azure-active-directory
twbs:bootstrap@4.0.0-alpha2
seba:minifiers-autoprefixer
fourseven:scss
velocity:html-reporter
practicalmeteor:mocha
fortawesome:fontawesome
accounts-password
dotansimha:accounts-ui-angular
walliski:azure-resource-onenote
```

**Comment by walliski** [comment]
Apparently switching out `ecmascript` to `pbastowski:angular-babel` solves this problem.
