### ISSUE TITLE
import { Template } from 'meteor/templating' not working with meteor 1.6.0.1

### ISSUE THREAD

**Issue by hacknlove** [meteor/meteor#9570]
If you do `import { Template } from 'meteor/templating'` `Template` will be `undefined`

Everything works fine if you do not import Template, so there is no much trouble.

Anyway, this brakes [some meteor tutorials like one](https://www.meteor.com/tutorials/blaze/templates#definingviewswithtemplates)

```javascript
import { Template } from 'meteor/templating';
 
import './body.html';
 
Template.body.helpers({
  tasks: [
    { text: 'This is task 1' },
    { text: 'This is task 2' },
    { text: 'This is task 3' },
  ],
});
```

**Comment by jamesmillerburgess** [comment]
I can confirm this doesn't work, and if you try to run the tutorial as @hacknlove said, it doesn't like the html import.

```
 Error: Cannot find module './body.html'
     at makeMissingError (packages/modules-runtime.js:231:12)
     at require (packages/modules-runtime.js:241:19)
     at body.js (imports/body.js:1:98)
     at fileEvaluate (packages/modules-runtime.js:343:9)
     at require (packages/modules-runtime.js:238:16)
     at main.js (main.js:1:14)
     at fileEvaluate (packages/modules-runtime.js:343:9)
     at require (packages/modules-runtime.js:238:16)
```

Changing the Meteor release as far back as 1.4 didn't help, and neither did changing the `blaze-html-templates` package version.

We should probably add some regression tests to make sure that tutorials stay in a working state. I'd be willing to help with that!

**Comment by hwillson** [comment]
Hi guys - it's working for me? See: https://github.com/hwillson/meteor-issue-9570. There must be something else happening. @hacknlove, any chance you could put together a small reproduction showing this issue? Also, we like to reserve issues in this repo for bugs with Meteor itself. Please re-open this over in https://github.com/meteor/tutorials as needed.

@jamesmillerburgess Help on the tutorials is always welcome! Just a heads up though, the meteor.com tutorials are a bit of a challenge to work on in their current state. To make changes, you sometimes have to update 3 separate repos (e.g. https://github.com/meteor/simple-todos-react, https://github.com/meteor/tutorials and https://github.com/meteor/tutorial-viewer), all of which involve submodules. Each code step lines up with a commit, so whenever a code step needs to be updated, you have to edit a specific commit and rebase. This makes it really difficult to accept PR's for example, since PR's are usually submitted against the tutorial repo as of its last commit. Since the tutorial code steps progressively change however, that means submitting a PR to fix an earlier code step can't really be directly applied - it has to be added manually. Long story short, we started working on a better approach for all of this a while back, but that work has been put on pause for a bit. I'm planning on blowing the dust of it again soon, so I'll definitely keep you posted when that happens - thanks!

**Comment by jamesmillerburgess** [comment]
@hacknlove 😅 I think we both made the same mistake!

Please check that your `main.js` file is in `/client` otherwise it will be trying to run on both the client and server.

**Comment by hacknlove** [comment]
I find out that it is caused by ostrio:flow-router-extra
[templating.tar.gz](https://github.com/meteor/meteor/files/1673088/templating.tar.gz)

If I remove ostrio:flow-router-extra, I can import Template

I should move this bug to that repo
