### ISSUE TITLE
[1.3] Testing issues

### ISSUE THREAD

**Issue by Sabst** [meteor/meteor#6678]
Looks like an FAQ but could not find the answer elsewhere...

This is with Meteor 1.3 on linux.

I followed the instructions of the [testing guide](https://github.com/meteor/guide/blob/testing-modules-content/content/testing.md#full-app-integration-test) with my app and had a number of problems.

I tried with the [**todos app**](https://github.com/meteor/todos/tree/react) (**react branch**) and had exactly the same problems... so it must be easy to reproduce.
Basically, assertions fail but 0 errors are reported:
`meteor test --once --driver-package dispatch:mocha-phantomjs`

```
Exception from Tracker recompute function:
AssertionError: expected undefined to be a function

```
```
--------------------------------
SERVER FAILURES: 0
CLIENT FAILURES: 0
--------------------------------
```

Full-app tests:
`meteor test --once --full-app --driver-package dispatch:mocha-phantomjs`
`Error: Cannot find module 'meteor/kadira:flow-router'` (this router is clearly not used in the project)
```
--------------------------------
SERVER FAILURES: 0
CLIENT FAILURES: 0
--------------------------------
```
Also, there is no indication of the file name and line where the tests fail.

**Comment by stubailo** [comment]
Are you sure that the `dispatch:mocha-phantomjs` package is built to work with Meteor 1.3 testing? With the new `meteor test` command, test drivers that previously worked for package testing need to be updated to also work with app testing. Might be worth filing an issue on that package, or having a discussion with those package authors.

**Comment by Sabst** [comment]
Let's focus on full app testing.

Maybe those lines (as of 4/5/2016) will make the point clearer:
https://github.com/meteor/todos/blob/react/imports/startup/client/routes.app-test.js#L6
https://github.com/meteor/todos/blob/react/package.json#L18

As you see, there is a wrong reference in the test to kadira:flow-router (not a package of the project).
This is silently ignored and all tests are ok (!).
Maybe the tests status is based on assertions only and not on other issues like compilation errors.

Here is a small reproducer that I named `fail.app-tests.js` in `imports/startup/client` (still in todos project/react branch):
```
/* eslint-env mocha */

// Uncomment the following line to see the issue (all tests will pass!)
//import { Whatever } from 'meteor/whatever';

import { chai, assert } from 'meteor/practicalmeteor:chai';

describe('Obvious failure test', () => {
  it('This is false', () => {
    assert.isTrue(false);
  });
});
```

**Comment by stubailo** [comment]
Oh, yes I would believe that the tests in the React version are broken because they are often just lifted from the Blaze version of the app. @tmeasday

**Comment by stubailo** [comment]
Oh, I see what you're saying, the test file is not even being loaded at all. Tom, something to take a look at.

**Comment by tmeasday** [comment]
Moving this to meteor/todos

**Comment by Sabst** [comment]
Getting rid of the test (or fixing it) will not solve the root cause problem with meteor testing.
Using the todos project is just an example of a bug in the testing environment.
All failing tests must be reported and this is not the case with the issue reported above.

Maybe that will be clearer with a more complete example session using the todos/react project.
By the way, the result is the same with 1.3 and 1.3.1.

**1- Valid behavior: errors are detected and reported:**
With `// import { Whatever }...` in the reproducer above.
`meteor test --once --full-app --driver-package practicalmeteor:mocha`
Result:
```
passes: 0 failures: 2 duration: 0.17s
Obvious failure test
This is false ‣
AssertionError: expected false to be true
    at Assertion.<anonymous> (http://localhost:3000/packages/practicalmeteor_chai.js?hash=8fb9a4aa7055fa02f8b35e05fb1f05c8787c8a46:1231:10)
    at Assertion.Object.defineProperty.get (http://localhost:3000/packages/practicalmeteor_chai.js?hash=8fb9a4aa7055fa02f8b35e05fb1f05c8787c8a46:4095:29)
    at Function.assert.isTrue (http://localhost:3000/packages/practicalmeteor_chai.js?hash=8fb9a4aa7055fa02f8b35e05fb1f05c8787c8a46:2793:31)
    at Context.<anonymous> (http://localhost:3000/app/app.js?hash=b190251751ee9e0da959e05a482034c3803aed38:844:33)
    at callFn (http://localhost:3000/packages/practicalmeteor_mocha.js?hash=81215895bcf916ea0cbd4f49d1218662f8ea051e:5141:25)
    at Test.Runnable.run (http://localhost:3000/packages/practicalmeteor_mocha.js?hash=81215895bcf916ea0cbd4f49d1218662f8ea051e:5134:11)
    at Runner.runTest (http://localhost:3000/packages/practicalmeteor_mocha.js?hash=81215895bcf916ea0cbd4f49d1218662f8ea051e:5529:14)
    at http://localhost:3000/packages/practicalmeteor_mocha.js?hash=81215895bcf916ea0cbd4f49d1218662f8ea051e:5606:16
    at next (http://localhost:3000/packages/practicalmeteor_mocha.js?hash=81215895bcf916ea0cbd4f49d1218662f8ea051e:5453:18)
    at http://localhost:3000/packages/practicalmeteor_mocha.js?hash=81215895bcf916ea0cbd4f49d1218662f8ea051e:5463:11
data available when routed
when logged out
"before each" hook ‣
ReferenceError: FlowRouter is not defined
    at http://localhost:3000/app/app.js?hash=b190251751ee9e0da959e05a482034c3803aed38:905:16
    at tryCallOne (http://localhost:3000/packages/promise.js?hash=76f9fa05244092de9aa9eb2b32e81d4c7cb48166:200:12)
    at http://localhost:3000/packages/promise.js?hash=76f9fa05244092de9aa9eb2b32e81d4c7cb48166:286:15
    at Object.flush (http://localhost:3000/packages/promise.js?hash=76f9fa05244092de9aa9eb2b32e81d4c7cb48166:820:29)
    at onGlobalMessage (http://localhost:3000/packages/meteor.
```

Two errors have been detected and reported... this is correct.

**2- Bug: error is ignored, all subsequent tests are ignored, final status is success**
With `import { Whatever }...` in the reproducer above (the comment has been removed).
`meteor test --once --full-app --driver-package practicalmeteor:mocha`
Result:
passes: 0 failures: 0 duration: 0s

This is a bug: no error is reported (there are 2 errors still!), wrong number of passing/failing tests

**Comment by tmeasday** [comment]
Hi @Sabst 

I assume in your command line you mean `--driver dispatch:mocha-phantomjs` ?

The issue here is a client error that is not being picked up by the phantomjs script in that package. I'd suggest opening an issue over at https://github.com/DispatchMe/meteor-phantomjs-tests

What happens if you introduce a similar failure in a server file?

**Comment by Sabst** [comment]
Can be either mocha or phantomjs, same problem just reported differently (I should have mentioned I switched back to mocha to avoid the doubt on phantomjs).

Now the server behavior is different as the compilation fails and prevents the test from returning any status.
So server-side is correct since a failure does not appear as a success.

On the client-side, it looks like an exception or error status (as shown in my first post) is ignored at some point during the test.

**Comment by tmeasday** [comment]
> On the client-side, it looks like an exception or error status (as shown in my first post) is ignored at some point during the test.

The way bundling works in development in Meteor means that a client side error at the top level may just kill the single package in development that it is in and not necessary stop the whole Meteor application from running. I'm not really sure there is much we can do about this? 

I suppose the various test drivers could listen to `window.onerror` or something? Honestly I'm not sure what the best pattern is there. If your tests files don't run properly I'd hope you'd notice earlier than in automated testing (i.e. you'd very quickly notice the mistake as you developed the test).
