### ISSUE TITLE
Build that works with 1.3-beta.11 fails with 1.3-rc3

### ISSUE THREAD

**Issue by hluz** [meteor/meteor#6540]
**Issue**

When using npm activedirectory package (installed via _npm install activedirectory --save_) with Meteor 1.3-rc3 on Mac OS X 10.11.3, running Meteor fails to start the server with following messages:

```
=> Started MongoDB.                           
=> Exited from signal: SIGTRAP                
W20160319-17:37:58.560(11)? (STDERR) dyld: lazy symbol binding failed: Symbol not found: _node_module_register
W20160319-17:37:58.561(11)? (STDERR)   Referenced from: /dyld/node_modules/activedirectory/node_modules/ldapjs/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node
W20160319-17:37:58.561(11)? (STDERR)   Expected in: dynamic lookup
W20160319-17:37:58.561(11)? (STDERR)          
W20160319-17:37:58.561(11)? (STDERR) dyld: Symbol not found: _node_module_register
W20160319-17:37:58.561(11)? (STDERR)   Referenced from: /dyld/node_modules/activedirectory/node_modules/ldapjs/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node
W20160319-17:37:58.561(11)? (STDERR)   Expected in: dynamic lookup
W20160319-17:37:58.561(11)? (STDERR)
```

Using Meteor 1.3-beta.11 it works fine.

**Reproduction**

Minimal repro showing the problem: https://github.com/hluz/dyld

**Comment by hluz** [comment]
It appears to be a npm version issue.

using ```meteor npm install``` instead of ```npm install``` resolves the issue.
