### ISSUE TITLE
[1.2.1] coffeescript not working in app

### ISSUE THREAD

**Issue by xvendo** [meteor/meteor#7405]
Meteor Version: 1.2.1

Changes to your project's package version selections:
                                              
aldeed:simple-schema  added, version 1.3.3    
amplify               added, version 1.0.0
cfs:http-methods      added, version 0.0.32
coffeescript          added, version 1.0.11
meteorspark:util      added, version 0.2.0
raix:eventemitter     added, version 0.1.3
tap:i18n              added, version 1.8.2
tap:i18n-ui           added, version 0.8.0

   Loading plugin `compileCoffeescript` ...  -
/home/paul/.meteor/packages/coffeescript/.1.0.11.1ozocbx++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/compileCoffeescript/node_modules/source-map/lib/source-map/source-node.js:103
      0                                         lastGeneratedColumn);
                                                ^^^^^^^^^^^^^^^^^^^
=> Errors prevented startup:                  
   
   While building for web.browser:
   error: no plugin found for lib/tap_i18n/tap_i18n-helpers.coffee in tap:i18n; a plugin for *.coffee was active when it was published but none is now
   error: no plugin found for lib/tap_i18n/tap_i18n-common.coffee in tap:i18n; a plugin for *.coffee was active when it was published but none is now
   error: no plugin found for lib/tap_i18n/tap_i18n-client.coffee in tap:i18n; a plugin for *.coffee was active when it was published but none is now
   error: no plugin found for lib/tap_i18n/tap_i18n-init.coffee in tap:i18n; a plugin for *.coffee was active when it was published but none is now
   error: no plugin found for i18n_ui_amplify.coffee in tap:i18n-ui; a plugin for *.coffee was active when it was published but none is now
   error: no plugin found for i18n_ui_client_helpers.coffee in tap:i18n-ui; a plugin for *.coffee was active when it was published but none is now
   error: no plugin found for frameworks/i18n_ui_bootstrap.coffee in tap:i18n-ui; a plugin for *.coffee was active when it was published but none is now
   error: no plugin found for frameworks/i18n_ui_semantic.coffee in tap:i18n-ui; a plugin for *.coffee was active when it was published but none is now
   
   While loading plugin `compileCoffeescript` from package `coffeescript`:
   module.js:439:25: Unexpected identifier
   at Module._compile (module.js:439:25)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (/home/paul/.meteor/packages/coffeescript/.1.0.11.1ozocbx++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/compileCoffeescript/node_modules/source-map/lib/source-map.js:8:22)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object._.extend.Npm.require (/tools/isobuild/bundler.js:1324:22)
   at Package (plugin/compile-coffeescript.js:1:23)
   at <runJavaScript-103>:227:4
   at <runJavaScript-103>:234:3
   
   
   While building for os.linux.x86_32:
   error: no plugin found for lib/tap_i18n/tap_i18n-helpers.coffee in tap:i18n; a plugin for *.coffee was active when it was published but none is now
   error: no plugin found for lib/tap_i18n/tap_i18n-common.coffee in tap:i18n; a plugin for *.coffee was active when it was published but none is now
   error: no plugin found for lib/tap_i18n/tap_i18n-server.coffee in tap:i18n; a plugin for *.coffee was active when it was published but none is now
   error: no plugin found for lib/tap_i18n/tap_i18n-init.coffee in tap:i18n; a plugin for *.coffee was active when it was published but none is now

Upgrading to Meteor 1.3.x solved this issue. But 1.2.1 won't work anymore.

**Comment by abernix** [comment]
I just created a new project with Meteor 1.2.1 and `coffeescript` and it worked properly:

```sh
$ meteor create meteor-issue-7405 --release 1.2.1
meteor-issue-7405/ $ cd meteor-issue-7405
$ meteor add coffeescript
$ echo 'console.log "coffee!" > test.coffee
$ meteor
...
=> App running at: http://localhost:3000/
...
I20160714-13:51:49.624(3)? coffee!
^C
$
```
Maybe try deleting your cached `coffeescript` package and letting Meteor reinstall it on the next run?

    rm -rf ~/.meteor/packages/coffeescript

Otherwise, please provide a more complete reproduction using the guideline for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor).

**Comment by xvendo** [comment]
Can you try adding tap:i18n package. 

Question: Is there a dev_bundle folder inside .meteor directory?

**Comment by abernix** [comment]
> Can you try adding tap:i18n package.

Still works fine.

> Question: Is there a dev_bundle folder inside .meteor directory?

Yes, the newer version of the `meteor` tool uses this to point to the correct dev bundle, even with older projects.

Please try reproducing the problem yourself and seeing if you have the same results with my commands above.

**Comment by xvendo** [comment]
I did the same as you did. The only thing I can think of is the OS. I am using Ubuntu 16.04. If you say that might be in hand of the OS version, I will setup Ubuntu 14.04 to see what happens there. Thanks.

**Comment by abernix** [comment]
Also works fine for me on Ubuntu 16.04 LTS:

```sh
ubuntu:~/Dev/meteor-issue-7405$ cat .meteor/release
METEOR@1.2.1
ubuntu:~/Dev/meteor-issue-7405$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
ubuntu:~/Dev/meteor-issue-7405$ cat test.coffee
console.log "coffee!"
ubuntu:~/Dev/meteor-issue-7405$ meteor
[[[[[ ~/Dev/meteor-issue-7405 ]]]]]

=> Started proxy.

=> Meteor 1.3: ES2015 modules, npm integration, app testing, mobile
improvements, and more.

This release is being downloaded in the background. Update your app to
Meteor 1.3 by running 'meteor update'.

=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
I20160714-11:55:44.409(0)? coffee!
^C
ubuntu:~/Dev/meteor-issue-7405$
```


You might want to try a fresh install of Meteor?:

    curl https://install.meteor.com/ | sh

**Comment by xvendo** [comment]
I did a fresh install. Ok now I have to go in depth of the problem. It will take some time, but I hope I will have a result by the end of the day.

**Comment by abernix** [comment]
Where does your `.meteor/dev_bundle` symlink point to?

**Comment by xvendo** [comment]
/home/paul/.meteor/packages/meteor-tool/.1.3.4_4.1srtql++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle

**Comment by xvendo** [comment]
Should there not an tool for 1.2.1? I only can find two meteor tools inside meteor-tool folder:
1.1.10  1.3.4_4

Is this correct using 1.3.4_4 when using meteor --release 1.2.1?

**Comment by abernix** [comment]
Hmm, I'm on 64-bit Ubuntu, and don't have 32-bit available to test on.  It could be that there isn't a package published for 32-bit somewhere.

**Comment by xvendo** [comment]
But when I am upgrading to 1.3.4 the error will disappear. Only when I do meteor --release 1.2.1 it comes to the trouble.

**Comment by xvendo** [comment]
I've got it! It's working now. I solved this issue in not using curl https://install.meteor.com/ | sh.
Instead I am copying the shell script to my local machine. 

Then inside the script change the release:

```
# This always does a clean install of the latest version of Meteor into your
# ~/.meteor, replacing whatever is already there. (~/.meteor is only a cache of
# packages and package metadata; no personal persistent data is stored there.)

RELEASE="1.3.4.4"

```
That will also prevent having a dev_bundle symlink. So 100 % sure now the problem resides at the new way of installation and can be found inside the shell script.

Hope that helps!

**Comment by abernix** [comment]
So, you changed the RELEASE to 1.2.1 and then ran it?  This would have installed the bootstrap of Meteor 1.2.1, but left you locked into the older `meteor-tool` as well.  You could still encounter this problem again as Meteor tries to auto-update it's tool.   It still doesn't really explain why the same configuration (with the `dev_bundle` symlink to the same place, except the 32-bit path), worked fine for me.

Regarding only having 1.1.10 and 1.3.3_4, that's because the Meteor release version wasn't always directly tied to the version of the `meteor-tool` (which is merely a component of the Meteor project).  Meteor 1.2.1 was actually using version 1.1.0 of the `meteor-tool`.

Even though it was working fine for me, I'm actually not sure if the `dev_bundle` symlink should have been pointing to the `1.3.4_4.1` version of the `meteor-tool`.  I will check into that and see if I can find an answer. 😄

**Comment by xvendo** [comment]
The problem is the dev_bundle linking to the wrong meteor-tool. I am not 100 % sure, but when I am using the 1.2.1 installer then the error will disappear and meteor can start. I never had troubles with auto update using 1.2.1. But maybe this is all due to a architecture change. Hope you can clarify. I will have a eye on it.

**Comment by abernix** [comment]
You might be right.  What happens if you go back to 1.3.4.4 (and get it all broken again) and then manually symlink to the 1.1.10 `dev_bundle` what happens?  Basically, run this in your project root directory:

_(I crafted this path by hand, but I believe it to be right for your configuration/arch)_

    ln -sf /home/paul/.meteor/packages/meteor-tool/1.1.10/mt-os.linux.x86_32/dev_bundle .meteor/dev_bundle

**Comment by abernix** [comment]
I _believe_ this will be fixed by Meteor 1.3.5: #7407

**Comment by benjamn** [comment]
This is exactly the bug that 1.3.5.1 fixes (not fixed in 1.3.5).

**Comment by xvendo** [comment]
OK. I changed my operating system to 64bit.

**Comment by abernix** [comment]
Meteor 1.3.5.1 is officially out.  I would highly recommend installing it as it should resolve the `dev_bundle` link problem you were having.  You can upgrade an existing project by using:

    meteor update --release 1.3.5.1

If you can't do that, I would strongly recommend at least creating temp project using this new version of Meteor to ensure that you have the tool on your machine.

**Comment by xvendo** [comment]
Great. Thanks

**Comment by xvendo** [comment]
Works with the following error:

I20160724-18:55:22.825(2)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
W20160724-18:55:23.659(2)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version

more to come ...

**Comment by abernix** [comment]
@xvendo With 1.3.5.1 installed, try running `meteor npm rebuild` within the root of your Meteor project.

If that doesn't work (and since we were futzing around with things), it wouldn't be a bad idea to remove:

* `.meteor/dev_bundle` (if it still exists)
* `.meteor/local/*` (all except `db`)
* `node_modules`

... then `meteor npm install` and run your project again (`meteor`).  Hopefully with the recent fixes you'll never have to do that again, though you will benefit from updating your project itself to more recent versions.

**Comment by xvendo** [comment]
@abernix I can confirm that 1.3.5.1 is working. The error still appears and the app is switching to js fallback. So I can live with that warning mentioned above.

## Report of broken Packages after upgrade:

meteorhacks:fast-render not working as expected anymore
Error: mongo.js:246 Uncaught Error: Expected to find a document to change
Was working with Meteor 1.2.1 
Stopped working with Meteor 1.3.x

https://github.com/kadirahq/fast-render/issues/9
