### ISSUE TITLE
Error: Cannot find module ‘meteor/tmeasday:check-npm-versions’

### ISSUE THREAD

**Issue by lauff** [meteor/meteor#9390]
Issue happens to my existing project after upgrading from 1.5.x to 1.,6

Completely uninstalled Meteor from Windows 10 and installed again.

Same for new project. To reproduce

(see 
[MeteorNix.zip](https://github.com/meteor/meteor/files/1484440/MeteorNix.zip)

Create an empty project with “meteor create”

Install collection2-core
meteor add aldeed:collection2-core
meteor npm install --save simpl-schema

run with “meteor”

```
D:\DEV-ML\htdocs\MeteorNix>meteor
[[[[[ ~\D\DEV-ML\htdocs\MeteorNix ]]]]]

=> Started proxy.
=> Started MongoDB.
W20171117-21:43:55.448(1)? (STDERR) d:\Users\markus\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20171117-21:43:55.486(1)? (STDERR)                                             throw(ex);
W20171117-21:43:55.489(1)? (STDERR)                                             ^
W20171117-21:43:55.490(1)? (STDERR)
W20171117-21:43:55.491(1)? (STDERR) Error: Cannot find module 'meteor/tmeasday:check-npm-versions'
W20171117-21:43:55.492(1)? (STDERR)     at Function.Module._resolveFilename (module.js:513:15)
W20171117-21:43:55.493(1)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20171117-21:43:55.493(1)? (STDERR)     at Object.require (D:\DEV-ML\htdocs\MeteorNix\.meteor\local\build\programs\server\boot.js:287:32)
W20171117-21:43:55.495(1)? (STDERR)     at makeInstallerOptions.fallback (packages\modules-runtime.js:651:18)
W20171117-21:43:55.499(1)? (STDERR)     at require (packages\modules-runtime.js:244:16)
W20171117-21:43:55.500(1)? (STDERR)     at collection2.js (packages/aldeed:collection2-core/collection2.js:1:345)
W20171117-21:43:55.500(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20171117-21:43:55.501(1)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20171117-21:43:55.502(1)? (STDERR)     at D:\DEV-ML\htdocs\MeteorNix\.meteor\local\build\programs\server\packages\aldeed_collection2-core.js:718:15
W20171117-21:43:55.502(1)? (STDERR)     at D:\DEV-ML\htdocs\MeteorNix\.meteor\local\build\programs\server\packages\aldeed_collection2-core.js:729:3
```

manually adding “tmeasday:check-npm-versions” using “meteor add tmeasday:check-npm-versions” does not help.

.meteor\packages

```
meteor-base@1.2.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.3.0                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
reactive-var@1.0.11           # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.5   # CSS minifier run for production mode
standard-minifier-js@2.2.0    # JS minifier run for production mode
es5-shim@4.6.15               # ECMAScript 5 compatibility for older browsers
ecmascript@0.9.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.0            # Server-side component of the `meteor shell` command

autopublish@1.0.7             # Publish all data to the clients (for prototyping)
insecure@1.0.7                # Allow all DB writes from clients (for prototyping)

aldeed:collection2-core
tmeasday:check-npm-versions
```

package.json

```
{
  "name": "MeteorNix",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "babel-runtime": "^6.26.0",
    "meteor-node-stubs": "^0.3.2",
    "simpl-schema": "^0.5.0"
  }
}
```

I also created the issue at aldeed repository and he already looked into it. 
[https://github.com/aldeed/meteor-collection2-core/issues/48](https://github.com/aldeed/meteor-collection2-core/issues/48)

**Comment by lauff** [comment]
I solved it by moving the meteor installation directory to a higher directory level.

Before it was "c:\users\markus\appdata\local\.meteor" now it is "c:\dev\.meteor".

No real idea why this works, might be that a path got too long, but again I don't know.

Anyhow, my issue is resolved and can be closed.

Thanks for your help.
Markus
