### ISSUE TITLE
[1.6] Cannot build on iOS due to cordova-plugin-console

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#9379]
After I updated my app from 1.5 to 1.6, it won't build on iOS anymore. The linker throws an error:

```
duplicate symbol _OBJC_CLASS_$_CDVLogger in:
    /Users/waldgeist/Library/Developer/Xcode/DerivedData/travelguzz-gchredzybixpkmclpnbymgmjhkrl/Build/Intermediates.noindex/travelguzz.build/Debug-iphoneos/travelguzz.build/Objects-normal/arm64/CDVLogger.o
    /Users/waldgeist/Library/Developer/Xcode/DerivedData/travelguzz-gchredzybixpkmclpnbymgmjhkrl/Build/Products/Debug-iphoneos/libCordova.a(CDVLogger.o)
duplicate symbol _OBJC_METACLASS_$_CDVLogger in:
    /Users/waldgeist/Library/Developer/Xcode/DerivedData/travelguzz-gchredzybixpkmclpnbymgmjhkrl/Build/Intermediates.noindex/travelguzz.build/Debug-iphoneos/travelguzz.build/Objects-normal/arm64/CDVLogger.o
    /Users/waldgeist/Library/Developer/Xcode/DerivedData/travelguzz-gchredzybixpkmclpnbymgmjhkrl/Build/Products/Debug-iphoneos/libCordova.a(CDVLogger.o)
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I found a thread in the Ionic framework that boiled this down to `cordova-plugin-console` which has been replaced by Cordova-internal code and thus resulting in duplicate object literals:

https://github.com/ionic-team/ionic/issues/12849#issuecomment-337349446

And in fact, a closer inspection of the generated code shows that `CDVLogger.m` and `CDVLogger.h` appear twice, under `CodovaLib` and under `Plugins`.

Unfortunately, Meteor still hard-depends on this console plugin, so I can't get rid of it:

https://github.com/meteor/meteor/blob/073f2410a685f1de87f70dff6a097b1eea2712b1/packages/logging/package.js#L15
https://github.com/meteor/meteor/blob/235d00e2c7b2d4ad55b92f0c350ac7edfa4b237b/tools/cordova/project.js#L56

**Comment by skirunman** [comment]
@derwaldgeist I'm curious what happens if you manually install `cordova-plugin-console@1.1.0` in your `app/.meteor/cordova-plugins` and re-build your app. See https://github.com/meteor/meteor/issues/9300

**Comment by derwaldgeist** [comment]
That won't work. I had the plugin installed myself and removed it because I thought it would be the culprit. Until I learned that Meteor itself was referencing it, too.

**Comment by skirunman** [comment]
OK, just clarifying you manually installed v1.1.0, and not v1.0.7, as  with v1.1.0 the CDVLogger class should not be loaded with `cordova-ios@4.5.0` or greater.

We are successfully building our 50k SLOC app on Meteor 1.6 with Xcode 9.1 and running on iOS 11 on both iPhone6 and iPhone X without manually installing any version of `cordova-plugin-console` so maybe another plugin or a package in your app has this dependency?.

Did a quick test by first manually installing `cordova-plugin-console@1.0.7` in `/.meteor/cordova-plugins`. Then built our project and got the linker error.

```
duplicate symbol _OBJC_CLASS_$_CDVLogger in:
.
.
.
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I then manually installed `cordova-plugin-console@1.1.0` and was able to successfully build our app! I made sure to clean everything between builds by doing a `meteor reset`.

If you can, it would also be helpful if you tried building with[ Meteor 1.6.1-beta-7 ](https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.6.1-beta.7).

**Comment by VioletaCalvo** [comment]
I had the same problem and manually installing `cordova-plugin-console@1.1.0` worked for me. Thank you @skirunman!

**Comment by derwaldgeist** [comment]
Ok, it worked for me with the updated console plugin, too. I think it would be good if this was mentioned in the Meteor 1.6 upgrade guide.

**Comment by abernix** [comment]
Great suggestion, @derwaldgeist.  I'd take a look at a pull-request for that if you submitted one to the [migration guide](https://github.com/meteor/guide/blob/master/content/1.6-migration.md), but hopefully this will simply be fixed in Meteor 1.6.1 and we won't have to mention it in the upgrade guide, but looks like we're still missing confirmation of whether that will work.  Are you (or @VioletaCalvo) able to confirm if the problem is resolved with the latest Meteor 1.6.1 beta, as @skirunman suggested?:

> If you can, it would also be helpful if you tried building with Meteor 1.6.1-beta-7 .

The current beta is now Meteor 1.6.1-beta.8, so you can test in your own project with:

    meteor update --release 1.6.1-beta.8

(Follow along for beta updates with #9274)

It would be much appreciated if you could help!

**Comment by derwaldgeist** [comment]
I tried to upgrade to 1.6.1-beta.8, but ran into this error (after running into #9378):

```
/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.1-beta.8.6t0v0y.du994++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at relative (path.js:1267:5)
    at ImportScanner._getRelativeImportId (/tools/isobuild/import-scanner.js:662:24)
    at ImportScanner._checkSourceAndTargetPaths (/tools/isobuild/import-scanner.js:304:31)
    at files.forEach.file (/tools/isobuild/import-scanner.js:225:12)
    at Array.forEach (<anonymous>)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:224:11)
    at sourceBatches.forEach.batch (/tools/isobuild/compiler-plugin.js:1041:15)
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1012:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1057:8)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:828:12)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:819:18)
    at /tools/isobuild/bundler.js:2927:14
    at /tools/isobuild/bundler.js:3016:20
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.1-beta.8.6t0v0y.du994++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:3015:7
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2908:31)
    at files.withCache (/tools/isobuild/bundler.js:2855:32)
    at Object.withCache (/tools/fs/files.js:1658:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2855:16)
    at Profile.run (/tools/runners/run-app.js:579:36)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:578:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
    at AppRunner._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:408:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TravelGuzz@0.0.1 start: `meteor run --settings settings.json --port $npm_package_config_port --mobile-server $npm_package_config_ipaddress:$npm_package_config_port "ios-device"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TravelGuzz@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/waldgeist/.npm/_logs/2017-11-22T13_04_00_143Z-debug.log
```

**Comment by derwaldgeist** [comment]
[2017-11-22T13_04_00_143Z-debug.log](https://github.com/meteor/meteor/files/1496044/2017-11-22T13_04_00_143Z-debug.log)

**Comment by paranoico** [comment]
Same problems here, moreover, Android version disconnects regularly with error:

> WebSocket is already in CLOSING or CLOSED state

For now, we have downgraded to version 1.5.2.1, last one stable for our app.

**Comment by skirunman** [comment]
@paranoico As this issue is closed what are you referring to when you said:

> Same problems here

I want to make sure you are not experiencing the iOS build issue with duplicate symbols with regards to `cordova-plugin-console` which can be resolved in Meteor 1.6 as discussed [here](https://github.com/meteor/meteor/issues/9379#issuecomment-345106428) or by updating to a Meteor 1.6.1 beta release. 

If you are experiencing another issue on Android it would be useful if you open another issue for that problem. I'm working on a Pull Request to update to `cordova-android@6.4.0`, but there are issues with this as it [breaks support for Crosswalk](https://cordova.apache.org/announcements/2017/11/09/android-release.html).

**Comment by paranoico** [comment]
Hello @skirunman 
Our issues was about the same in regards cordova-plugin-console but at the end downgrading to Meteor v1.5.2.1 got our App working again.

And yes, it is on Android, I am sorry.

This week we are going to start a new App for other requirements. So we are going to try to find issues with v1.6, until then I have no time to post a new issue. Thanks for your answer.

**Comment by ricardoteix** [comment]
> I had the same problem and manually installing `cordova-plugin-console@1.1.0` worked for me. Thank you @skirunman!

Same here.
