### ISSUE TITLE
METEOR@1.4.2.1 Uncaught Error: Cannot find module for ReactJS

### ISSUE THREAD

**Issue by dulguun0225** [meteor/meteor#8035]
After upgrading to 1.4.2.1 using external reactjs library causes this problem in browser. Also some module imports can't find the module.

```
> modules-runtime.js?hash=5b5615c…:119Uncaught Error: Cannot find module './components/fields/SchemaField'
>     at require (http://localhost:3000/packages/modules-runtime.js?hash=5b5615c907a5b9a4d19081582f04748e2ad64275:119:19)
>     at http://localhost:3000/packages/modules.js?hash=3252ce8492943ee8ba8b3b8c8e4828e79869200a:24945:19
>     at Array.reduce (native)
>     at load (http://localhost:3000/packages/modules.js?hash=3252ce8492943ee8ba8b3b8c8e4828e79869200a:24944:16)
>     at getDefaultRegistry (http://localhost:3000/packages/modules.js?hash=3252ce8492943ee8ba8b3b8c8e4828e79869200a:24950:16)
>     at Form.getRegistry (http://localhost:3000/packages/modules.js?hash=3252ce8492943ee8ba8b3b8c8e4828e79869200a:24669:63)
>     at Form.render (http://localhost:3000/packages/modules.js?hash=3252ce8492943ee8ba8b3b8c8e4828e79869200a:24704:27)
>     at http://localhost:3000/packages/modules.js?hash=3252ce8492943ee8ba8b3b8c8e4828e79869200a:17520:21
>     at measureLifeCyclePerf (http://localhost:3000/packages/modules.js?hash=3252ce8492943ee8ba8b3b8c8e4828e79869200a:16801:12)
>     at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/packages/modules.js?hash=3252ce8492943ee8ba8b3b8c8e4828e79869200a:17519:27)
```

Sample project is here [https://github.com/dulguun0225/METEOR-1.4.2.1-issue](https://github.com/dulguun0225/METEOR-1.4.2.1-issue)

**Comment by benjamn** [comment]
What version were you upgrading from?

**Comment by dulguun0225** [comment]
I don't remember exactly from what version. Somewhere 1.4.1.3 - 1.4.2.0

**Comment by benjamn** [comment]
Dynamic `require` calls like [this one](https://github.com/mozilla-services/react-jsonschema-form/blob/1e16b9f3ab1974317983f62bc15d5bdae7f40763/src/utils.js#L59) (where the module identifier string is not a string literal) are not supported in client-bundled code, because it's hard/impossible to know at bundling time exactly what module is being imported.

Webpack works around this by including all modules matching a certain configuration option, but then you're potentially shipping unused modules to the client.

You can force certain specific modules to be included in the bundle by putting
```js
require("react-jsonschema-form/lib/components/fields/SchemaField.js")
```
explicitly in your own code. Repeat for any other modules that might be imported by dynamic `require` calls at runtime.

The code in question appears to have been added [two days ago](https://github.com/mozilla-services/react-jsonschema-form/commit/f24a72826b1d966ff644334e119b8278c999e71b), so I think this error was introduced by the release of `react-jsonschema-form@0.40.0`, not by the recent Meteor release.

**Comment by benjamn** [comment]
Feel free to reopen this issue if my analysis seems incorrect. Thanks for asking about it.

**Comment by dulguun0225** [comment]
Thanks, so going back react-jsonschema-form version should fix it right?

**Comment by dulguun0225** [comment]
Seems like it's version 0.41.0. 0.40.0 works fine.
