### PR TITLE
Ensure the meteor.loginServiceConfiguration subscription always becomes ready

### LINKED ISSUE #12376: 2.9: window.DDP._allSubscriptionsReady()  always returns false
We use the function `window.DDP._allSubscriptionsReady()` for our Cypress test to check if all subscriptions are ready. After updating to Meteor 2.9 this function always return false.

The [Migration Guide](https://guide.meteor.com/2.9-migration.html) does not mention any changes here.

It's probably related to [this issue](https://github.com/meteor/meteor/issues/12375) but because it is a different package I open a new issue for this.

### PR DESCRIPTION
**Pull request by Torgen**
Fixes #12376

### CODE REVIEW

**Review by zodern — DISMISSED** [review]

**Comment by ixdi** [comment]
Hi,
After update to 2.11.0-rc.0 the initialization of the server shows this message:
```
I20230208-16:13:27.952(1)? Exception from sub meteor.loginServiceConfiguration id vAACiX9oharg3fne4 TypeError: this.ready is not a function
I20230208-16:13:27.954(1)?     at Subscription._server.publish.is_auto [as _handler] (packages/accounts-base/accounts_server.js:769:12)
I20230208-16:13:27.954(1)?     at packages/check/match.js:118:15
I20230208-16:13:27.954(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
I20230208-16:13:27.954(1)?     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
I20230208-16:13:27.954(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
I20230208-16:13:27.954(1)?     at packages/ddp-server/livedata_server.js:1124:9
I20230208-16:13:27.954(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
I20230208-16:13:27.954(1)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1123:60)
I20230208-16:13:27.954(1)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:934:9)
I20230208-16:13:27.955(1)?     at Session.sub (packages/ddp-server/livedata_server.js:673:12)
I20230208-16:13:27.955(1)?     at packages/ddp-server/livedata_server.js:603:43
```
Could it be that it is necessary to use this.ready() with function definition instead of using the arrow function?
```js
this._server.publish("meteor.loginServiceConfiguration", () => { ... this.ready(); }, {is_auto: true})
```
Thanks
