### ISSUE TITLE
1.7.0.3 Meteor.autorun is not a function

### ISSUE THREAD

**Issue by haojia321** [meteor/meteor#10061]
Got below error after upgraded from 1.6.1.2 to 1.7.0.3. 
Seems like im not using u2622:persistent-session in my project though.

Exception in callback of async function: TypeError: Meteor.autorun is not a function
    at Object.UserHelper.js.UserHelper.subscribeMyUserDetails (UserHelper.js:4)
    at ctor.waitOn (UserBaseController.js:55)
    at iron_router.js?hash=0266e6aaa7cb3eef37db8c36c9ecc86aece007c9:436
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (underscore.js?hash=884c0f04552531e604be5ca6d94381bbf1550f5c:149)
    at ctor.RouteController._runRoute (iron_router.js?hash=0266e6aaa7cb3eef37db8c36c9ecc86aece007c9:435)
    at Function.Route.dispatch (iron_router.js?hash=0266e6aaa7cb3eef37db8c36c9ecc86aece007c9:851)
    at ctor.route (iron_router.js?hash=0266e6aaa7cb3eef37db8c36c9ecc86aece007c9:708)
    at boundNext (iron_middleware-stack.js?hash=0209544ffaf64fce7f891fcce52510851380c75a:418)
    at meteor.js?hash=c8108d734cc548d91539b054e14b613d0c4512cc:1185

**Comment by klaussner** [comment]
`Meteor.autorun` has been deprecated for quite a while and was removed in Meteor 1.7. I think you can simply replace it with `Tracker.autorun` in your `UserHelper.js` file.

**Comment by haojia321** [comment]
@klaussner Thank you.

**Comment by derwaldgeist** [comment]
> and was removed in Meteor 1.7

That's a bummer. I just stumbled upon this because a community package is using this. Why are these kind of breaking changes introduced without any need?
