### ISSUE TITLE
accounts-password 1.2.13 fails on resetPassword

### ISSUE THREAD

**Issue by menelike** [meteor/meteor#7611]
*Meteor Version: METEOR@1.4.0.1*
*OS: 4.4.0-28-generic 47-Ubuntu SMP; OS X 10.11.5*

*versions*
```
accounts-base@1.2.9
accounts-password@1.2.13
```

After upgrading `accounts-password` from 1.2.12 to 1.2.13 I always get this error when the client tries to use `Accounts.resetPassword()`. This has been tested in context of `enrollAccount` feature.

```
meteor update
This project is already at Meteor 1.4.0.1, the latest release.

Changes to your project's package version selections from updating package versions:

accounts-password   upgraded from 1.2.12 to 1.2.13
```

```
I20160809-14:09:35.616(2)? Exception while invoking method 'resetPassword' TypeError: Accounts._getPasswordResetTokenLifetimeMs is not a function
I20160809-14:09:35.618(2)?     at packages/accounts-password/password_server.js:668:38
I20160809-14:09:35.618(2)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:247:14)
I20160809-14:09:35.618(2)?     at AccountsServer.Ap._loginMethod (packages/accounts-base/accounts_server.js:380:5)
I20160809-14:09:35.619(2)?     at [object Object].resetPassword (packages/accounts-password/password_server.js:654:19)
I20160809-14:09:35.619(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160809-14:09:35.619(2)?     at packages/ddp-server/livedata_server.js:711:19
I20160809-14:09:35.619(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160809-14:09:35.619(2)?     at packages/ddp-server/livedata_server.js:709:40
I20160809-14:09:35.620(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160809-14:09:35.620(2)?     at packages/ddp-server/livedata_server.js:707:46
I20160809-14:09:35.620(2)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20160809-14:09:35.620(2)?     at packages/ddp-server/livedata_server.js:551:43
```

I'm not sure if I missed something regarding the upgrade, could not find any instructions about incompatibilities. 
The temporary solution: Use `accounts-password@=1.2.12` in packages to avoid upgrades.

**Comment by benjamn** [comment]
Confirmed, sorry! The good news is we can now fix this without doing another Meteor release, thanks to core package version unpinning.

**Comment by benjamn** [comment]
Your comment [here](https://github.com/meteor/meteor/pull/7534/files#r74042634) seems to be accurate, by the way.

**Comment by benjamn** [comment]
Fixed by `accounts-base@1.2.10` and `accounts-password@1.2.14`, published just now.

**Comment by menelike** [comment]
@benjamn I can't tell you how much I appreciate your work, thanks a lot for this fast response.

**Comment by izqui** [comment]
Such a quick fix, thank you @benjamn. Working again!

**Comment by bjones6** [comment]
@benjamn Appreciate the quick fix!

**Comment by Frazer** [comment]
@benjamn - awesome!  How do I use this fix 'Fixed by accounts-base@1.2.10 and accounts-password@1.2.14, published just now.' ?

Sorry, I'm still new to Meteor

**Comment by bjones6** [comment]
@Frazer If I recall the fix is by explicitly setting the package version inside the .meteor folder of your project. Meteor should then detect the change and update the broken package with the fixed one. If you google around a bit you can find the exact syntax for explicitly setting the package version, I believe it's simply $PACKAGE_NAME@$PACKAGE_VERSION but I may be wrong.

**Comment by Frazer** [comment]
Thanks! setting the package version inside the .meteor folder worked a charm - super easy.
