### ISSUE TITLE
Meteor.loginWithGoogle broken on 1.7.0.3

### ISSUE THREAD

**Issue by gchallen** [meteor/meteor#10111]
My existing Google login flow that was (and is) working on 1.6.1.3 breaks when I upgrade to 1.7.0.3. Client-side calls to `Meteor.loginWithGoogle...` produce the following error messages in the server console:
````
W20180730-13:17:11.442(-5) (oauth.js:100) Unable to base64 decode state from OAuth query: undefined
W20180730-13:17:11.446(-5) (oauth.js:100) Unable to base64 decode state from OAuth query: undefined
W20180730-13:17:11.446(-5) (oauth.js:424) Error in OAuth Server: Failed to complete OAuth handshake with Google. failed [400] {   "error" : "invalid_grant",   "error_description" : "Malformed auth code." }
````
Backing up to 1.6.1.3 immediately fixes the problem at which point login begins working again.

**Comment by paulincai** [comment]
Hi there, I am up to date with Meteor and accounts-google and everything works fine including Cordova. Here is my login setup:

`"loginStyle": "popup",
        "scope": [
          "email",
          "https://www.googleapis.com/auth/plus.login"
        ]`

`Meteor.loginWithGoogle({requestPermissions: scope, loginStyle, requestOfflineToken: true}, err => {... handle}`

"requestOfflineToken: true" is possibly responsible for your type of error. Do you have it set in your login method?

[might help](https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35)

**Comment by graemian** [comment]
@gchallen Was this ever resolved for you? Can you point me to your pull request? I can't seem to find it

**Comment by gchallen** [comment]
IIRC this was resolved, via [this pull request](https://github.com/meteor/meteor/pull/10152).
