### ISSUE TITLE
Cordova 4: Issues with raix:push 

### ISSUE THREAD

**Issue by nddeveloper** [meteor/meteor#6927]
I have used raix:push plugin in meteor project. It works fine in meteor 1.2 but in meteor 1.3 it gives error when compiling code in xcode.

.meteor/local/cordova-build/platforms/ios/meteor1.3/Plugins/com.phonegap.plugins.PushPlugin/PushPlugin.m:274:23: error: no visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
[self.webView stringByEvaluatingJavaScriptFromString:jsCallBack];

**Comment by nddeveloper** [comment]
I have used raix:push plugin in meteor project. It works fine in meteor 1.2 but in meteor 1.3 it gives error when compiling code in xcode.

.meteor/local/cordova-build/platforms/ios/recurly-meteor1.3/Plugins/com.phonegap.plugins.PushPlugin/PushPlugin.m:274:23: error: no visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
        [self.webView stringByEvaluatingJavaScriptFromString:jsCallBack];

**Comment by abernix** [comment]
Considering this is a bug with `raix:push` (or an incompatibility with a new version of Meteor) and not Meteor itself, perhaps you could consider opening this with [that package's own issue tracker](https://github.com/raix/push) instead?  Also, might I suggest a title of "raix:push breaks with Meteor 1.3".

**Comment by nddeveloper** [comment]
This link has same issue: 
https://github.com/Telerik-Verified-Plugins/PushNotification/issues/71

And the conclusion is that the issue is with cordova 4.x which is used in meteor 1.3 for ios.

can i use specific version of cordova or can i downgrade cordova to specific version

**Comment by abernix** [comment]
1.3 was a major version upgrade for Cordova to version 4 (which was already behind, as Cordova 5 is already out).  Downgrading might not be possible (though I'm not sure)

The problem lies around the `UIWebView` change in Cordova 4.  And it's not an **issue** per se, but instead it's been deprecated in favor of the (*much* faster) `WkWebView`. As you can see in the other issue you referenced (on a third project), the owners have made or are making changes.  It is no longer recommended to use in the newer versions of Cordova and the `raix:push` package will need to be updated.  

Even if it is possible for someone to take a look at this here, please:
* Change the title of this Issue to something **brief** and helpful, like "Cordova 4: Issues with raix:push"
* Provide a small sample repo (so an engineer doesn't have to re-build your project).

You will likely have to switch to a more actively maintained module or wait until it is updated.

**Comment by laosb** [comment]
Sounds like a `raix:push`-specific issue. Cordova 4 did break something and packages should follow. Closing as this is not quite close to Meteor itself.
