### ISSUE TITLE
Install for Android not working with Android Studio 3.0.1, Android SDK 24-27, Meteor 1.6

### ISSUE THREAD

**Issue by cdcv** [meteor/meteor#9510]
- [x ] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [x ] The version of Meteor showing the problem.
1.6
- [x ] The last version of Meteor where the problem did _not_ occur, if applicable.
Same, installed on another dev Mac
- [x ] The operating system you're running Meteor on.
Max OS 10.12.6
- [x ] The expected behavior.
Possible to run meteor add-platform android
- [x ] The actual behavior.
meteor add-platform android yields:
android: added platform                       
                                              
Your system does not yet seem to fulfill all requirements to build apps for Android.
                                              
Please follow the installation instructions in the mobile guide:
http://guide.meteor.com/mobile.html#installing-prerequisites
                                              
Status of the individual requirements:        
✓ Java JDK                                    
✓ Android SDK                                 
✗ Android target: avdmanager: Command failed with exit code 1 Error output:
  Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
  at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
  at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
  at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
  at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
  at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
  Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
 
I am trying to setup a new dev machine.  This has become a half-day project, and is still not working.  The instructions in the Guide are not adequate.  I especially like this instruction from the Guide: “Install the Android SDK and download the required tools, platforms, and other components”

It is completely unclear what's going on.  Others have apparently had similar problems, based on a number of other issues, and posts, but I have not been able to find a resolution.

I've tried Android SDK 23,24,25,26,27, with none working.
I have the same project building correctly on another machine that I have tried to exactly reproduce everything from (including Android Studio 3 setup, environment / path variables).

I spend MOST of my time with Meteor not on development but on this kind of issue.  I really wish that Meteor would focus more energy on usability rather than new features for the next release.
It shouldn't in my view take all day to be able to build a meteor project for Android and iOS... but it does.

Thanks for your help.

**Comment by klaussner** [comment]
Can you check which Java version you have installed (with `java -version`)? I think the Android SDK requires Java 8 and doesn't work with Java 9 yet (see [this Stack Overflow answer](https://stackoverflow.com/a/43574427/499350) for details).

**Comment by skirunman** [comment]
I share your pain with doing Cordova development with Meteor. The biggest problem is that Android/Android Studio and iOS/Xcode change more frequently, including breaking changes, which requires changes, including breaking changes, to Cordova than Meteor is able to keep up with in its release cycle. 

For instance, I made this PR https://github.com/meteor/meteor/pull/9213 to update to `cordova-lib@7.1.0` and [`cordova-android@6.3.0`](https://cordova.apache.org/announcements/2017/09/27/android-release.html) back on October 11, 2017. However, it is still not released and since then [`cordova-lib@8.0.0`](https://cordova.apache.org/news/2017/12/18/tools-release.html) has been released along with [`cordova-android@6.4.0`](https://cordova.apache.org/announcements/2017/11/09/android-release.html) and recently [`cordova-android@7.0.0`](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html). Both of these android releases fix issues including specifically with building with Android Studio 3.

In my opinion it would be best to decouple the Cordova releases from Meteor releases as per [this feature request](https://github.com/meteor/meteor-feature-requests/issues/112).  Also, this [issue](https://github.com/meteor/meteor-feature-requests/issues/148) and this [issue](https://github.com/meteor/meteor-feature-requests/issues/245) really need to be addressed as well.

Until Meteor 1.6.1 is released you may need to downgrade your tools. Meteor 1.6.0.1 is using [`cordova-android@6.2.3`](https://cordova.apache.org/announcements/2017/05/04/android-release.html). Therefore, you may want to use an older version of Android Studio, I'm using 2.3.1, and stick to Android API Level 26.

**Comment by davidecantini** [comment]
@skirunman Also this [issue](https://github.com/meteor/meteor/issues/9479) could have been fixed already (since Oct 11, 2017, based on your comment) but it's stuck waiting for 1.6.1 to be released.
Your proposal of decoupling Cordova releases from Meteor releases seem to be the way to go.

**Comment by klaussner** [comment]
While I agree that setting up the required tools and dependencies can be difficult, this issue doesn't seem to be caused by Meteor or an outdated Cordova version. The exception is thrown by the `avdmanager` in the Android SDK because it's not compatible with Java 9. I've opened meteor/guide#686 about adding a note to the JDK installation instructions in the guide. :slightly_smiling_face:

**Comment by cdcv** [comment]
It turns out that the problem is the version of Java.  When I installed Java 8, I was able to get this to work.  So that others are aware, it is possible to build correctly for Android using Android Studio 3, that wasn't the problem.
It would be REALLY HELPFUL if MDG/the meteor community would create a simple tool that outputs all of the relevant versions of everything that meteor requires to work properly (probably need this for Mac, Windows, Linux), along with the correct versions that will actually work.  This would have saved me days worth of time.  This would also make it easier to post to this forum and ensure that all of the relevant information is available.  Thanks.

**Comment by doukasd** [comment]
Indeed the issue was having installed a version of Java later than 8 and the solution as easy as deleting that from `/Library/Java/JavaVirtualMachines`

**Comment by chip** [comment]
I've downgraded to Java 8 and am still running into this issue. I also tried downloading Android Studio 2.3.1 per suggestions from @skirunman, but it is no longer available at https://developer.android.com/studio/archive. I did download 2.3.2, but that doesn't allow API Level 26 and didn't work anyway. I've tried this on both 1.6.1.1 and 1.7.0.1. Is there a valid link for downloading Android Studio 2.3.1 out there? Thanks.

**Comment by RichardHitier** [comment]
I dont get why this issue is closed. 
Guess it should be inserted in the meteor tuto.

 However, thanks to  https://github.com/NativeScript/nativescript-cli/issues/3139  I could fix it with the following environnement setting:
export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'

**Comment by DrLonnieJonesPFMP** [comment]
@cdcv
What combination did you use to get it to work?

**Comment by patelkrunal78** [comment]
I had a similar problem this morning (trying to build for Android using Unity3D). I ended up uninstalling JDK9 and installing Java SE Development Kit 8u144. Hope this helps.

Find more at Here https://icetutor.com/question/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-annotation-xmlschema
