### ISSUE TITLE
After meteor update (babel-runtime 1.0.0) => Client: Cannot find module 'babel-runtime/helpers/typeof'

### ISSUE THREAD

**Issue by nska02** [meteor/meteor#8032]
Meteor version: 1.4.2 // packages all last updates
Platform: Ubuntu 16.04
Packages used include (among all) reactive-dict failing (among others) on client.

Due to reactive-dict dependants, cascading failures (zimme:active-route, session,  kadira:flow-router, blaze-layout, autoform, etc.).

I tried to npm install babel-runtime, deleted .local cache, reinstalled fresh ~/.meteor. Nothing worked.

To reproduce, simply make a fresh install of Meteor, create project, and add reactive-dict package. The app homepage will still appear but shows error in the console. 
As it is with my app, flow-router fails and thus can't display anything. 

Thanks in advance for your help.

![screenshot from 2016-11-09 11-14-31](https://cloud.githubusercontent.com/assets/11373782/20135096/4c11c576-a66e-11e6-9b2d-0a2f1b89e54f.png)

**Comment by wareczek** [comment]
Same here
`Cannot find module 'babel-runtime/helpers/classCallCheck'`

**Comment by Elandiro** [comment]
Same here
_Error: Cannot find module 'babel-runtime/helpers/typeof'_
_Error: Cannot find module 'babel-runtime/helpers/classCallCheck'_

**Comment by drrodio** [comment]
I'm working with meteor 1.4.1 without problems ... after update to 1.4.2:

Error: The babel-runtime npm package could not be found in your node_modules 
directory. Please run the following command to install it:

  meteor npm install --save babel-runtime

Still no solution found

**Comment by marcofacheris** [comment]
Same here, Meteor 1.4.2, after running `meteor update --all-packages` which updated babel-runtime to 1.0.0.

**Comment by abstractmatter** [comment]
+1

**Comment by ucekmez** [comment]
+1

**Comment by marcofacheris** [comment]
I was able to downgrade babel-runtime to the previous version with the following command:
`meteor add babel-runtime@=0.1.13 --allow-incompatible-update`
got this output:
`
babel-runtime*  downgraded from 1.0.0 to 0.1.13
coffeescript    downgraded from 1.11.1_3 to 1.11.1_2
ecmascript      downgraded from 0.6.0 to 0.5.9
`
my app is working again now. i'm not aware of possible side effects of this, anyway, i won't update again until a new version of babel-runtime is out.
The whole javascript ecosystem is such a mess...

**Comment by benjamn** [comment]
Meteor 1.4.2.1 will fix this, but the workaround @marcofacheris suggests is a good one for now. Just remember to remove that `=` from the `babel-runtime` version in your `.meteor/packages` file when you update to 1.4.2.1.

**Comment by benjamn** [comment]
Hi folks, this is my fault, and I'm very sorry for the inconvenience.

The good news is that Meteor 1.4.2.1 (just released) fixes this problem, along with several other bugs that affected Meteor 1.4.2 (see [History.md](https://github.com/meteor/meteor/blob/devel/History.md#v1421)).

Please run `meteor update` as soon as possible, and make sure you also run `meteor npm install --save babel-runtime` in your app if you haven't already.

I hope this goes without saying, but please let me know if you have any other problems after updating!

**Comment by nska02** [comment]
Thanks @marcofacheris and @benjamn .
All works fine from my side now.
So I understand from the log history that starting now every meteor project has to include babel-runtime as a node-module to properly compile, right?

**Comment by benjamn** [comment]
That's right, @nska02.

**Comment by drrodio** [comment]
Nice work guys @benjamn @marcofacheris

**Comment by benjamn** [comment]
Wrote a longer post on the forums about this problem: https://forums.meteor.com/t/meteor-1-4-2-1-is-an-important-patch-for-1-4-2-users/31190

**Comment by stefanve** [comment]
meteor npm install --save babel-runtime  did not solve it for me after update to 1.4.2.3

**Comment by nonyy** [comment]
@stefanve Try meteor npm init first.
I don't know why but concerning my old project updated to 1.4.2.3 from 1.2.1 meteor did not want to install babel-runtime until I provided package.json file.

**Comment by nonyy** [comment]
Update: I know why. Npm requires package.json before installing babel-runtime. It's provided by default using meteor create testapp but if you update the project, you have to provide it yourself.
The following message (from either meteor install babel-runtime or meteor install --save babel-runtime) indicates so:

> npm WARN saveError ENOENT: **no such file or directory, open '/home/tomasz/package.json'**
/home/tomasz
└── babel-runtime@6.18.0 
npm WARN enoent ENOENT: no such file or directory, open '/home/tomasz/package.json'
npm WARN tomasz No description
npm WARN tomasz No repository field.
npm WARN tomasz No README data
npm WARN tomasz No license field.

**Comment by wodinga** [comment]
Hey @nonyy that fixed my problem. Why is it looking for a package.json file in the home directory all of a sudden?

**Comment by skemb321** [comment]
@TechplexEngineer hahaha it worked! I really dont know why we have to npm install first. It was okay to install inside the bundle before, right? hahaha Anyways, thanks!

**Comment by alexbottoni** [comment]
FYI: this problem still exists in Meteor 1.4.2.3 as Feb, the 1st 2017. Meteor complains about the lack of the whole "babel-runtime" package as reported by drrodio on Nov the 9th (see comments above).

Fixed with "meteor npm init" followed by "meteor npm install --save babel-runtime" as suggested by nonyy on Nov. the 20th. See comments above.

**Comment by Pitasi** [comment]
@TechplexEngineer you saved my day. ;)

**Comment by rschiavi** [comment]
babel is really ruining my friday deploy, just got through all the above mess, and now this. anyone ever seen this one?

 While building for web.browser:
   node_modules-/babel-runtime/helpers/asyncGenerator.js:122:20: await is a reserved word (122:20)

**Comment by hems** [comment]
meteor npm init did for me

**Comment by bretonio** [comment]
In my case  the module not found is ´@babel/runtime´ ...

**Comment by benjamn** [comment]
This is an old issue, but I think the recent commenters are hitting this problem: https://github.com/meteor/meteor/issues/10126#issuecomment-410469107
