### ISSUE TITLE
Error: Cannot find module './entry.js' after upgrade from 1.4.1.3 to 1.4.4.3 

### ISSUE THREAD

**Issue by dongzhi-yang** [meteor/meteor#8727]
I just upgraded my app from 1.4.1.3 to 1.4.4.3, the upgrade seemed successful, but when I tried to start the app, the Error: Cannot find module './entry.js'  occurred, please see the following messages from screen after i run 'meteor run'.

-------------------------
=> Started proxy.
For compatibility, the PACKAGE_DIRS environment variable is deprecated and will be removed in a future Meteor release.
Developers should now use METEOR_PACKAGE_DIRS and Windows projects should now use a semi-colon (;) to separate paths.
=> Started MongoDB.
W20170530-01:40:50.659(8)? (STDERR) D:\ecom\.meteor\local\build\programs\server\boot.js:356
W20170530-01:40:50.718(8)? (STDERR) }).run();
W20170530-01:40:50.719(8)? (STDERR)    ^
W20170530-01:40:50.720(8)? (STDERR)
W20170530-01:40:50.722(8)? (STDERR) Error: Cannot find module './entry.js'
W20170530-01:40:50.723(8)? (STDERR)     at require (packages\modules-runtime.js:123:19)
W20170530-01:40:50.725(8)? (STDERR)     at meteorInstall.node_modules.meteor.modules.node_modules.reify.lib.runtime.js (packages\modules.js:319:13)
W20170530-01:40:50.727(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:197:9)
W20170530-01:40:50.729(8)? (STDERR)     at require (packages\modules-runtime.js:120:16)
W20170530-01:40:50.731(8)? (STDERR)     at meteorInstall.node_modules.meteor.modules.reify.js (packages\modules.js:301:1)
W20170530-01:40:50.732(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:197:9)
W20170530-01:40:50.745(8)? (STDERR)     at require (packages\modules-runtime.js:120:16)
W20170530-01:40:50.746(8)? (STDERR)     at meteorInstall.node_modules.meteor.modules.server.js (packages\modules.js:24:1)
W20170530-01:40:50.748(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:197:9)
W20170530-01:40:50.749(8)? (STDERR)     at require (packages\modules-runtime.js:120:16)
=> Exited with code: 1

**Comment by dongzhi-yang** [comment]
I have tried the solution in this https://github.com/nodejs/node/issues/3543, but wasn't successful

**Comment by benjamn** [comment]
Try running `meteor reset`?

**Comment by dongzhi-yang** [comment]
Hi Ben, thanks, I tried, but it didn't work.

**Comment by hwillson** [comment]
Hi @dongzhi-yang - just to make sure, do you have the `babel-runtime` package installed?

```
meteor npm install --save babel-runtime
```

**Comment by dongzhi-yang** [comment]
@hwillson , I just installed babel-runtime with the above command given. but still same error. 
btw, I am on Windows 10

**Comment by crapthings** [comment]
do u use [mantra](https://github.com/kadirahq/mantra) ?
do u use babel root import ?

what is your package.json looks like, and .babelrc ?

**Comment by dongzhi-yang** [comment]
Hi @crapthings , I am not using mantra , the package.json looks like the following. 
I can't find .babelrc file
{
  "name": "ecom",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "ContentTools": "^1.3.1",
    "angular": "^1.5.9",
    "angular-bootstrap-lightbox": "^0.12.0",
    "angular-drag-and-drop-lists": "^2.1.0",
    "angular-xeditable": "^0.2.0",
    "babel-runtime": "^6.23.0",
    "bcrypt": "^0.8.7",
    "express": "^4.14.0",
    "fastclick": "^1.0.6",
    "fibers": "^1.0.15",
    "gridfs-stream": "^1.1.1",
    "hammerjs": "^2.0.8",
    "imports": "^1.0.0",
    "jquery": "^2.2.4",
    "jquery-hammerjs": "^2.0.0",
    "meteor-jsdoc": "^1.0.4",
    "ng-embed": "^2.1.1",
    "package": "^1.0.1",
    "pingpp": "^2.0.8",
    "pingpp-js": "^2.1.5",
    "textangular": "^1.5.16"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/dongzhi-yang/ecom.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/dongzhi-yang/ecom/issues"
  },
  "homepage": "https://github.com/dongzhi-yang/ecom#readme"
}

**Comment by crapthings** [comment]
https://github.com/meteor/meteor/issues/8729

we might have the same issue

**Comment by dongzhi-yang** [comment]
@crapthings ,thanks but unfortunately not,  mine cannot even upgrade to 1.4.2 or 1.4.2.1. It shows the same error with entry.js if I try to upgrade to 1.4.2 and above.

**Comment by dongzhi-yang** [comment]
does it have anything to do with node version or npm version? i have installed nvm and changed the node version to 4.5.0 but it still doesn't work

**Comment by dongzhi-yang** [comment]
since the release of 1.5, the error has changed to the following, although I am still trying to run 1.4.4.3:
I tried to create a new empty project and reinstalled meteor, delete '.meteor' folder, but still the error persists.
For compatibility, the PACKAGE_DIRS environment variable is deprecated and will be removed in a future Meteor release.
Developers should now use METEOR_PACKAGE_DIRS and Windows projects should now use a semi-colon (;) to separate paths.
W20170602-11:36:11.215(8)? (STDERR) D:\ecom\.meteor\local\build\programs\server\boot.js:356
W20170602-11:36:11.217(8)? (STDERR) }).run();
W20170602-11:36:11.219(8)? (STDERR)    ^
W20170602-11:36:11.220(8)? (STDERR)
W20170602-11:36:11.231(8)? (STDERR) Error: Cannot find module './utils.js'
W20170602-11:36:11.238(8)? (STDERR)     at makeMissingError (packages\modules-runtime.js:221:12)
W20170602-11:36:11.242(8)? (STDERR)     at require (packages\modules-runtime.js:231:19)
W20170602-11:36:11.254(8)? (STDERR)     at meteorInstall.node_modules.meteor.modules.node_modules.reify.lib.runtime.index.js (packages\modules.js:308:13)
W20170602-11:36:11.273(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:333:9)
W20170602-11:36:11.275(8)? (STDERR)     at require (packages\modules-runtime.js:228:16)
W20170602-11:36:11.278(8)? (STDERR)     at meteorInstall.node_modules.meteor.modules.reify.js (packages\modules.js:287:1)
W20170602-11:36:11.287(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:333:9)
W20170602-11:36:11.289(8)? (STDERR)     at require (packages\modules-runtime.js:228:16)
W20170602-11:36:11.301(8)? (STDERR)     at meteorInstall.node_modules.meteor.modules.server.js (packages\modules.js:23:1)
W20170602-11:36:11.303(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:333:9)

**Comment by dongzhi-yang** [comment]
I moved my project  and all local packages to under the current user folder, and it works.  And I am even able to upgrade to 1.5. 
But if I create a new project outside of the current user folder , the project can not run. 
So meteor doesn't allow creating project in folders outside of current user's folder starting from 1.4.2?
Or is this a bug?

**Comment by hwillson** [comment]
@dongzhi-yang Can you try creating a project in a folder that doesn't have a period in its name? Your example uses `D:\ecom.meteor` - can you try with something like `D:\ecom_meteor` and report back? Thanks!

**Comment by dongzhi-yang** [comment]
@hwillson thanks a lot for the tip. I moved a project folder to the current user folder which is   c:\users\my_user_name\ and it worked. 
Not sure why it didn't work on D drive though. Will try to tip when I have sometime.

**Comment by hwillson** [comment]
Thanks @dongzhi-yang - I'll close this issue for now then, since the issue of having special characters in a directory name is already being tracked in https://github.com/meteor/meteor/issues/8840.
