### PR TITLE
Fixes: TypeError: this._encodeParams is not a function #11092

### PR DESCRIPTION
**Pull request by RobertLowe**
Fixes: TypeError: this._encodeParams is not a function #11092

I can't explain why behaviour changed, but this resolves the issue, I was able to reproduce it following @WayneUong comment (https://github.com/meteor/meteor/issues/11092#issuecomment-645814564) using a minimal app of:

```
meteor-base
http
ecmascript
standard-minifier-css
standard-minifier-js
```

### CODE REVIEW

**Comment by RobertLowe** [comment]
@filipenevola ping, please review `HTTP` has essentially broken since https://github.com/meteor/meteor/pull/10518

**Comment by RobertLowe** [comment]
Expanding on this, the issue seems larger, noticed this elsewhere:

```
Exception while invoking method 'someMethod' TypeError: this._addDefaultFieldSelector is not a function
    at Object.user (packages/accounts-base/accounts_common.js:119:53)
    at MethodInvocation.someMethod (imports/api/server/methods/someMethod.js:7:5)
    at MethodInvocation.methodMap.<computed> (packages/afrokick_kadira.js:2725:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/afrokick_kadira.js:2616:38
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Session.sessionProto.protocol_handlers.method (packages/afrokick_kadira.js:2615:44)
    at packages/ddp-server/livedata_server.js:559:43
```

Really very odd https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L119

I'll try to make a reproduction of this one as well, but something is weird with `this`.

**Comment by filipenevola** [comment]
Thank you @RobertLowe, Published on url@1.3.1.

**Comment by RobertLowe** [comment]
@filipenevola can you verify the root cause of it? I have a suspicion it may exist in other packages that use the structure of calling `this.<function>`, it's an odd pattern, but the URL package hasn't been updated for 3 years... so what else could of broken?

**Comment by RobertLowe** [comment]
Scratch that, I now see the root cause: https://github.com/RobertLowe/meteor/blob/8077d5172498332b22504123aa067a08353039eb/packages/url/url_common.js#L9 was renamed to `var`, so it lost the context of URL.
