### ISSUE TITLE
[1.6.1] Cordova Android: Cannot find module 'dezalgo'

### ISSUE THREAD

**Issue by KoenLav** [meteor/meteor#9560]
After upgrading from Meteor 1.6.0 to 1.6.1 it seems the included cordova-lib in meteor-tool is outdated.

meteor run android-device leads to: Cannot find module 'dezalgo'

Going to meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\cordova-lib and running npm install fixes this issue for me.

Possibly/probably this is caused by the included package-lock.json in lib.

With regard to that: package-locks often seem to cause cross-platform issues, I know that's an npm issue, but does Meteor have a specific approach towards this?

**Comment by KoenLav** [comment]
Other than that I needed to accept a new license agreement for the Android SDK that is used for this particular release, but that's not a bug (just mentioning it here for reference).

Other than that Meteor 1.6.1 runs like a breeze, on web and Android.

**Comment by KoenLav** [comment]
When calling meteor run android-device Meteor will start adding Cordova to meteor-tool.

At some point it errors out while renaming cordova-lib\node_modules\npm\node_modules\ansistyles.

When I try running the command again I get 'cannot find module 'dezalgo'', running npm install in cordova-lib fixes it again.

**Comment by adooylabs** [comment]
@KoenLav - Thanks, that fixed it! For sure this will be fixed next release.

**Comment by wojtkowiak** [comment]
The same happens to me. Also on Appveyor, CircleCI and Travis it fails with:

https://travis-ci.org/wojtkowiak/meteor-desktop/jobs/335154353#L1141
https://ci.appveyor.com/project/wojtkowiak/meteor-desktop/build/1.0.448/job/j0a2l5ohel77g40k#L3571

After consecutive `add-platform` you will get `Cannot find module 'dezalgo'`

**Comment by dovydaskukalis** [comment]
Removing .meteor folder from home directory also fixes it.

**Comment by wojtkowiak** [comment]
@abernix any plans to work on it? Or at least idea why it fails? 

```
Error: Error: couldn't install npm package cordova-common@2.1.1: Command failed: /home/travis/.meteor/packages/meteor-tool/.1.6.1.9s0dj5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm install cordova-common@2.1.1
npm WARN enoent ENOENT: no such file or directory, open '/home/travis/.meteor/packages/meteor-tool/.1.6.1.9s0dj5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/package.json'
```
At least from npm I can see that it complains about package.json being missing. 
And the actual error is
```
npm ERR! path /home/travis/.meteor/packages/meteor-tool/.1.6.1.9s0dj5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/node-gyp/node_modules/cryptiles/node_modules/boom
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/travis/.meteor/packages/meteor-tool/.1.6.1.9s0dj5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/node-gyp/node_modules/cryptiles/node_modules/boom' -> '/home/travis/.meteor/packages/meteor-tool/.1.6.1.9s0dj5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/node-gyp/node_modules/cryptiles/node_modules/boom'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Did not spend much time on it, but it might be related to the fact the contents of dev bundle are prepared by different npm than is later used to add corodova. Maybe adding package.json would help... idk

**Comment by joseAndresGomezTovar** [comment]
@KoenLav - The same happens to me. Windows 10 x64 , Meteor 1.6.1 , android studio 3.0.1

**Comment by Gosselk** [comment]
@joseAndresGomezTovar Have you find a solution for this issue ? Because i'm stuck with the same issue

**Comment by joseAndresGomezTovar** [comment]
@Gosselk It's a known bug. There is no solution, yet

**Comment by marcoroche** [comment]
Same problem. Updated to 1.6.1 and stuck....

**Comment by Gosselk** [comment]
i have found this : 
`meteor npm i -g write-file-atomic path-is-inside async-some dezalgo`

it's work fine for add android and ios with `meteor add-platform android`

**Comment by marcoroche** [comment]
@Gosselk I applied your command and it works.  I have finally generated my App with Meteor 1.6.1

**Comment by abernix** [comment]
I hope the root problem here is fixed by a `cordova-lib` update (as in, this was fixed upstream), because the solution provided by @Gosselk in https://github.com/meteor/meteor/issues/9560#issuecomment-375150749 doesn't seem clear to me (even if it does work; though I haven't researched).

Has anyone made (or would anyone be willing to make) the attempt at checking to see if `cordova-lib` has specifically fixed this upstream?

It's possible to [Run Meteor from a checkout](https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md#running-from-a-git-checkout) and bump Cordova versions [here](https://github.com/meteor/meteor/blob/a3a19f94eb6059233a5564540fefb3952fe8fc92/tools/cordova/index.js#L10-L15).  After bumping the version, you'll want to delete the already-installed version in `dev_bundle/lib/node_modules/cordova-lib` (in the Meteor checkout) before attempting to run your application with `/path/to/meteor-checkout/meteor` in your application directory again.

**Comment by derwaldgeist** [comment]
Stuck after upgrading to 1.6.1 on macOS, too. :-/
