### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _node_module_register

### ISSUE THREAD

**Issue by alex42miranda** [meteor/meteor#7120]
I just installed the meteor framework (www.meteor.com) and I did what the QuickStart Says:

Once you’ve installed Meteor, create a project:

1 meteor create my app

Run it locally:

1 cd my app
2 meteor npm install
3 meteor
#//Meteor server running on: http://localhost:3000/

However I am getting this error:

=> Started proxy.                             
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/alexandremagnobezerramiranda/node_modules/kerberos/build/Release/kerberos.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/alexandremagnobezerramiranda/node_modules/kerberos/build/Release/kerberos.node
  Expected in: dynamic lookup

Trace/BPT trap: 5

So, I would like to know how do I solve this problem? Any Thoughts?

**Comment by abernix** [comment]
Are you sure you did *exactly* those three steps?  This really sounds like conflicting versions of Node being used to build your project versus the ones that are used for running your project.

Did you happen to run `npm install` before you ran `meteor npm install`? (This would cause problems).

I would try:
```
cd your_app_dir/
rm -rf node_modules/
meteor npm install
```

**Comment by abernix** [comment]
I'm guessing you've omitted some other steps you may have taken because the `kerberos` npm module would not have be installed by default.

**Comment by alex42miranda** [comment]
Ok Abernix. I will try it out right now. Thank you so much

**Comment by alex42miranda** [comment]
I did it again and I am getting the same error yet =/

**Comment by benjamn** [comment]
Though @abernix's advice should work, you may be able to avoid removing your entire `node_modules` directory by doing
```sh
cd your_app_dir
meteor npm rebuild
```

**Comment by abernix** [comment]
@alex42miranda Again, it seems you're doing something additional than what you've listed in this issue because `kerberos` wouldn't normally be installed on a fresh project so I don't know why it's working it's way into your project.  It leads me to believe that you're adding some other packages.  Please provide either:
* A link to a Git Repo where someone can clone and reproduce this.
* The *exact* steps you're taking to make this happen from a brand new project – or a link to the exact tutorial steps you're following.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)

**Comment by keyscores** [comment]
+1 still getting this when updating to 1.4.1. Already tried `meteor npm rebuild`. Any ideas?

W20160927-17:55:37.593(-4)? (STDERR) dyld: lazy symbol binding failed: Symbol not found: _node_module_register
W20160927-17:55:37.594(-4)? (STDERR)   Referenced from: /Users/LUCAS/.meteor/packages/npm-bcrypt/.0.8.5.1bury91++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/build/Release/bcrypt_lib.node
W20160927-17:55:37.594(-4)? (STDERR)   Expected in: dynamic lookup
W20160927-17:55:37.594(-4)? (STDERR)          
W20160927-17:55:37.594(-4)? (STDERR) dyld: Symbol not found: _node_module_register
W20160927-17:55:37.594(-4)? (STDERR)   Referenced from: /Users/LUCAS/.meteor/packages/npm-bcrypt/.0.8.5.1bury91++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules/bcrypt/build/Release/bcrypt_lib.node
W20160927-17:55:37.595(-4)? (STDERR)   Expected in: dynamic lookup
W20160927-17:55:37.595(-4)? (STDERR)          
=> Exited from signal: SIGTRAP

**Comment by zaklampert** [comment]
try removing the npm-bcrypt folder in `/Users/[username]/.meteor/packages`

**Comment by biswasaveek** [comment]
just doing npm rebuild solved the issue for me

**Comment by typpo** [comment]
I had this problem with bcrypt (`dyld: Symbol not found: _node_module_register`) following a [basic accounts tutorial](https://guide.meteor.com/accounts.html) word-for-word.  Clearing modules and re-installing did not work for me.  Neither did rebuilding.

In the end, I realized that I had an old version of meteor installed.  `meteor update`, followed by re-installing everything, fixed things.

**Comment by ryanmtaylor** [comment]
I just wanted to mention that I had this error, and while I'm sure upgrading would have worked, downgrading was necessary for my project.  It seems that the `npm-bcrypt@0.8` builds are problematic, usually this is fixed by `npm-bcrypt@0.8.7_1` but this did not work for me

```
     meteor add accounts-password@1.1.7
     meteor add npm-bcrypt@0.7.8_2
```
