### ISSUE TITLE
Meteor shell crashes server

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#8272]
Version: Meteor@1.4.2.3

Server starts and runs fine until I run `meteor shell`, then it crashes with:

```
var repl = self.repl = require("repl").start(options);
TypeError: require(...).start is not a function
```

`shell-server` (@0.2.1) is in `.meteor/packages`.

It works fine with Meteor@1.3.

**Comment by hwillson** [comment]
Hi @realyze - sorry to hear you're having trouble! Any chance you could create and link to a small runnable reproduction showing this problem, to help with troubleshooting? This issue hasn't been reported by anyone else, so it's likely a combination of things from your specific project. Cutting things down to the smallest reproduction possible might help track down the cause. Thanks!

**Comment by realyze** [comment]
@hwillson Thanks for the reply. I can try some time this week. Do you have any educated guesses as to what may be causing this so that I know where to look? (Our app where this happens is pretty big.)

**Comment by abernix** [comment]
@realyze This error would appear to be stemming from [this code](https://github.com/meteor/meteor/blob/devel/packages/shell-server/shell-server.js#L180) in `server-shell` (the Meteor package).  `repl` (the NPM module being `require'-d, is a part of the [core Node API](https://nodejs.org/api/repl.html) if `require('repl')` is returning `undefined` (as this error is suggesting), that points to a fairly significant failure.

I guess make sure that you're not somehow destroying that core module – for example, by defining your own `repl`?

**Comment by realyze** [comment]
Hmm, well, I'm positive we're not defining our own `repl` anywhere (in our code, that is). The funny thing is that 1.3 doesn't have this problem. If we redefined `repl`, I'd assume 1.3 would crash too.

**Comment by abernix** [comment]
@realyze A reproduction here might be as simple as copying your `.meteor/packages` to a blank project.  If you don't mind trying that in a reproduction that you could provide here, that would be the best way to move forward.

**Comment by hwillson** [comment]
Hi @realyze - any luck with putting together a reproduction? Also - does updating to Meteor 1.4.3.1 help? Since we haven't heard back in a while, I'll close this issue for now. Happy to re-open if you're able to post back with more details. Thanks!

**Comment by realyze** [comment]
@hwillson Sorry, I didn't have time to investigate yet (we're still on Meteor 1.3 but we plan to migrate in the weeks to come so I'm sure I'll hit this again and will be able to spend more time on it).

BTW I don't have this issue on my smaller project which uses meteor@1.4 so it's most definitely package-related.

**Comment by realyze** [comment]
@hwillson Sorry for the huge delay. I finally narrowed it down to `meteor-node-stubs` - when I `require`it in the code, shell server crashes.

**Comment by abernix** [comment]
Is there a reason that you're directly `require`-ing `meteor-node-stubs`?  The stubs are intended to be browser-based versions of core Node functions but designed to work in a client environment.  They are automatically included (when installed) in the client bundle thanks to the `modules` package and are not meant to be installed on the server.

**Comment by realyze** [comment]
Hmm, I have this vague memory we needed it to be able to require [Mingo](https://github.com/kofrasa/mingo) which wanted the stream API on the client...but it was rather a long time ago so I might be wrong. But we've started to use the `modules` package since so I guess we don't need it anymore. I'm pretty sure requiring it on the server was just a shared-code accident.
