### ISSUE TITLE
JS issue in 1.9-alpha.6 not present in 1.8.1

### ISSUE THREAD

**Issue by houshuang** [meteor/meteor#10600]
Compiling exactly the same code that works fine with 1.8.1 I get this console error in 1.9-alpha.6:

```js
modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:532466 Uncaught TypeError: (0 , _reactOnclickoutside2.default) is not a function
    at tokenContainer (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:532466)
    at Token.react.js (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:536823)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:268)
    at TypeaheadInputMulti.react.js (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:536153)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:268)
    at Typeahead.react.js (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:535454)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:268)
    at AsyncTypeahead.react.js (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:531958)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:268)
    at index.js (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:531877)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:268)
    at TypeaheadField.js (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:524879)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:268)
    at index.js (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:523715)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at Module.moduleLink [as link] (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:336)
    at EnhancedForm.js (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:440076)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:268)
    at index.js (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:436396)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at Module.moduleLink [as link] (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:336)
    at index.js (app.js?hash=50b5b77e05bc769a0f6100f6e4a1cfce9233317e:11005)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at Module.moduleLink [as link] (modules.js?hash=4fb2363bda18e5ea71e907140a2423660af38e58:336)
    at main.jsx (main.jsx:1)
    at fileEvaluate (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:346)
    at Module.require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:248)
    at require (modules-runtime.js?hash=0ba1f02e48d68e39631c5674a06607fabab6101e:268)
    at app.js?hash=50b5b77e05bc769a0f6100f6e4a1cfce9233317e:21802
```

My initial thought is that this could be due to a circular dependency and perhaps the bundling logic is changed from 1.8.1 to 1.9-alpha.6, however it's a bit weird that it's happening in a dependency and not in my core code.

Example code in https://github.com/chili-epfl/FROG branch minimal1.9 (run ./initial_setup.sh first, then npm start server).

**Comment by aliogaili** [comment]
I also has missing modules, in my case it was react-trello.

> it's a bit weird that it's happening in a dependency and not in my core code.

I think it's because in 1.8.2 Meteor is attempting to transpile the node_modules folder in addition to app code, I think Benjamin is looking into this.

**Comment by benjamn** [comment]
@houshuang That specific issue should be fixed by https://github.com/benjamn/reify/commit/7d8b85a1bc3b4d8605e9fee2319e0a6db7c1f981 in the next beta release of Meteor 1.8.2.

**Comment by houshuang** [comment]
I can confirm that this has been resolved in 1.8.2-beta.13. Thanks.
