### ISSUE TITLE
Error: Cannot find module '@babel/runtime/helpers/builtin/objectSpread' after updating meteor packages

### ISSUE THREAD

**Issue by Luke-Tan** [meteor/meteor#9777]
Hi, fairly new to meteor. I recently ran meteor update --all-packages, updating the following things:
![screen shot 2018-03-29 at 3 42 34 pm](https://user-images.githubusercontent.com/4784866/38076424-2424b0fe-3368-11e8-9282-5266b895a612.png)
However, my app now crashes giving the following errors:
![screen shot 2018-03-29 at 3 42 52 pm](https://user-images.githubusercontent.com/4784866/38076444-33ed34ca-3368-11e8-800f-95b3a416c30d.png)
Does anyone know what is going on? I figured I would try downgrading some of the updated packages but im not sure how I would go about doing that. Thanks!

**Comment by Luke-Tan** [comment]
Downgraded meteor, babel-compiler and ddpclient with meteor add <package_name>@=<old_version>,
the error is still there...

**Comment by Luke-Tan** [comment]
I tried making a new meteor project and adding that projects objectSpread module into my original project... still returns the same error. I have absolutely no idea what is going on

**Comment by Luke-Tan** [comment]
I fixed this by creating a new project and transferring the objectSpread module from that project into my current project.. Could anyone still explain to me what just happened?

**Comment by mkorban** [comment]
I have a some problem after update to 1.6.1.1

**Comment by mkorban** [comment]
@Luke-Tan How to you do it?

**Comment by Luke-Tan** [comment]
Update your @babel/runtime by running the following while inside your project folder:
meteor npm install —save @babel/runtime

**Comment by Luke-Tan** [comment]
Update your Babel runtime by running:
`meteor npm install —save @babel/runtime`

**Comment by Luke-Tan** [comment]
Update your Babel runtime by running
meteor npm install ―save @babel/runtime
Inside your project folder

**Comment by benjamn** [comment]
There have been some breaking changes in recent versions of Babel 7 beta. As @Luke-Tan has suggested, the solution here is to run
```sh
meteor npm install --save @babel/runtime@latest
```

**Comment by dovydaskukalis** [comment]
Updating to latest Babel (7.0.0-beta.44) and running Meteor throws

```
/.meteor/local/build/programs/server/boot.js:475
 }).run();
Error: Cannot find module './defineProperty'
at makeMissingError (packages/modules-runtime.js:231:12)
at require (packages/modules-runtime.js:241:19)
 at objectSpread.js (packages/modules.js:17530:22)
at fileEvaluate (packages/modules-runtime.js:343:9)
at require (packages/modules-runtime.js:238:16)
at livedata_connection.js (/.meteor/local/build/programs/server/packages/ddp-client.js:149:45)
at fileEvaluate (packages/modules-runtime.js:343:9)
at require (packages/modules-runtime.js:238:16)
at namespace.js (packages/ddp-client/common/namespace.js:1:300)
at fileEvaluate (packages/modules-runtime.js:343:9)
```

Can't find a way to fix it apart from reverting back to Meteor 1.6.1

**Comment by jfols** [comment]
I'm experiencing issues here too: successful build, throws an error at first spread attempt:
```
app.js?hash=8c3e74f441484da7a2382445828181ea26630fd4:4235 Uncaught TypeError: Invalid attempt to spread non-iterable instance
    at _nonIterableSpread (app.js?hash=8c3e74f441484da7a2382445828181ea26630fd4:4235)
    at _toConsumableArray (app.js?hash=8c3e74f441484da7a2382445828181ea26630fd4:4233)
    at index.js (index.js:66)
    at fileEvaluate (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:353)
    at require (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:248)
    at main.js (main.js:1)
    at fileEvaluate (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:353)
    at require (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:248)
    at app.js?hash=8c3e74f441484da7a2382445828181ea26630fd4:5112
```

`meteor npm install --save @babel/runtime@latest` has no effect, already successfully on `7.0.0-beta.44` with v1.6.1.

**Comment by dovydaskukalis** [comment]
@jfols Make sure you don't try to spread undefined value.

**Comment by jfols** [comment]
@dovydaskukalis for sure, doubled checked and I'm attempting to spread an `object`

**Comment by neopostmodern** [comment]
I had the same issue as pointed out in https://github.com/meteor/meteor/issues/9777#issuecomment-378583359

> I had babel/runtime module in devDependencies. Moving to dependencies fixed it.

Could this hint be added to https://github.com/meteor/meteor/blob/devel/History.md#v1611-2018-04-02 ? (Yes, it simply says "install" — but one always thinks themself more intelligent, so an explicit comment might help)
