### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by dgreensp** [meteor/meteor#4943]
We're excited to announce the first public release candidate of Meteor 1.2, which is now ready for early testing.  We have some more QA to do, but we wanted to get it in your hands as soon as possible.  You can upgrade your app using:

```
meteor update --release METEOR@1.2-rc.12
```

Meteor 1.2 is the biggest new release of Meteor ever! Highlights include:

* Faster application rebuild times, thanks to a new plugin architecture
* Built-in support for ES6/ES2015 JavaScript features
* Cross-package LESS and Stylus imports
* Upgrades to Cordova mobile support
* Official support for React and Angular as view layer alternatives to Blaze

The biggest things to keep in mind with the upgrade process are:

* Upgrading to a 1.2 RC will modify your .meteor/packages file.  When switching back to a previous version of Meteor, you'll need to revert this change in your source control.

* Package authors: Packages that depend on Meteor 1.2's versions of coffeescript, less, stylus, or templating, or that use the new ecmascript or static-html packages, will only work with Meteor 1.2 or later, which is enforced by the constraint solver.  In addition, we had to bump the major versions of less and stylus in order to enable cross-package imports, so if your package contains LESS or Stylus files, you'll have to re-publish using the 2.x versions of these packages to make your package 1.2-compatible (breaking compatibility with previous versions of Meteor).

See the [Meteor 1.2 Upgrade Guide](https://quip.com/RXFlAk9Rc2xI) for more details. We will continue to revise the Upgrade Guide between now and final release.

Release-blocking bugs will be tracked in the [Release 1.2 milestone](https://github.com/meteor/meteor/milestones/Release%201.2).

Thanks everyone!  Reply with feedback in this thread.

**Comment by woniesong92** [comment]
@stubailo may I ask what the current status for this release is?

**Comment by stubailo** [comment]
We are hoping to release a testable RC soon!

**Comment by lorensr** [comment]
And according to Monday's blog post, full release ETA is September.

**Comment by bySabi** [comment]
WOW `rc-6` really fast here. Much more than `rc-4`
thanks!! Good work!!

**Comment by woniesong92** [comment]
with `rc-7` I get the following error:

* These packages have been updated to new versions that are not backwards
compatible.

```                                          
/Users/appPath/meteor/tools/utils/fiber-helpers.js:168
    }).run();
       ^
Error: Cannot find module 'cli-color'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object._.extend.Npm.require (/tools/isobuild/bundler.js:1266:22)
    at prettify (packages/logging/logging.js:263:1)
    at Function.Log.format (packages/logging/logging.js:266:1)
    at [object Object]._.extend.logAppOutput (/tools/runners/run-log.js:98:27)
    at Transformer.<anonymous> (/tools/runners/run-app.js:97:16)
    at /tools/utils/fiber-helpers.js:158:12
```

**Comment by dgreensp** [comment]
@woniesong92 Can you give us more information to help us reproduce?  What command did you run, and do you get this error repeatably?

**Comment by woniesong92** [comment]
@dgreensp Of course.

`meteor-devel` points at a cloned Meteor's latest commit of the branch `release-1.2`.

```
$ meteor-devel --version
Unreleased, running from a checkout at 3d6cb90 (HEAD, tag: release/METEOR@1.2-rc.7, origin/release-1.2, release-1.2)

$ meteor-devel 
=> Running Meteor from a checkout -- overrides project version (Meteor 1.1.0.3)
[[[[[ ~/myPath ]]]]]                         

=> Started proxy.                             
=> Started MongoDB.                           
                                              
Changes to your project's package version selections:
                                              
accounts-base           upgraded from 1.2.0 to 1.2.1-rc.1
accounts-password       upgraded from 1.1.1 to 1.1.2-rc.1
accounts-ui             upgraded from 1.1.5 to 1.1.6-rc.0
accounts-ui-unstyled    upgraded from 1.1.7 to 1.1.8-rc.0
autoupdate              upgraded from 1.2.1 to 1.2.3-rc.1
babel-compiler          added, version 5.8.22-rc.0
babel-runtime           added, version 0.1.4-rc.0
base64                  upgraded from 1.0.3 to 1.0.4-rc.0
binary-heap             upgraded from 1.0.3 to 1.0.4-rc.0
blaze                   upgraded from 2.1.2 to 2.1.3-rc.0
blaze-tools             upgraded from 1.0.3 to 1.0.4-rc.0
boilerplate-generator   upgraded from 1.0.3 to 1.0.4-rc.0
caching-compiler        added, version 1.0.0-rc.0
caching-html-compiler   added, version 1.0.1-rc.0
callback-hook           upgraded from 1.0.3 to 1.0.4-rc.0
check                   upgraded from 1.0.5 to 1.0.6-rc.0
coffeescript            upgraded from 1.0.6 to 1.0.8-rc.2
ddp                     upgraded from 1.1.0 to 1.2.1-rc.0
ddp-client              added, version 1.2.1-rc.1
ddp-common              added, version 1.2.1-rc.0
ddp-rate-limiter        added, version 1.0.0-rc.0
ddp-server              added, version 1.2.1-rc.1
deps                    upgraded from 1.0.7 to 1.0.8-rc.0
diff-sequence           added, version 1.0.1-rc.0
ecmascript              added, version 0.1.3-rc.1
ecmascript-collections  added, version 0.1.5-rc.1
ejson                   upgraded from 1.0.6 to 1.0.7-rc.0
email                   upgraded from 1.0.6 to 1.0.7-rc.0
fastclick               upgraded from 1.0.3 to 1.0.7-rc.0
geojson-utils           upgraded from 1.0.3 to 1.0.4-rc.0
html-tools              upgraded from 1.0.4 to 1.0.5-rc.0
htmljs                  upgraded from 1.0.4 to 1.0.5-rc.1
http                    upgraded from 1.1.0 to 1.1.1-rc.1
id-map                  upgraded from 1.0.3 to 1.0.4-rc.0
jquery                  upgraded from 1.11.3_2 to 1.11.4-rc.0
json                    removed from your project
launch-screen           upgraded from 1.0.2 to 1.0.3-rc.1
less*                   upgraded from 1.0.14 to 2.5.0-rc.2_1
livedata                upgraded from 1.0.13 to 1.0.14-rc.0
localstorage            upgraded from 1.0.3 to 1.0.4-rc.0
logging                 upgraded from 1.0.7 to 1.0.8-rc.1
meteor                  upgraded from 1.1.6 to 1.1.7-rc.1
meteor-platform         upgraded from 1.2.2 to 1.2.3-rc.0
minifiers               upgraded from 1.1.5 to 1.1.6-rc.1
minimongo               upgraded from 1.0.8 to 1.0.9-rc.0
mobile-status-bar       upgraded from 1.0.3 to 1.0.5-rc.1
mongo                   upgraded from 1.1.0 to 1.1.1-rc.2
mongo-id                added, version 1.0.1-rc.0
npm-mongo               added, version 1.4.39-rc.0_1
observe-sequence        upgraded from 1.0.6 to 1.0.7-rc.0
ordered-dict            upgraded from 1.0.3 to 1.0.4-rc.0
promise                 added, version 0.4.8-rc.0
random                  upgraded from 1.0.3 to 1.0.4-rc.0
rate-limit              added, version 1.0.0-rc.0
reactive-dict           upgraded from 1.1.0 to 1.1.1-rc.0
reactive-var            upgraded from 1.0.5 to 1.0.6-rc.0
reload                  upgraded from 1.1.3 to 1.1.4-rc.0
retry                   upgraded from 1.0.3 to 1.0.4-rc.0
routepolicy             upgraded from 1.0.5 to 1.0.6-rc.0
service-configuration   upgraded from 1.0.4 to 1.0.5-rc.0
session                 upgraded from 1.1.0 to 1.1.1-rc.0
sha                     upgraded from 1.0.3 to 1.0.4-rc.0
spacebars               upgraded from 1.0.6 to 1.0.7-rc.0
spacebars-compiler      upgraded from 1.0.6 to 1.0.7-rc.0
srp                     upgraded from 1.0.3 to 1.0.4-rc.0
templating              upgraded from 1.1.1 to 1.1.2-rc.3
templating-tools        added, version 1.0.0-rc.0
tracker                 upgraded from 1.0.7 to 1.0.8-rc.0
ui                      upgraded from 1.0.6 to 1.0.7-rc.0
underscore              upgraded from 1.0.3 to 1.0.4-rc.0
url                     upgraded from 1.0.4 to 1.0.5-rc.0
webapp                  upgraded from 1.2.0 to 1.2.2-rc.1
webapp-hashing          upgraded from 1.0.3 to 1.0.4-rc.0

                                              
* These packages have been updated to new versions that are not backwards
compatible.
                                              
/Users/name/meteorBleedingEdge/meteor/tools/utils/fiber-helpers.js:168
    }).run();
       ^
Error: Cannot find module 'cli-color'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object._.extend.Npm.require (/tools/isobuild/bundler.js:1266:22)
    at prettify (packages/logging/logging.js:263:1)
    at Function.Log.format (packages/logging/logging.js:266:1)
    at [object Object]._.extend.logAppOutput (/tools/runners/run-log.js:98:27)
    at Transformer.<anonymous> (/tools/runners/run-app.js:108:14)
    at /tools/utils/fiber-helpers.js:158:12
```

This error happens as soon as I switch to the latest version from the stable Meteor 1.1.0.3 version. Once I switch back, the app runs fine.

```
$ meteor --version
Meteor 1.1.0.3

$ meteor
[[[[[ ~/appName ]]]]]                         

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

**Comment by dgreensp** [comment]
Ok, see update at top of thread, it's official guys!

**Comment by dgreensp** [comment]
@woniesong92 Ah, that's helpful, thanks.  (Still not sure what's going on.)  Could I trouble you to open a separate issue and paste that in?

**Comment by woniesong92** [comment]
@dgreensp Instead of using a cloned version, I ran `meteor update --release METEOR@1.2-rc.7` and the app was built without a problem!

**Comment by dgreensp** [comment]
Hmm, weird!

**Comment by woniesong92** [comment]
Started a new issue #5049. Running the latest release version failed on an iPhone. Do you mind checking out what's going on?

**Comment by LarsBuur** [comment]
Upgraded from 1.1.0.3 to 1.2-rc.7. 

To problems: 

The meteor list reports that the "logging" package can be updated so I tried to update. 

The update process fails with the following error.

```
meteor update
This project is already at Meteor 1.2-rc.7, which is newer than the latest release.
=> Errors while upgrading packages:

While selecting package versions:
error: unknown package: isobuild:compiler-plugin
Required by: meteor 1.1.7-rc.1
Required by: ecmascript 0.1.3-rc.1
Required by: templating 1.1.2-rc.3
Required by: coffeescript 1.0.8-rc.2

unknown package: isobuild:isopack-2
Required by: ecmascript 0.1.3-rc.1
Required by: ddp-server 1.2.1-rc.1
Required by: accounts-base 1.2.1-rc.1
Required by: caching-compiler 1.0.0-rc.0
Required by: templating-tools 1.0.0-rc.0
Required by: caching-html-compiler 1.0.1-rc.0
Required by: templating 1.1.2-rc.3
Required by: facebook 1.2.2-rc.0
Required by: google 1.1.6-rc.0
Required by: accounts-base 1.2.1-rc.1
Required by: facts 1.0.5-rc.0

unknown package: isobuild:minifier-plugin
Required by: standard-minifiers 1.0.0-rc.1
```

The app runs without error - but the accounts-base/accounts-password login system has stopped working which is strange but could be related to the above error. 

Second issue is that I tried to remove the "flemay:less-autoprefixer" to utilize the native less support. This did not happen - and I will have to look into that.

This is the current packages loaded in the app I am working on.

```
meteor list
accounts-base               1.2.1-rc.1  A user account system
accounts-facebook           1.0.5-rc.0  Login service for Facebook accounts
accounts-google             1.0.5-rc.0  Login service for Google accounts
accounts-password           1.1.2-rc.1  Password support for accounts
alanning:roles              1.2.13  Role-based authorization
amplify                     1.0.0  API for Persistent Storage, PubSub and Request
audit-argument-checks       1.0.4-rc.0  Try to detect inadequate input sanitization
babrahams:constellation     0.1.3  A curated set of packages for Constellation
blaze-html-templates        1.0.1-rc.0  Compile HTML templates into reactive UI with Meteor Blaze
check                       1.0.6-rc.0  Check whether a value matches a pattern
chrismbeckett:toastr        2.1.2_1  Gnome / Growl type non-blocking notifications
constellation:schema        0.3.4  Schema generator plugin for Constellation
ejson                       1.0.7-rc.0  Extended and Extensible JSON library
facts                       1.0.5-rc.0  Publish internal app statistics
flemay:less-autoprefixer    1.1.0  The dynamic stylesheet language + Autoprefixer
flyandi:reactive-countdown  0.0.3  A simple reactive countdown timer for Meteor
http                        1.1.1-rc.1  Make HTTP calls to remote servers
iron:router                 1.0.9  Routing specifically designed for Meteor
jparker:crypto-hmac         0.1.0  HMAC function for CryptoJS, standard secure crypto algorithms
jparker:crypto-sha1         0.1.0  SHA1 algo for CryptoJS, standard secure crypto algorithms
jquery                      1.11.4-rc.0  Manipulate the DOM using CSS selectors
larsbuur:moment             2.9.1+ Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
larsbuur:numeral            1.5.5+ Package to wrap Numeral-js, a library for formatting and manipulating numbers
logging                     1.0.8-rc.1* Logging facility.
markdown                    1.0.5-rc.0  Markdown-to-HTML processor
meteor-base                 1.0.1-rc.0  Packages that every Meteor app needs
meteor-tablesorter          0.0.0+ tablesorter is a jQuery plugin for turning a standard HTML table with THEAD and TBODY tags into a so...
meteorhacks:aggregate       1.3.0  Proper MongoDB aggregations support for Meteor
meteorhacks:kadira          2.23.0  Performance Monitoring for Meteor
meteorhacks:npm             1.4.0  Use npm modules with your Meteor App
mobile-experience           1.0.1-rc.0  Packages for a great mobile user experience
mongo                       1.1.1-rc.2  Adaptor for using MongoDB and Minimongo over DDP
mrt:cookies                 0.3.0  Basic cookies support for client
mrt:highcharts              0.1.0  Easily create charts with Highcharts.
ongoworks:speakingurl       5.0.1  Generate a slug. Wraps the speakingurl package for Meteor
percolate:momentum          0.5.2+ Reactive animations
pfafman:epoch               0.6.0  Epoch charts packaged for Meteor
random                      1.0.4-rc.0  Random number generator and utilities
reactive-var                1.0.6-rc.0  Reactive variable
reload                      1.1.4-rc.0  Reload the page while preserving application state.
reywood:iron-router-ga      0.6.1  Google analytics (universal edition) with some Iron Router sugar for tracking page views.
richsilv:pikaday            1.0.1+ Pikaday JavaScript Datepicker for Meteor — lightweight, no dependencies, modular CSS
sacha:spin                  2.3.1  Simple spinner package for Meteor
semantic:ui                 2.0.8  Official Semantic UI Integration for Meteor
service-configuration       1.0.5-rc.0  Manage the configuration for third-party services
session                     1.1.1-rc.0  Session variable
spacebars                   1.0.7-rc.0  Handlebars-like template language for Meteor
standard-minifiers          1.0.0-rc.1  Standard minifiers used with Meteor apps by default.
tap:i18n                    1.5.1  A comprehensive internationalization solution for Meteor
tracker                     1.0.8-rc.0  Dependency tracker to allow reactive callbacks
vsivsi:job-collection       1.2.2  A persistent and reactive job queue for Meteor, supporting distributed workers that can run anywhere


* New versions of these packages are available! Run 'meteor update' to try to update those packages to their latest versions. If your
  packages cannot be updated further, try typing `meteor add <package>@<newVersion>` to see more information.

+ These packages are built locally from source.
```

I have reverted back to 1.1.0.3 for now. Please let me know if you need additional info. I will be happy to assist.

**Comment by dgreensp** [comment]
@LarsBuur Ah, this something we ran into too.  Tracking it as #5054.

**Comment by sebakerckhof** [comment]
Not necessarily an issue, but what would be the equivalent of compileStep.pathForSourceMap in 1.2?

**Comment by dgreensp** [comment]
@sebakerckhof `file.getDisplayPath()`

**Comment by raix** [comment]
I'm getting an infinite "client update" sometimes - 1.2-rc.7 mac - I'm guessing it could be a watch loop?
```bash
=> App running at: http://localhost:3000/
=> Client modified -- refreshing (x440)^C
```

**Comment by evenfrost** [comment]
Still no lodash support?

**Comment by Kestanous** [comment]
still +1 for lodash :smiley_cat:

**Comment by bySabi** [comment]
:+1: lodash please

**Comment by elidoran** [comment]
Is there a way to get the Meteor release version inside `package.js` ? `Meteor.release` isn't available.

**Comment by elidoran** [comment]
For the Build Plugin API, the name of the package's directory (and the path to it) is hard to get a hold of. And, it has two different versions, `getDisplayPath()` uses an underscore and `getPackageName()` uses a colon.

They both can be used to piece together the folder name. Below is one example:

```coffeescript
# calling inputFile.getPackageName()
#   for an app file I get:   null
#   for package folder 'browserify-example' I get:   cosmos:browserify-example
packageName = inputFile.getPackageName() 

if packageName?
  index = packageName.indexOf(':') + 1
  packageName = packageName[index...]
else
  packageName = 'npm-container'  # use meteorhacks:npm for app scope

# result pieced back together once I have the directory name
"packages/#{packageName}/.npm/package"
```

The `inputFile.getDisplayPath()`: 
  `/packages/cosmos_browserify-example/client1.browserify.js`.

It seems like I should be able to do:

```coffeescript
# app returns null still
packageDir = inputFile.getPackageDir() ? 'npm-container'
"packages/#{packageDir}/.npm/package"
 ``` 

And, I suppose I'll always have to test for package name and look in npm-container because NPM isn't supported at the app level. It would be nice to have that support and do this instead:

```coffeescript
# for an app: ''
# for a package: packages/packageDirName/
inputFile.getParentDir() + '.npm/package' 
```

**Comment by dgreensp** [comment]
There's a new RC to try.  Update with:

```
meteor update --release METEOR@1.2-rc.12
```

Fixes between RC 7 and RC 12:

* Fix `meteor update` when running an RC (#5054)
* Fix client refreshing (#5074)
* Fix to `bare` option to `api.addFiles` (#4817)
* Can add a file as source and asset (#5040)

**API change**: Use `api.addAssets` instead of `api.addFiles` for adding assets.  The arguments are the same.  Having two separate functions results in a cleaner API.

**Comment by rclai** [comment]
Just to confirm, `{ isAsset: true }` will no longer work?

**Comment by dgreensp** [comment]
@rclai Yes, `{isAsset: true}` is deprecated.

**Comment by dgreensp** [comment]
@elidoran Have you read this section on accessing the file system from a plugin? https://github.com/meteor/meteor/wiki/Build-Plugins-API#accessing-file-system

**Comment by stubailo** [comment]
@rclai you do get a nice error if you use it, though, and it doesn't affect published packages. Just local packages and ones that you publish from now on.

**Comment by elidoran** [comment]
@dgreensp Yes. :) I read that page a million times trying to figure out how to use the new build API stuff.

Subclassing CachingCompiler was the easy part and was straightforward. The related functions were explained and made sense. And, looking at the coffeescript package helped.

I think a more detailed section on setting up the package.js for a build plugin, and a section on testing a build plugin, would be helpful. Perhaps with a complete functioning example.

What I took from the 'accessing the file system' part is to use `Plugin.fs` instead of `fs`, and, continue using unix paths as the standard path format. Which is great. It just doesn't help get the name of the package's directory on the file system which I need in this new build api because path resolution is done from the root of the app (well, the meteor tool's CWD, which better be the root of the app now or trouble occurs).

**Comment by sebakerckhof** [comment]
I'm getting these failed unlink crashes very frequently in windows with 1.2: https://github.com/meteor/meteor/issues/4933

**Comment by DavideCan** [comment]
Getting an error running on android-device: <a href="https://github.com/meteor/meteor/issues/5134">#5134</a>

**Comment by stubailo** [comment]
Just released 1.2-rc.14, with some fixes. Mostly these are things where we have responded "will be released in the next RC". Also, it should work a lot better on Windows now.

**Comment by LarsBuur** [comment]
Something strange is happening when upgrading from RC10 to RC11. 

I tried to update to rc14 this morning but it did not work and I got a "This project is at the latest release which is compatible with your current package constraints."

So I reverted to RC7 and to the updates one by one. The error happens after RC10.

```
pathx:app user$ meteor update --release METEOR@1.2-rc.7

Changes to your project's package version selections from updating the release:

accounts-base           upgraded from 1.2.0 to 1.2.1-rc.1
accounts-facebook       upgraded from 1.0.4 to 1.0.5-rc.0
accounts-google         upgraded from 1.0.4 to 1.0.5-rc.0
accounts-oauth          upgraded from 1.1.5 to 1.1.6-rc.0
accounts-password       upgraded from 1.1.1 to 1.1.2-rc.1
audit-argument-checks   upgraded from 1.0.3 to 1.0.4-rc.0
autoupdate              upgraded from 1.2.1 to 1.2.3-rc.1
babel-compiler          added, version 5.8.22-rc.0
babel-runtime           added, version 0.1.4-rc.0
base64                  upgraded from 1.0.3 to 1.0.4-rc.0
binary-heap             upgraded from 1.0.3 to 1.0.4-rc.0
blaze                   upgraded from 2.1.2 to 2.1.3-rc.0
blaze-tools             upgraded from 1.0.3 to 1.0.4-rc.0
boilerplate-generator   upgraded from 1.0.3 to 1.0.4-rc.0
caching-compiler        added, version 1.0.0-rc.0
caching-html-compiler   added, version 1.0.1-rc.0
callback-hook           upgraded from 1.0.3 to 1.0.4-rc.0
check                   upgraded from 1.0.5 to 1.0.6-rc.0
coffeescript            upgraded from 1.0.6 to 1.0.8-rc.2
ddp                     upgraded from 1.1.0 to 1.2.1-rc.0
ddp-client              added, version 1.2.1-rc.1
ddp-common              added, version 1.2.1-rc.0
ddp-rate-limiter        added, version 1.0.0-rc.0
ddp-server              added, version 1.2.1-rc.1
deps                    upgraded from 1.0.7 to 1.0.8-rc.0
diff-sequence           added, version 1.0.1-rc.0
ecmascript              added, version 0.1.3-rc.1
ecmascript-collections  added, version 0.1.5-rc.1
ejson                   upgraded from 1.0.6 to 1.0.7-rc.0
email                   upgraded from 1.0.6 to 1.0.7-rc.0
facebook                upgraded from 1.2.1 to 1.2.2-rc.0
facts                   upgraded from 1.0.4 to 1.0.5-rc.0
fastclick               upgraded from 1.0.3 to 1.0.7-rc.0
geojson-utils           upgraded from 1.0.3 to 1.0.4-rc.0
google                  upgraded from 1.1.5 to 1.1.6-rc.0
html-tools              upgraded from 1.0.4 to 1.0.5-rc.0
htmljs                  upgraded from 1.0.4 to 1.0.5-rc.1
http                    upgraded from 1.1.0 to 1.1.1-rc.1
id-map                  upgraded from 1.0.3 to 1.0.4-rc.0
jquery                  upgraded from 1.11.3_2 to 1.11.4-rc.0
json                    removed from your project
launch-screen           upgraded from 1.0.2 to 1.0.3-rc.1
livedata                upgraded from 1.0.13 to 1.0.14-rc.0
localstorage            upgraded from 1.0.3 to 1.0.4-rc.0
logging                 upgraded from 1.0.7 to 1.0.8-rc.1
markdown                upgraded from 1.0.4 to 1.0.5-rc.0
meteor                  upgraded from 1.1.6 to 1.1.7-rc.1
meteor-platform         upgraded from 1.2.2 to 1.2.3-rc.0
minifiers               upgraded from 1.1.5 to 1.1.6-rc.1
minimongo               upgraded from 1.0.8 to 1.0.9-rc.0
mobile-status-bar       upgraded from 1.0.3 to 1.0.5-rc.1
mongo                   upgraded from 1.1.0 to 1.1.1-rc.2
mongo-id                added, version 1.0.1-rc.0
mongo-livedata          upgraded from 1.0.8 to 1.0.9-rc.0
npm-mongo               added, version 1.4.39-rc.0_1
oauth                   upgraded from 1.1.4 to 1.1.6-rc.2
oauth2                  upgraded from 1.1.3 to 1.1.4-rc.0
observe-sequence        upgraded from 1.0.6 to 1.0.7-rc.0
ordered-dict            upgraded from 1.0.3 to 1.0.4-rc.0
promise                 added, version 0.4.8-rc.0
random                  upgraded from 1.0.3 to 1.0.4-rc.0
rate-limit              added, version 1.0.0-rc.0
reactive-dict           upgraded from 1.1.0 to 1.1.1-rc.0
reactive-var            upgraded from 1.0.5 to 1.0.6-rc.0
reload                  upgraded from 1.1.3 to 1.1.4-rc.0
retry                   upgraded from 1.0.3 to 1.0.4-rc.0
routepolicy             upgraded from 1.0.5 to 1.0.6-rc.0
service-configuration   upgraded from 1.0.4 to 1.0.5-rc.0
session                 upgraded from 1.1.0 to 1.1.1-rc.0
sha                     upgraded from 1.0.3 to 1.0.4-rc.0
spacebars               upgraded from 1.0.6 to 1.0.7-rc.0
spacebars-compiler      upgraded from 1.0.6 to 1.0.7-rc.0
srp                     upgraded from 1.0.3 to 1.0.4-rc.0
templating              upgraded from 1.1.1 to 1.1.2-rc.3
templating-tools        added, version 1.0.0-rc.0
tracker                 upgraded from 1.0.7 to 1.0.8-rc.0
ui                      upgraded from 1.0.6 to 1.0.7-rc.0
underscore              upgraded from 1.0.3 to 1.0.4-rc.0
url                     upgraded from 1.0.4 to 1.0.5-rc.0
webapp                  upgraded from 1.2.0 to 1.2.2-rc.1
webapp-hashing          upgraded from 1.0.3 to 1.0.4-rc.0

app: updated to Meteor 1.2-rc.7.
pathx:app user$ meteor update --release METEOR@1.2-rc.14
This project is at the latest release which is compatible with your current package constraints.
pathx:app user$ meteor update --release METEOR@1.2-rc.8

Changes to your project's package version selections from updating the release:

accounts-base         upgraded from 1.2.1-rc.1 to 1.2.1-rc.2
blaze-html-templates  added, version 1.0.1-rc.0
hot-code-push         added, version 1.0.0-rc.0
meteor-base           added, version 1.0.1-rc.0
meteor-platform       removed from your project
mobile-experience     added, version 1.0.1-rc.0
standard-minifiers    added, version 1.0.0-rc.1

app: updated to Meteor 1.2-rc.8.
pathx:app user$ meteor update --release METEOR@1.2-rc.9
app: updated to Meteor 1.2-rc.9.
pathx:app user$ meteor update --release METEOR@1.2-rc.10

Changes to your project's package version selections from updating the release:

webapp  upgraded from 1.2.2-rc.1 to 1.2.2-rc.2

app: updated to Meteor 1.2-rc.10.
pathx:app user$ meteor update --release METEOR@1.2-rc.11
This project is at the latest release which is compatible with your current package constraints.
pathx:app user$
```

How can I tell which package is causing my troubles?

This is the current package list from "meteor list"

```
accounts-base               1.2.1-rc.2* A user account system
accounts-facebook           1.0.5-rc.0  Login service for Facebook accounts
accounts-google             1.0.5-rc.0  Login service for Google accounts
accounts-password           1.1.2-rc.1  Password support for accounts
alanning:roles              1.2.13  Role-based authorization
amplify                     1.0.0  API for Persistent Storage, PubSub and Request
audit-argument-checks       1.0.4-rc.0  Try to detect inadequate input sanitization
blaze-html-templates        1.0.1-rc.0  Compile HTML templates into reactive UI with Meteor Blaze
check                       1.0.6-rc.0  Check whether a value matches a pattern
chrismbeckett:toastr        2.1.2_1  Gnome / Growl type non-blocking notifications
ejson                       1.0.7-rc.0  Extended and Extensible JSON library
facts                       1.0.5-rc.0  Publish internal app statistics
flemay:less-autoprefixer    1.1.0  The dynamic stylesheet language + Autoprefixer
flyandi:reactive-countdown  0.0.3  A simple reactive countdown timer for Meteor
http                        1.1.1-rc.1  Make HTTP calls to remote servers
iron:router                 1.0.9  Routing specifically designed for Meteor
jparker:crypto-hmac         0.1.0  HMAC function for CryptoJS, standard secure crypto algorithms
jparker:crypto-sha1         0.1.0  SHA1 algo for CryptoJS, standard secure crypto algorithms
jquery                      1.11.4-rc.0  Manipulate the DOM using CSS selectors
larsbuur:moment             2.9.1+ Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
larsbuur:numeral            1.5.5+ Package to wrap Numeral-js, a library for formatting and manipulating numbers
logging                     1.0.8-rc.1* Logging facility.
markdown                    1.0.5-rc.0  Markdown-to-HTML processor
meteor-base                 1.0.1-rc.0  Packages that every Meteor app needs
meteor-tablesorter          0.0.0+ tablesorter is a jQuery plugin for turning a standard HTML table with THEAD and TBODY tags into a sortable t...
meteorhacks:aggregate       1.3.0  Proper MongoDB aggregations support for Meteor
meteorhacks:kadira          2.23.2  Performance Monitoring for Meteor
meteorhacks:npm             1.5.0  Use npm modules with your Meteor App
mobile-experience           1.0.1-rc.0  Packages for a great mobile user experience
mongo                       1.1.1-rc.2* Adaptor for using MongoDB and Minimongo over DDP
mrt:cookies                 0.3.0  Basic cookies support for client
mrt:highcharts              0.1.0  Easily create charts with Highcharts.
ongoworks:speakingurl       5.0.1  Generate a slug. Wraps the speakingurl package for Meteor
percolate:momentum          0.5.2+ Reactive animations
pfafman:epoch               0.6.0  Epoch charts packaged for Meteor
random                      1.0.4-rc.0  Random number generator and utilities
reactive-var                1.0.6-rc.0  Reactive variable
reload                      1.1.4-rc.0  Reload the page while preserving application state.
reywood:iron-router-ga      0.6.1  Google analytics (universal edition) with some Iron Router sugar for tracking page views.
richsilv:pikaday            1.0.1+ Pikaday JavaScript Datepicker for Meteor — lightweight, no dependencies, modular CSS
sacha:spin                  2.3.1  Simple spinner package for Meteor
semantic:ui                 2.1.4  Official Semantic UI Integration for Meteor
service-configuration       1.0.5-rc.0  Manage the configuration for third-party services
session                     1.1.1-rc.0  Session variable
spacebars                   1.0.7-rc.0  Handlebars-like template language for Meteor
standard-minifiers          1.0.0-rc.1* Standard minifiers used with Meteor apps by default.
tap:i18n                    1.5.1  A comprehensive internationalization solution for Meteor
tracker                     1.0.8-rc.0  Dependency tracker to allow reactive callbacks
vsivsi:job-collection       1.2.3  A persistent and reactive job queue for Meteor, supporting distributed workers that can run anywhere
```

**Comment by dgreensp** [comment]
@LarsBuur see https://github.com/meteor/meteor/issues/5114 for a way to find out what packages are preventing update in the absence of a better error message for this case.

**Comment by LarsBuur** [comment]
Thanks @dgreensp. It was my /app/packages/npm-container that caused the problem. The error was:

```
While reading package from `/app/packages/npm-container`:
package.js:23:7: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.
```

This could be something that someone else would run into but not related to meteor core. 

There is a note on how to solve the problem here: https://github.com/meteorhacks/npm

**Comment by cee-dub** [comment]
I'm seeing an issue with production builds of apps using meteor 1.2 where minification removes `Accounts` and underlying dependencies like `Meteor._localStorage` despite including the `accounts-ui` package in my app. Any ideas?

**Comment by mjmasn** [comment]
It would be good if this error showed the full path of the file, in this case the file name and 'web.browser' is unique enough to narrow down which package and file the error is in but generally for a more generic name e.g. `methods.coffee` I'd have no idea if this was in the main project or one of 20+ local packages included in it:
```
=> Errors prevented startup:                  
   
   While processing files with coffeescript (for target web.browser):
   manager.coffee:85:1: unexpected indentation
   
=> Your application has errors. Waiting for file change.
```

**Comment by galdo666** [comment]
I just upgrade my project to Meteor 1.2 but if install ecmascript, the run process freezes at that line:

 => meteor run
 [[[[[ ~/Documents/ksource/linkone ]]]]]       

 => Started proxy.                              
 => Started MongoDB.                           
   Processing files with templating (for...  -

What is wrong?

**Comment by stubailo** [comment]
@galdo666 I think it's best to open new issues since Meteor 1.2 is released. Can you repost this as a separate issue?

Going to lock this thread.
