### ISSUE TITLE
1.3.3.1 incorrectly imports modules

### ISSUE THREAD

**Issue by tomitrescak** [meteor/meteor#7252]
After update to 1.3.3.1 all the imports that come from a module with only single export stopped working.

Meaning, if a module has only one export, now Meteor requires that it is exported as "default" export, otherwise it imports "null". I guess that is a bug not a feature.

**Comment by laosb** [comment]
I tried to reproduce with a `Posts.js` which `export { Posts }`, and do these in `meteor shell`:

![image](https://cloud.githubusercontent.com/assets/2545261/16174828/789b42c4-3608-11e6-9a26-d84f9be0b178.png)

**Comment by tomitrescak** [comment]
I'll try to produce reproducible environment. Weird part is that downgrading to 1.3.3 solved all import errors for me.

**Comment by d-winter** [comment]
Hi. I think I have the same issue here.
After updating to 1.3.3.1 my collections file cannot be imported any longer:

```
import { Mongo } from 'meteor/mongo'; // eslint-disable-line no-unused-vars

export const Projects = new Mongo.Collection('projects');
export const Tables = new Mongo.Collection('tables');
```

When I try to import the projects collection, there comes a cannot find module '/projectname/lib/collections'

**Comment by croogie** [comment]
The same here.

Doing `import * as Collections from '/lib/collections';` results in:


```
Unable to resolve some modules:

  "/Users/croogie/git/test/lib/collections" in /Users/croogie/git/test/client/configs/context.js (web.browser)
```

[Screenshot from Chrome console](http://i.imgur.com/3dH5cPZ.png)

**Comment by croogie** [comment]
As I've done small investigation it appears to me that problem with imports is not caused by Meteor itself but `bebel-root-slash-import` plugin included by default.

Removing it from `.babelrc` (in case of Mantra app) file solves problem.

**Comment by d-winter** [comment]
@croogie ah, cool. So we should file an issue on the babel-root-slash-import?

**Comment by croogie** [comment]
@d-winter Yeah, I think so. Actually I haven't time to figure out what it is exactly doing.

**Comment by benjamn** [comment]
@croogie @d-winter ahh I see we duplicated some debugging work, and thankfully we came to the same conclusion: https://github.com/meteor/meteor/issues/7225#issuecomment-227269000

**Comment by croogie** [comment]
Right, I believe that we can close this issue as well.
